Repository kubernetes-sigs/multi-tenancy, pull requests merged in 2019-09, with the labels that each got.

#48 Import existing namespace by adding OwnerReference
  tenant/pkg/controller/tenantnamespace/tenantnamespace_controller.go
  tenant/pkg/controller/tenantnamespace/tenantnamespace_controller_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#52 vc: vn-agent: test for /containerLogs, /run api proxy
  incubator/virtualcluster/pkg/vn-agent/server/server_test.go
  incubator/virtualcluster/pkg/vn-agent/testcerts/certs.go
  incubator/virtualcluster/pkg/vn-agent/testcerts/gencerts.sh
Labels: approved, cncf-cla: yes, lgtm, size/L

#55 Fix tenantnamespace controller event handler for namespace changes
  tenant/pkg/apis/apis.go
  tenant/pkg/controller/tenantnamespace/tenantnamespace_controller.go
  tenant/pkg/controller/tenantnamespace/tenantnamespace_controller_test.go
  tenant/pkg/controller/tenantnamespace/tenantnamespace_event_handler.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#57 Remove the deprecated `parent` label
  incubator/hnc/Makefile
  incubator/hnc/README.md
  incubator/hnc/config/crd/bases/hnc.x-k8s.io_hierarchies.yaml
  incubator/hnc/config/manager/manager.yaml
  incubator/hnc/controllers/hierarchy_controller_test.go
  incubator/hnc/controllers/label_controller.go
  incubator/hnc/controllers/namespace_controller_test.go
  incubator/hnc/controllers/object_controller_test.go
  incubator/hnc/controllers/setup.go
  incubator/hnc/controllers/suite_test.go
  incubator/hnc/controllers/test_labels/label_controller_test.go
  incubator/hnc/controllers/test_labels/object_controller_test.go
  incubator/hnc/controllers/test_labels/suite_test.go
  incubator/hnc/main.go
  incubator/hnc/scripts/hier-set-parent
  incubator/hnc/scripts/ns-set-parent
Labels: approved, cncf-cla: yes, lgtm, size/XL

#58 Allow missing parents (with a condition warning)
  incubator/hnc/controllers/hierarchy_controller.go
  incubator/hnc/controllers/hierarchy_controller_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#61 Updated readme
  README.md
Labels: approved, cncf-cla: yes, size/S

#62 Don't require or create unnecessary singletons
  incubator/hnc/controllers/hierarchy_controller.go
  incubator/hnc/controllers/hierarchy_controller_test.go
  incubator/hnc/controllers/namespace_controller.go
  incubator/hnc/controllers/namespace_controller_test.go
  incubator/hnc/controllers/object_controller.go
  incubator/hnc/controllers/object_controller_test.go
  incubator/hnc/controllers/setup.go
  incubator/hnc/pkg/forest/forest.go
  incubator/hnc/scripts/hier-set-parent
Labels: approved, cncf-cla: yes, lgtm, size/L

#64 Idiomatic watches in the hierarchy controller
  incubator/hnc/controllers/hierarchy_controller.go
  incubator/hnc/controllers/namespace_controller.go
  incubator/hnc/controllers/setup.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#60 Add README.md for Tenant Operator
  tenant/Makefile
  tenant/README.md
  tenant/config/manager/all_in_one.yaml
  tenant/config/manager/manager.yaml
  tenant/config/samples/tenancy_v1alpha1_tenantnamespace.yaml
Labels: approved, cncf-cla: yes, size/L

#70 Update dependencies
  incubator/hnc/go.mod
  incubator/hnc/go.sum
Labels: approved, cncf-cla: yes, lgtm, size/S

#71 Fixes to kind scripts
  incubator/hnc/kind-deploy
  incubator/hnc/kind-env
  incubator/hnc/kind-reset
  incubator/hnc/kind-watch
Labels: approved, cncf-cla: yes, lgtm, size/XS

#66 Lets namespaces be created/reconciled out-of-order
  incubator/hnc/controllers/hierarchy_controller.go
  incubator/hnc/controllers/hierarchy_controller_test.go
  incubator/hnc/controllers/object_controller.go
  incubator/hnc/controllers/object_controller_test.go
  incubator/hnc/pkg/forest/forest.go
  incubator/hnc/pkg/forest/forest_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#73 Fix wrong links
  tenant/README.md
Labels: approved, cncf-cla: yes, size/S

#74 Fix wrong namespace for clusterRoleBinding
  tenant/config/manager/all_in_one.yaml
Labels: approved, cncf-cla: yes, size/XS

#63 [syncer part 1] add multi cluster controller runtime and entry syncer…
  .gitignore
  incubator/virtualcluster/cmd/syncer/app/syncer.go
  incubator/virtualcluster/cmd/syncer/main.go
  incubator/virtualcluster/pkg/resource-syncer/cluster/cluster.go
  incubator/virtualcluster/pkg/resource-syncer/controller/controller.go
  incubator/virtualcluster/pkg/resource-syncer/handler/enqueue_object.go
  incubator/virtualcluster/pkg/resource-syncer/handler/types.go
  incubator/virtualcluster/pkg/resource-syncer/manager/manager.go
  incubator/virtualcluster/pkg/resource-syncer/reconciler/reconciler.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#65 Report any conflicts in propagated objects
  incubator/hnc/controllers/object_controller.go
  incubator/hnc/controllers/object_controller_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#75 Switch to traditional structure
  incubator/hnc/Dockerfile
  incubator/hnc/Makefile
  incubator/hnc/cmd/manager/main.go
  incubator/hnc/pkg/controllers/hierarchy_controller.go
  incubator/hnc/pkg/controllers/hierarchy_controller_test.go
  incubator/hnc/pkg/controllers/object_controller.go
  incubator/hnc/pkg/controllers/object_controller_test.go
  incubator/hnc/pkg/controllers/setup.go
  incubator/hnc/pkg/controllers/suite_test.go
  incubator/hnc/pkg/validators/hierarchy.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#77 Add adrianludwin as owner/reviewer
  OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/XS

#79 Initial kubectl plugin
  incubator/hnc/Makefile
  incubator/hnc/README.md
  incubator/hnc/cmd/kubectl/main.go
  incubator/hnc/devenv
  incubator/hnc/go.mod
  incubator/hnc/go.sum
  incubator/hnc/pkg/kubectl/root.go
  incubator/hnc/pkg/kubectl/setparent.go
  incubator/hnc/pkg/kubectl/show.go
  incubator/hnc/pkg/kubectl/sub.go
  incubator/hnc/pkg/kubectl/tree.go
  incubator/hnc/pkg/kubectl/unsetparent.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#78 Prevent cycles in validating webhook
  incubator/hnc/cmd/manager/main.go
  incubator/hnc/kind-deploy
  incubator/hnc/pkg/controllers/setup.go
  incubator/hnc/pkg/controllers/suite_test.go
  incubator/hnc/pkg/forest/forest.go
  incubator/hnc/pkg/validators/hierarchy.go
  incubator/hnc/pkg/validators/hierarchy_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#81 Fix a small bug
  tenant/pkg/controller/tenantnamespace/tenantnamespace_controller.go
Labels: approved, cncf-cla: yes, size/XS

#83 Show conditions in tree subcmd
  incubator/hnc/pkg/kubectl/tree.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#82 Reconcile namespace and singleton in tandem
  incubator/hnc/pkg/controllers/hierarchy_controller.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#85 Fix out-of-date readme issues
  incubator/hnc/README.md
Labels: approved, cncf-cla: yes, lgtm, size/M
