Repository kubernetes-sigs/multi-tenancy, pull requests merged in 2019-04, with the labels that each got.

#7 Initial commit of code for creating tenant and namespaces state in the
  poc/tenant-controller/cmd/tenant-ctl/main.go
  poc/tenant-controller/data/manifests/sample-tenant.yaml
  poc/tenant-controller/pkg/controllers/tenants/controller.go
  tools/lib/devtk/cmd-setup.sh
Labels: approved, cncf-cla: yes, size/M

#12 tenant-controller: add namespace/rbac sync on update of tenant
  poc/README.md
  poc/tenant-controller/data/manifests/rbac.yaml
  poc/tenant-controller/pkg/controllers/tenants/controller.go
Labels: approved, cncf-cla: yes, size/L

#18 add namespacetemplate type
  poc/tenant-controller/data/manifests/crd.yaml
  poc/tenant-controller/data/manifests/sample-nstemplate.yaml
  poc/tenant-controller/go.sum
  poc/tenant-controller/pkg/apis/tenants/v1alpha1/register.go
  poc/tenant-controller/pkg/apis/tenants/v1alpha1/types.go
  poc/tenant-controller/pkg/apis/tenants/v1alpha1/zz_generated.deepcopy.go
  poc/tenant-controller/pkg/clients/tenants/clientset/v1alpha1/typed/tenants/v1alpha1/fake/fake_namespacetemplate.go
  poc/tenant-controller/pkg/clients/tenants/clientset/v1alpha1/typed/tenants/v1alpha1/fake/fake_tenants_client.go
  poc/tenant-controller/pkg/clients/tenants/clientset/v1alpha1/typed/tenants/v1alpha1/generated_expansion.go
  poc/tenant-controller/pkg/clients/tenants/clientset/v1alpha1/typed/tenants/v1alpha1/namespacetemplate.go
  poc/tenant-controller/pkg/clients/tenants/clientset/v1alpha1/typed/tenants/v1alpha1/tenants_client.go
  poc/tenant-controller/pkg/clients/tenants/informers/externalversions/generic.go
  poc/tenant-controller/pkg/clients/tenants/informers/externalversions/tenants/v1alpha1/interface.go
  poc/tenant-controller/pkg/clients/tenants/informers/externalversions/tenants/v1alpha1/namespacetemplate.go
  poc/tenant-controller/pkg/clients/tenants/listers/tenants/v1alpha1/expansion_generated.go
  poc/tenant-controller/pkg/clients/tenants/listers/tenants/v1alpha1/namespacetemplate.go
  poc/tenant-controller/pkg/controllers/tenants/controller.go
Labels: approved, cncf-cla: yes, size/XL

#19 apply namespace template into tenant namespaces
  poc/tenant-controller/data/manifests/sample-nstemplate.yaml
  poc/tenant-controller/data/manifests/sample-tenant.yaml
  poc/tenant-controller/go.sum
  poc/tenant-controller/pkg/controllers/tenants/controller.go
  poc/tenant-controller/pkg/controllers/tenants/kubectl.go
Labels: approved, cncf-cla: yes, size/L

#21 Initial version of doc for soft multi-tenancy profile
  docs/README.md
  docs/profiles/profile-soft-multitenancy-s1.md
Labels: approved, cncf-cla: yes, size/L
