Repository kubernetes-sigs/multi-tenancy, pull requests merged in 2019-11, with the labels that each got.

#209 [incubator][VC] fix resource syncer issue
  incubator/virtualcluster/cmd/syncer/app/options/options.go
  incubator/virtualcluster/go.mod
  incubator/virtualcluster/pkg/syncer/controller/controller.go
  incubator/virtualcluster/pkg/syncer/controllers/configmap/controller.go
  incubator/virtualcluster/pkg/syncer/controllers/namespace/controller.go
  incubator/virtualcluster/pkg/syncer/controllers/pod/controller.go
  incubator/virtualcluster/pkg/syncer/controllers/secret/controller.go
  incubator/virtualcluster/pkg/syncer/conversion/helper.go
  incubator/virtualcluster/pkg/syncer/syncer.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#215 [incubator][VC] register virtual node in tenant master
  incubator/virtualcluster/README.md
  incubator/virtualcluster/cmd/syncer/app/config/config.go
  incubator/virtualcluster/cmd/syncer/app/options/options.go
  incubator/virtualcluster/cmd/vn-agent/main.go
  incubator/virtualcluster/config/setup/all_in_one.yaml
  incubator/virtualcluster/go.mod
  incubator/virtualcluster/go.sum
  incubator/virtualcluster/pkg/apis/tenancy/v1alpha1/clusterversion.go
  incubator/virtualcluster/pkg/controller/pki/pki.go
  incubator/virtualcluster/pkg/controller/virtualcluster/virtualcluster_controller.go
  incubator/virtualcluster/pkg/syncer/controllers/configmap/controller.go
  incubator/virtualcluster/pkg/syncer/controllers/namespace/controller.go
  incubator/virtualcluster/pkg/syncer/controllers/node/controller.go
  incubator/virtualcluster/pkg/syncer/controllers/node/node.go
  incubator/virtualcluster/pkg/syncer/controllers/pod/controller.go
  incubator/virtualcluster/pkg/syncer/controllers/register.go
  incubator/virtualcluster/pkg/syncer/controllers/secret/controller.go
  incubator/virtualcluster/pkg/syncer/syncer.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XL

#221 [incubator][vc] add service sync controller
  incubator/virtualcluster/pkg/syncer/controllers/register.go
  incubator/virtualcluster/pkg/syncer/controllers/service/controller.go
  incubator/virtualcluster/pkg/syncer/conversion/helper.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#224 [incubator][VC] vn-agent: support full klog options
  incubator/virtualcluster/cmd/vn-agent/app/options/options.go
  incubator/virtualcluster/cmd/vn-agent/app/server.go
  incubator/virtualcluster/cmd/vn-agent/main.go
  incubator/virtualcluster/pkg/vn-agent/certificate/cert.go
  incubator/virtualcluster/pkg/vn-agent/config/config.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#225 run go fmt in the code
  incubator/hnc/pkg/controllers/hierarchy_controller.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#223 Logic added to not propagate objects with nonempty finalizer list
  incubator/hnc/pkg/controllers/object_controller.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#226 Remove object conditions in v0.1
  incubator/hnc/api/v1alpha1/hierarchy_types.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#227 Create Metadata package
  incubator/hnc/pkg/controllers/hierarchy_controller.go
  incubator/hnc/pkg/controllers/object_controller.go
  incubator/hnc/pkg/metadata/metav1.go
  incubator/hnc/pkg/validators/object.go
  incubator/hnc/pkg/validators/object_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#214 Migrate benchmarks page
  benchmarks/.github/ISSUE_TEMPLATE/new-benchmark-test.md
  benchmarks/README.md
  benchmarks/config.yaml
  benchmarks/documentation/categories.md
  benchmarks/documentation/contributing.md
  benchmarks/documentation/definitions.md
  benchmarks/documentation/run.md
  benchmarks/documentation/types.md
  benchmarks/e2e/config/config.go
  benchmarks/e2e/config/utils.go
  benchmarks/e2e/tests/block_bind_mounts/README.md
  benchmarks/e2e/tests/block_cluster_resources/README.md
  benchmarks/e2e/tests/block_cluster_resources/block_cluster_resources.go
  benchmarks/e2e/tests/block_host_net_ports/README.md
  benchmarks/e2e/tests/block_multitenant_resources/README.md
  benchmarks/e2e/tests/block_nodeports/README.md
  benchmarks/e2e/tests/block_ns_quotas/README.md
  benchmarks/e2e/tests/block_other_tenant_resources/README.md
  benchmarks/e2e/tests/configure_ns_quotas/README.md
  benchmarks/e2e/tests/configure_ns_quotas/configure_ns_quotas.go
  benchmarks/e2e/tests/default_deny_net_conn/README.md
  benchmarks/e2e/tests/e2e.go
  benchmarks/e2e/tests/e2e_test.go
  benchmarks/go.mod
  benchmarks/go.sum
  benchmarks/main.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XXL

#230 revoke vn-agent code
  incubator/virtualcluster/cmd/vn-agent/app/options/options.go
  incubator/virtualcluster/cmd/vn-agent/app/server.go
  incubator/virtualcluster/cmd/vn-agent/main.go
  incubator/virtualcluster/pkg/vn-agent/certificate/cert.go
  incubator/virtualcluster/pkg/vn-agent/config/config.go
  incubator/virtualcluster/pkg/vn-agent/server/route.go
  incubator/virtualcluster/pkg/vn-agent/server/server.go
  incubator/virtualcluster/pkg/vn-agent/server/server_test.go
  incubator/virtualcluster/pkg/vn-agent/server/translate.go
  incubator/virtualcluster/pkg/vn-agent/testcerts/certs.go
  incubator/virtualcluster/pkg/vn-agent/testcerts/gencerts.sh
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/XXL

#216 Package kubectl plugin for krew
  incubator/hnc/Makefile
  incubator/hnc/hack/hnc.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#232 pull back syncer code
  incubator/virtualcluster/cmd/syncer/app/config/config.go
  incubator/virtualcluster/cmd/syncer/app/options/options.go
  incubator/virtualcluster/cmd/syncer/app/server.go
  incubator/virtualcluster/cmd/syncer/main.go
  incubator/virtualcluster/pkg/syncer/apis/config/types.go
  incubator/virtualcluster/pkg/syncer/cluster/cluster.go
  incubator/virtualcluster/pkg/syncer/controller/controller.go
  incubator/virtualcluster/pkg/syncer/controllers/configmap/controller.go
  incubator/virtualcluster/pkg/syncer/controllers/namespace/controller.go
  incubator/virtualcluster/pkg/syncer/controllers/node/controller.go
  incubator/virtualcluster/pkg/syncer/controllers/node/node.go
  incubator/virtualcluster/pkg/syncer/controllers/pod/controller.go
  incubator/virtualcluster/pkg/syncer/controllers/register.go
  incubator/virtualcluster/pkg/syncer/controllers/secret/controller.go
  incubator/virtualcluster/pkg/syncer/controllers/service/controller.go
  incubator/virtualcluster/pkg/syncer/conversion/helper.go
  incubator/virtualcluster/pkg/syncer/handler/enqueue_object.go
  incubator/virtualcluster/pkg/syncer/handler/types.go
  incubator/virtualcluster/pkg/syncer/listener/listener.go
  incubator/virtualcluster/pkg/syncer/manager/manager.go
  incubator/virtualcluster/pkg/syncer/reconciler/reconciler.go
  incubator/virtualcluster/pkg/syncer/syncer.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#233 Fix unicode character in kubectl-hnc tree
  incubator/hnc/pkg/kubectl/tree.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#234 Update generated CRD manifest file
  incubator/hnc/config/crd/bases/hnc.x-k8s.io_hierarchyconfigurations.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#236 Enable one-line installation and smooth onboarding experience
  incubator/hnc/.gitignore
  incubator/hnc/Makefile
  incubator/hnc/README.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#237 Ensure hierarchy doesn't violate required children
  incubator/hnc/pkg/validators/hierarchy.go
  incubator/hnc/pkg/validators/hierarchy_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#239 HNC: forbid propagated objects from being modified
  incubator/hnc/pkg/controllers/object_controller.go
  incubator/hnc/pkg/object/object.go
  incubator/hnc/pkg/validators/object.go
  incubator/hnc/pkg/validators/object_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#242 fix typo in tenancy
  tenant/pkg/apis/tenancy/v1alpha1/tenant_types.go
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/XS

#244 Add tenant admin users and set up basic RBAC rules
  tenant/Dockerfile
  tenant/config/crds/tenancy_v1alpha1_tenant.yaml
  tenant/config/manager/all_in_one.yaml
  tenant/config/rbac/rbac_role.yaml
  tenant/config/samples/tenancy_v1alpha1_tenant.yaml
  tenant/pkg/apis/tenancy/v1alpha1/tenant_types.go
  tenant/pkg/apis/tenancy/v1alpha1/zz_generated.deepcopy.go
  tenant/pkg/controller/tenant/tenant_controller.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#245 Revert "revoke vn-agent code"
  incubator/virtualcluster/cmd/vn-agent/app/options/options.go
  incubator/virtualcluster/cmd/vn-agent/app/server.go
  incubator/virtualcluster/cmd/vn-agent/main.go
  incubator/virtualcluster/pkg/vn-agent/certificate/cert.go
  incubator/virtualcluster/pkg/vn-agent/config/config.go
  incubator/virtualcluster/pkg/vn-agent/server/route.go
  incubator/virtualcluster/pkg/vn-agent/server/server.go
  incubator/virtualcluster/pkg/vn-agent/server/server_test.go
  incubator/virtualcluster/pkg/vn-agent/server/translate.go
  incubator/virtualcluster/pkg/vn-agent/testcerts/certs.go
  incubator/virtualcluster/pkg/vn-agent/testcerts/gencerts.sh
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/XXL

#246 Revert "pull back syncer code"
  incubator/virtualcluster/cmd/syncer/app/config/config.go
  incubator/virtualcluster/cmd/syncer/app/options/options.go
  incubator/virtualcluster/cmd/syncer/app/server.go
  incubator/virtualcluster/cmd/syncer/main.go
  incubator/virtualcluster/pkg/syncer/apis/config/types.go
  incubator/virtualcluster/pkg/syncer/cluster/cluster.go
  incubator/virtualcluster/pkg/syncer/controller/controller.go
  incubator/virtualcluster/pkg/syncer/controllers/configmap/controller.go
  incubator/virtualcluster/pkg/syncer/controllers/namespace/controller.go
  incubator/virtualcluster/pkg/syncer/controllers/node/controller.go
  incubator/virtualcluster/pkg/syncer/controllers/node/node.go
  incubator/virtualcluster/pkg/syncer/controllers/pod/controller.go
  incubator/virtualcluster/pkg/syncer/controllers/register.go
  incubator/virtualcluster/pkg/syncer/controllers/secret/controller.go
  incubator/virtualcluster/pkg/syncer/controllers/service/controller.go
  incubator/virtualcluster/pkg/syncer/conversion/helper.go
  incubator/virtualcluster/pkg/syncer/handler/enqueue_object.go
  incubator/virtualcluster/pkg/syncer/handler/types.go
  incubator/virtualcluster/pkg/syncer/listener/listener.go
  incubator/virtualcluster/pkg/syncer/manager/manager.go
  incubator/virtualcluster/pkg/syncer/reconciler/reconciler.go
  incubator/virtualcluster/pkg/syncer/syncer.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#247 [incubator][VC] update virtual node status by events from super master
  incubator/virtualcluster/pkg/syncer/controllers/node/controller.go
  incubator/virtualcluster/pkg/syncer/controllers/node/node.go
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/L

#229 add Virtualcluster status for syncer to watch
  incubator/virtualcluster/Makefile
  incubator/virtualcluster/README.md
  incubator/virtualcluster/config/sampleswithspec/clusterversion_v1.yaml
  incubator/virtualcluster/config/sampleswithspec/virtualcluster_1.yaml
  incubator/virtualcluster/config/setup/all_in_one.yaml
  incubator/virtualcluster/go.mod
  incubator/virtualcluster/hack/lib/docker-image.sh
  incubator/virtualcluster/hack/lib/init.sh
  incubator/virtualcluster/pkg/apis/tenancy/v1alpha1/zz_generated.deepcopy.go
  incubator/virtualcluster/pkg/controller/clusterversion/clusterversion_controller.go
  incubator/virtualcluster/pkg/controller/util/util.go
  incubator/virtualcluster/pkg/controller/virtualcluster/virtualcluster_controller.go
  incubator/virtualcluster/pkg/syncer/controller/controller.go
  incubator/virtualcluster/pkg/syncer/controllers/configmap/controller.go
  incubator/virtualcluster/pkg/syncer/controllers/namespace/controller.go
  incubator/virtualcluster/pkg/syncer/controllers/pod/controller.go
  incubator/virtualcluster/pkg/syncer/controllers/register.go
  incubator/virtualcluster/pkg/syncer/controllers/secret/controller.go
  incubator/virtualcluster/pkg/syncer/controllers/service/controller.go
  incubator/virtualcluster/pkg/syncer/syncer.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#252 Add RBAC to allow tenant admin to create tenantnamespace CR and get the created namespace.
  tenant/config/crds/tenancy_v1alpha1_tenant.yaml
  tenant/config/manager/all_in_one.yaml
  tenant/config/rbac/rbac_role.yaml
  tenant/pkg/controller/tenant/tenant_controller.go
  tenant/pkg/controller/tenantnamespace/tenantnamespace_controller.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#240 fix Canonical function
  incubator/hnc/pkg/object/object.go
  incubator/hnc/pkg/object/object_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#241 fix some typo
  incubator/hnc/pkg/controllers/hierarchy_controller.go
  incubator/hnc/pkg/forest/forest.go
  incubator/hnc/pkg/forest/forest_test.go
  incubator/hnc/pkg/validators/hierarchy.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#253 Add OwnedNamespace field in TenantNamespace CRD status
  tenant/config/crds/tenancy_v1alpha1_tenantnamespace.yaml
  tenant/pkg/apis/tenancy/v1alpha1/tenantnamespace_types.go
  tenant/pkg/controller/tenantnamespace/tenantnamespace_controller.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#254 [incubator][VC] support service account for tenant
  incubator/virtualcluster/go.mod
  incubator/virtualcluster/pkg/syncer/controller/controller.go
  incubator/virtualcluster/pkg/syncer/controllers/node/controller.go
  incubator/virtualcluster/pkg/syncer/controllers/pod/controller.go
  incubator/virtualcluster/pkg/syncer/controllers/register.go
  incubator/virtualcluster/pkg/syncer/controllers/secret/controller.go
  incubator/virtualcluster/pkg/syncer/controllers/service/controller.go
  incubator/virtualcluster/pkg/syncer/controllers/serviceaccount/controller.go
  incubator/virtualcluster/pkg/syncer/conversion/helper.go
  incubator/virtualcluster/pkg/syncer/utils/client.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#255 Remove namespace from tenant clusterrole when tenantnamespace CR is deleted
  tenant/pkg/controller/tenantnamespace/tenantnamespace_controller.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#256 Update Tenant README.md
  tenant/README.md
Labels: approved, cncf-cla: yes, size/M

#263 [incubator][VC] flying check for vckbcfg option
  incubator/virtualcluster/cmd/vcctl/subcmd/create.go
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/XS

#261 [incubator][VC] inject service related env var to pod
  incubator/virtualcluster/pkg/syncer/controllers/pod/controller.go
  incubator/virtualcluster/pkg/syncer/conversion/helper.go
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/M

#262 [incubator][VC] add work queue for upward syncer
  incubator/virtualcluster/pkg/syncer/constants/constants.go
  incubator/virtualcluster/pkg/syncer/controllers/configmap/controller.go
  incubator/virtualcluster/pkg/syncer/controllers/namespace/controller.go
  incubator/virtualcluster/pkg/syncer/controllers/node/controller.go
  incubator/virtualcluster/pkg/syncer/controllers/node/uws.go
  incubator/virtualcluster/pkg/syncer/controllers/pod/controller.go
  incubator/virtualcluster/pkg/syncer/controllers/pod/uws.go
  incubator/virtualcluster/pkg/syncer/controllers/secret/controller.go
  incubator/virtualcluster/pkg/syncer/controllers/service/controller.go
  incubator/virtualcluster/pkg/syncer/controllers/service/uws.go
  incubator/virtualcluster/pkg/syncer/controllers/serviceaccount/controller.go
  incubator/virtualcluster/pkg/syncer/conversion/helper.go
  incubator/virtualcluster/pkg/syncer/manager/manager.go
  incubator/virtualcluster/pkg/syncer/syncer.go
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/XL

#268 Fix benchmark IDs in README.md
  benchmarks/README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#249 fix golint errors
  benchmarks/e2e/tests/configure_ns_quotas/configure_ns_quotas.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#269 [incubator][VC] add work queue for virtual cluster controller
  incubator/virtualcluster/config/sampleswithspec/virtualcluster_1.yaml
  incubator/virtualcluster/pkg/syncer/controller/controller.go
  incubator/virtualcluster/pkg/syncer/conversion/helper.go
  incubator/virtualcluster/pkg/syncer/syncer.go
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/L

#272 add a vc demo video
  incubator/virtualcluster/README.md
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/XS

#277 [incubator][VC] support to teardown virtual cluster from syncer
  incubator/virtualcluster/pkg/syncer/cluster/cluster.go
  incubator/virtualcluster/pkg/syncer/controller/controller.go
  incubator/virtualcluster/pkg/syncer/controllers/configmap/controller.go
  incubator/virtualcluster/pkg/syncer/controllers/endpoints/controller.go
  incubator/virtualcluster/pkg/syncer/controllers/namespace/controller.go
  incubator/virtualcluster/pkg/syncer/controllers/node/controller.go
  incubator/virtualcluster/pkg/syncer/controllers/pod/controller.go
  incubator/virtualcluster/pkg/syncer/controllers/secret/controller.go
  incubator/virtualcluster/pkg/syncer/controllers/service/controller.go
  incubator/virtualcluster/pkg/syncer/controllers/serviceaccount/controller.go
  incubator/virtualcluster/pkg/syncer/listener/listener.go
  incubator/virtualcluster/pkg/syncer/syncer.go
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/L

#270 Set flags to enable new object controller
  incubator/hnc/Makefile
  incubator/hnc/cmd/manager/main.go
  incubator/hnc/pkg/controllers/object_controller_new.go
  incubator/hnc/pkg/controllers/setup.go
  incubator/hnc/pkg/controllers/suite_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#243 Config Cloud Build YAML file for HNC releases
  incubator/hnc/Makefile
  incubator/hnc/README.md
  incubator/hnc/cloudbuild.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#279 [incubator][VC] create tenant master under clusername namespace
  incubator/virtualcluster/cmd/vcctl/subcmd/create.go
  incubator/virtualcluster/config/setup/all_in_one.yaml
  incubator/virtualcluster/pkg/controller/pki/pki.go
  incubator/virtualcluster/pkg/controller/virtualcluster/virtualcluster_controller.go
  incubator/virtualcluster/pkg/syncer/syncer.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#280 [incubator][VC] reconcile pod deletion event
  incubator/virtualcluster/cmd/syncer/app/options/options.go
  incubator/virtualcluster/cmd/vcctl/subcmd/create.go
  incubator/virtualcluster/pkg/syncer/cluster/cluster.go
  incubator/virtualcluster/pkg/syncer/constants/constants.go
  incubator/virtualcluster/pkg/syncer/controller/controller.go
  incubator/virtualcluster/pkg/syncer/controllers/pod/controller.go
  incubator/virtualcluster/pkg/syncer/controllers/pod/uws.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#283 Add Jerry(zhuangqh) to VC approver
  incubator/virtualcluster/OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/XS
