Repository kubernetes-sigs/multi-tenancy, pull requests merged in 2019-05, with the labels that each got.

#22 Update link.md
  docs/links.md
Labels: cncf-cla: yes, size/XS

#25 Add slides from KubeCon EU 2019 Deep dive to docs
  docs/links.md
Labels: approved, cncf-cla: yes, size/XS

#26 Slight restructure of docs page
  docs/links.md
Labels: approved, cncf-cla: yes, size/S
