Repository kubernetes-sigs/multi-tenancy, pull requests merged in 2019-12, with the labels that each got.

#276 Closes #275: fix certmanager version
  incubator/hnc/Makefile
  incubator/hnc/config/certmanager/certificate.yaml
  incubator/hnc/config/default/kustomization.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#284 [incubator][VC] add script to run k8s e2e test on a local cluster
  incubator/virtualcluster/Makefile
  incubator/virtualcluster/hack/make-rules/test-e2e-k8s.sh
Labels: approved, cncf-cla: yes, lgtm, size/M

#285 [incubator][VC] fix: mutate spec of init containers of the pod
  incubator/virtualcluster/pkg/syncer/conversion/helper.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#287 Fix a build error
  incubator/virtualcluster/pkg/syncer/controllers/serviceaccount/controller.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#289 Fix HNC to work with cert-manager v0.11.0
  incubator/hnc/Makefile
  incubator/hnc/config/certmanager/certificate.yaml
  incubator/hnc/config/certmanager/kustomizeconfig.yaml
  incubator/hnc/config/crd/patches/cainjection_in_hierarchies.yaml
  incubator/hnc/config/default/webhookcainjection_patch.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#288 [incubator][VC] fix: replace fieldRef env with virtual pod's value
  incubator/virtualcluster/pkg/syncer/controllers/pod/controller.go
  incubator/virtualcluster/pkg/syncer/controllers/pod/uws.go
  incubator/virtualcluster/pkg/syncer/conversion/helper.go
  incubator/virtualcluster/pkg/syncer/conversion/helper_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#290 Give the HNC service account all required verbs
  incubator/hnc/config/rbac/role.yaml
  incubator/hnc/pkg/controllers/object_controller.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#282 Initial version of new object controller
  incubator/hnc/pkg/controllers/object_controller_new.go
  incubator/hnc/pkg/controllers/object_controller_test.go
  incubator/hnc/pkg/controllers/setup.go
  incubator/hnc/pkg/forest/forest.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#294 Fix flaky object controller test
  incubator/hnc/pkg/controllers/object_controller_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#295 [incubator][VC] feature: observe pod value update event
  incubator/virtualcluster/pkg/syncer/controllers/pod/controller.go
  incubator/virtualcluster/pkg/syncer/conversion/equality.go
  incubator/virtualcluster/pkg/syncer/conversion/equality_test.go
  incubator/virtualcluster/pkg/syncer/conversion/helper.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#296 [incubator][VC] feature: observe value update event
  incubator/virtualcluster/pkg/syncer/controllers/configmap/controller.go
  incubator/virtualcluster/pkg/syncer/conversion/equality.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#297 [incubator][VC] observe endpoints, secrets value update event
  incubator/virtualcluster/pkg/syncer/controllers/endpoints/controller.go
  incubator/virtualcluster/pkg/syncer/controllers/namespace/controller.go
  incubator/virtualcluster/pkg/syncer/controllers/secret/controller.go
  incubator/virtualcluster/pkg/syncer/conversion/equality.go
  incubator/virtualcluster/pkg/syncer/conversion/equality_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#298 [incubator][VC] fix: assign node capacity to virtual node
  incubator/virtualcluster/pkg/syncer/controllers/node/node.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#301 Check Crit condition in object controller
  incubator/hnc/pkg/controllers/hierarchy_controller.go
  incubator/hnc/pkg/controllers/object_controller_new.go
  incubator/hnc/pkg/controllers/object_controller_test.go
  incubator/hnc/pkg/forest/forest.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#305 Change name of kubectl plugin and fix krew.
  incubator/hnc/Makefile
  incubator/hnc/README.md
  incubator/hnc/hack/krew-hierarchical-namespaces.yaml
  incubator/hnc/pkg/kubectl/root.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#310 Set v0.2 object controller as default
  incubator/hnc/Makefile
  incubator/hnc/config/default/manager_auth_proxy_patch.yaml
  incubator/hnc/pkg/controllers/suite_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#308 Improve kubectl subcommands to match naming doc
  incubator/hnc/pkg/kubectl/create.go
  incubator/hnc/pkg/kubectl/describe.go
  incubator/hnc/pkg/kubectl/root.go
  incubator/hnc/pkg/kubectl/set.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#311 change the vc setting for ACK
  incubator/virtualcluster/config/setup/all_in_one.yaml
  incubator/virtualcluster/pkg/controller/virtualcluster/virtualcluster_controller.go
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/XS

#312 Turn Condition.code into a string, not an enum
  incubator/hnc/api/v1alpha1/hierarchy_types.go
  incubator/hnc/config/crd/bases/hnc.x-k8s.io_hierarchyconfigurations.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#313 Fix cert-manager for older versions of K8s
  incubator/hnc/Makefile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#319 Remove redundant per-namespace locks
  incubator/hnc/pkg/controllers/hierarchy_controller.go
  incubator/hnc/pkg/controllers/object_controller_new.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#317 Improve RequiredChildConflict condition
  incubator/hnc/api/v1alpha1/hierarchy_types.go
  incubator/hnc/config/crd/bases/hnc.x-k8s.io_hierarchyconfigurations.yaml
  incubator/hnc/pkg/controllers/hierarchy_controller.go
  incubator/hnc/pkg/controllers/hierarchy_controller_test.go
  incubator/hnc/pkg/forest/forest.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#320 Only enqueue descendants when labels are changed
  incubator/hnc/pkg/controllers/hierarchy_controller.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#323 [incubator][VC]Code cleanup plus minor bug fix
  incubator/virtualcluster/pkg/syncer/cluster/cluster.go
  incubator/virtualcluster/pkg/syncer/controllers/node/uws.go
  incubator/virtualcluster/pkg/syncer/controllers/pod/controller.go
  incubator/virtualcluster/pkg/syncer/controllers/pod/uws.go
  incubator/virtualcluster/pkg/syncer/syncer.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#327 [incubator][VC] Clean up MultiClusterController
  incubator/virtualcluster/pkg/syncer/cluster/cluster.go
  incubator/virtualcluster/pkg/syncer/controllers/configmap/controller.go
  incubator/virtualcluster/pkg/syncer/controllers/endpoints/controller.go
  incubator/virtualcluster/pkg/syncer/controllers/namespace/controller.go
  incubator/virtualcluster/pkg/syncer/controllers/node/controller.go
  incubator/virtualcluster/pkg/syncer/controllers/pod/controller.go
  incubator/virtualcluster/pkg/syncer/controllers/secret/controller.go
  incubator/virtualcluster/pkg/syncer/controllers/service/controller.go
  incubator/virtualcluster/pkg/syncer/controllers/serviceaccount/controller.go
  incubator/virtualcluster/pkg/syncer/listener/listener.go
  incubator/virtualcluster/pkg/syncer/mccontroller/mccontroller.go
  incubator/virtualcluster/pkg/syncer/syncer.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#321 Create reconcile counters and a flag to enable it
  incubator/hnc/cmd/manager/main.go
  incubator/hnc/pkg/controllers/hierarchy_controller.go
  incubator/hnc/pkg/controllers/object_controller.go
  incubator/hnc/pkg/controllers/object_controller_new.go
  incubator/hnc/pkg/controllers/setup.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#322 Add conditions for object problems
  incubator/hnc/api/v1alpha1/hierarchy_types.go
  incubator/hnc/pkg/controllers/hierarchy_controller.go
  incubator/hnc/pkg/controllers/object_controller_new.go
  incubator/hnc/pkg/controllers/object_controller_test.go
  incubator/hnc/pkg/controllers/setup.go
  incubator/hnc/pkg/forest/forest.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#325 [incubator][VC] back populate pod related event to tenant
  incubator/virtualcluster/pkg/syncer/constants/constants.go
  incubator/virtualcluster/pkg/syncer/controllers/event/controller.go
  incubator/virtualcluster/pkg/syncer/controllers/event/uws.go
  incubator/virtualcluster/pkg/syncer/controllers/pod/controller.go
  incubator/virtualcluster/pkg/syncer/controllers/pod/uws.go
  incubator/virtualcluster/pkg/syncer/controllers/register.go
  incubator/virtualcluster/pkg/syncer/conversion/helper.go
  incubator/virtualcluster/pkg/syncer/mccontroller/mccontroller.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#332 Use Cloud Build for everything and update docs
  incubator/hnc/Makefile
  incubator/hnc/README.md
  incubator/hnc/cloudbuild.yaml
  incubator/hnc/hack/ci-test.sh
Labels: approved, cncf-cla: yes, lgtm, size/L

#334 [incubator][VC] setup prometheus metrics framework
  incubator/virtualcluster/cmd/syncer/app/config/config.go
  incubator/virtualcluster/cmd/syncer/app/options/options.go
  incubator/virtualcluster/cmd/syncer/app/server.go
  incubator/virtualcluster/go.mod
  incubator/virtualcluster/pkg/syncer/controllers/pod/controller.go
  incubator/virtualcluster/pkg/syncer/metrics/metrics.go
  incubator/virtualcluster/pkg/syncer/syncer.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#315 add period checker for pod controller
  incubator/virtualcluster/pkg/syncer/controllers/configmap/controller.go
  incubator/virtualcluster/pkg/syncer/controllers/endpoints/controller.go
  incubator/virtualcluster/pkg/syncer/controllers/namespace/controller.go
  incubator/virtualcluster/pkg/syncer/controllers/node/controller.go
  incubator/virtualcluster/pkg/syncer/controllers/pod/checker.go
  incubator/virtualcluster/pkg/syncer/controllers/pod/controller.go
  incubator/virtualcluster/pkg/syncer/controllers/secret/controller.go
  incubator/virtualcluster/pkg/syncer/controllers/service/controller.go
  incubator/virtualcluster/pkg/syncer/controllers/serviceaccount/controller.go
  incubator/virtualcluster/pkg/syncer/conversion/helper.go
  incubator/virtualcluster/pkg/syncer/manager/manager.go
  incubator/virtualcluster/pkg/syncer/mccontroller/mccontroller.go
Labels: approved, cncf-cla: yes, lgtm, size/L
