Repository kubernetes-sigs/multi-tenancy, pull requests merged in 2019-08, with the labels that each got.

#34 Request to be owner and reviewer
  OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/XS

#35 Add TenantAdminNamespaceName field and remove unused code
  tenant/config/crds/tenancy_v1alpha1_tenant.yaml
  tenant/config/rbac/rbac_role.yaml
  tenant/pkg/apis/tenancy/v1alpha1/tenant_types.go
  tenant/pkg/controller/tenant/tenant_controller.go
  tenant/pkg/controller/tenant/tenant_controller_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#28 Create profile-single-tenant-cluster.md
  docs/profiles/profile-single-tenant-cluster.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#37 [incubator] Add virtualcluster project owners
  incubator/virtualcluster/OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/S

#38 Reconcile for creating TenantAdminNamespace on Tenant creation
  tenant/config/rbac/rbac_role.yaml
  tenant/config/samples/tenancy_v1alpha1_tenant.yaml
  tenant/pkg/controller/tenant/tenant_controller.go
  tenant/pkg/controller/tenant/tenant_controller_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#39 Add watcher for tenantAdminNamespace
  tenant/pkg/controller/tenant/tenant_controller.go
  tenant/pkg/controller/tenant/tenant_controller_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#40 Add TenantNamespace CRD scaffolding codes
  tenant/config/crds/tenancy_v1alpha1_tenantnamespace.yaml
  tenant/config/rbac/rbac_role.yaml
  tenant/config/samples/tenancy_v1alpha1_tenantnamespace.yaml
  tenant/pkg/apis/tenancy/v1alpha1/tenantnamespace_types.go
  tenant/pkg/apis/tenancy/v1alpha1/tenantnamespace_types_test.go
  tenant/pkg/apis/tenancy/v1alpha1/zz_generated.deepcopy.go
  tenant/pkg/controller/add_tenantnamespace.go
  tenant/pkg/controller/tenantnamespace/tenantnamespace_controller.go
  tenant/pkg/controller/tenantnamespace/tenantnamespace_controller_suite_test.go
  tenant/pkg/controller/tenantnamespace/tenantnamespace_controller_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#41 Add Name field in TenantNamespace CRD
  tenant/config/crds/tenancy_v1alpha1_tenantnamespace.yaml
  tenant/config/rbac/rbac_role.yaml
  tenant/pkg/apis/tenancy/v1alpha1/tenantnamespace_types.go
  tenant/pkg/controller/tenantnamespace/tenantnamespace_controller.go
  tenant/pkg/controller/tenantnamespace/tenantnamespace_controller_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#46 Support optional Name in TenantNamespaceSpec
  tenant/config/crds/tenancy_v1alpha1_tenantnamespace.yaml
  tenant/pkg/apis/tenancy/v1alpha1/tenantnamespace_types.go
  tenant/pkg/controller/tenantnamespace/tenantnamespace_controller.go
  tenant/pkg/controller/tenantnamespace/tenantnamespace_controller_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L
