Repository kubernetes-sigs/multi-tenancy, pull requests merged in 2019-10, with the labels that each got.

#87 Add scaffolding code for Tenant CRD webhook
  tenant/pkg/webhook/default_server/add_validating_tenant.go
  tenant/pkg/webhook/default_server/tenant/validating/create_update_webhook.go
  tenant/pkg/webhook/default_server/tenant/validating/tenant_create_update_handler.go
  tenant/pkg/webhook/default_server/tenant/validating/webhooks.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#84 Restructure NS enqueuing; improve thread safety
  incubator/hnc/pkg/controllers/hierarchy_controller.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#86 Add validation admission checks for TenantNamespace - Part I
  tenant/pkg/webhook/default_server/tenantnamespace/validating/tenantnamespace_create_update_handler.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#96 Add namespace name validity check for TenantNamespace CR
  tenant/pkg/controller/tenantnamespace/tenantnamespace_controller.go
  tenant/pkg/util/tenant_utils.go
  tenant/pkg/webhook/default_server/tenantnamespace/validating/tenantnamespace_create_update_handler.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#97 Remove some noisy log messages
  incubator/hnc/pkg/controllers/object_controller.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#95 Self-service subnamespace creation (reconciler only)
  incubator/hnc/api/v1alpha1/hierarchy_types.go
  incubator/hnc/api/v1alpha1/zz_generated.deepcopy.go
  incubator/hnc/config/crd/bases/hnc.x-k8s.io_hierarchies.yaml
  incubator/hnc/pkg/controllers/hierarchy_controller.go
  incubator/hnc/pkg/controllers/hierarchy_controller_test.go
  incubator/hnc/pkg/forest/forest.go
  incubator/hnc/pkg/kubectl/show.go
  incubator/hnc/pkg/kubectl/sub.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#114 Rename 'patches' to 'patchesStrategicMerge' and update README with missing dependencies install intructions
  incubator/hnc/README.md
  incubator/hnc/config/crd/kustomization.yaml
  incubator/hnc/config/default/kustomization.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#98 Change hier singleton to hierarchy
  incubator/hnc/api/v1alpha1/hierarchy_types.go
  incubator/hnc/api/v1alpha1/zz_generated.deepcopy.go
  incubator/hnc/config/crd/bases/hnc.x-k8s.io_hierarchyconfigurations.yaml
  incubator/hnc/pkg/controllers/hierarchy_controller.go
  incubator/hnc/pkg/controllers/hierarchy_controller_test.go
  incubator/hnc/pkg/controllers/object_controller_test.go
  incubator/hnc/pkg/kubectl/root.go
  incubator/hnc/pkg/kubectl/tree.go
  incubator/hnc/pkg/validators/hierarchy.go
  incubator/hnc/pkg/validators/hierarchy_test.go
  incubator/hnc/scripts/hier-set-parent
  incubator/hnc/scripts/hier-show
Labels: approved, cncf-cla: yes, lgtm, size/L

#121 Improved onboarding instructions
  incubator/hnc/README.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#116 Passes new kinds to be inherited
  incubator/hnc/pkg/controllers/setup.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#117 run code-generator to generate clientset
  incubator/virtualcluster/pkg/apis/tenancy/v1alpha1/zz_generated.deepcopy.go
  incubator/virtualcluster/pkg/client/clientset/versioned/clientset.go
  incubator/virtualcluster/pkg/client/clientset/versioned/doc.go
  incubator/virtualcluster/pkg/client/clientset/versioned/fake/clientset_generated.go
  incubator/virtualcluster/pkg/client/clientset/versioned/fake/doc.go
  incubator/virtualcluster/pkg/client/clientset/versioned/fake/register.go
  incubator/virtualcluster/pkg/client/clientset/versioned/scheme/doc.go
  incubator/virtualcluster/pkg/client/clientset/versioned/scheme/register.go
  incubator/virtualcluster/pkg/client/clientset/versioned/typed/tenancy/v1alpha1/doc.go
  incubator/virtualcluster/pkg/client/clientset/versioned/typed/tenancy/v1alpha1/fake/doc.go
  incubator/virtualcluster/pkg/client/clientset/versioned/typed/tenancy/v1alpha1/fake/fake_tenancy_client.go
  incubator/virtualcluster/pkg/client/clientset/versioned/typed/tenancy/v1alpha1/fake/fake_virtualcluster.go
  incubator/virtualcluster/pkg/client/clientset/versioned/typed/tenancy/v1alpha1/generated_expansion.go
  incubator/virtualcluster/pkg/client/clientset/versioned/typed/tenancy/v1alpha1/tenancy_client.go
  incubator/virtualcluster/pkg/client/clientset/versioned/typed/tenancy/v1alpha1/virtualcluster.go
  incubator/virtualcluster/pkg/client/informers/externalversions/factory.go
  incubator/virtualcluster/pkg/client/informers/externalversions/generic.go
  incubator/virtualcluster/pkg/client/informers/externalversions/internalinterfaces/factory_interfaces.go
  incubator/virtualcluster/pkg/client/informers/externalversions/tenancy/interface.go
  incubator/virtualcluster/pkg/client/informers/externalversions/tenancy/v1alpha1/interface.go
  incubator/virtualcluster/pkg/client/informers/externalversions/tenancy/v1alpha1/virtualcluster.go
  incubator/virtualcluster/pkg/client/listers/tenancy/v1alpha1/expansion_generated.go
  incubator/virtualcluster/pkg/client/listers/tenancy/v1alpha1/virtualcluster.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#115 Add proper conditions to Hierarchy status
  incubator/hnc/api/v1alpha1/hierarchy_types.go
  incubator/hnc/api/v1alpha1/zz_generated.deepcopy.go
  incubator/hnc/config/crd/bases/hnc.x-k8s.io_hierarchyconfigurations.yaml
  incubator/hnc/pkg/controllers/hierarchy_controller.go
  incubator/hnc/pkg/controllers/hierarchy_controller_test.go
  incubator/hnc/pkg/forest/forest.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#123 HNC: Fix for typo in kustomization yaml file
  incubator/hnc/config/crd/kustomization.yaml
  incubator/hnc/config/default/kustomization.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#118 Create bash script for CI
  incubator/hnc/Makefile
  incubator/hnc/hack/ci-test.sh
Labels: approved, cncf-cla: yes, lgtm, size/M

#127 Add GOPATH/bin to PATH env var in ci-test.sh
  incubator/hnc/hack/ci-test.sh
Labels: approved, cncf-cla: yes, lgtm, size/S

#129 Add the `tree` label to all namespaces with explicit hierarchies
  incubator/hnc/pkg/controllers/hierarchy_controller.go
  incubator/hnc/pkg/controllers/hierarchy_controller_test.go
  incubator/hnc/pkg/controllers/object_controller.go
  incubator/hnc/pkg/forest/forest.go
  incubator/hnc/pkg/forest/forest_test.go
Labels: approved, cncf-cla: yes, size/L

#126 Refactor hierarchy controller
  incubator/hnc/pkg/controllers/hierarchy_controller.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#125 Add admission webhook for tenant CR
  tenant/pkg/webhook/default_server/tenant/validating/tenant_create_update_handler.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#133 Update test to verify specific condition codes
  incubator/hnc/pkg/controllers/hierarchy_controller_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#134 Add CRIT_ANCESTOR condition to hier controller
  incubator/hnc/pkg/controllers/hierarchy_controller.go
  incubator/hnc/pkg/controllers/hierarchy_controller_test.go
  incubator/hnc/pkg/forest/forest.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#128 [incubator][vc] vn-agent support streaming api
  incubator/virtualcluster/go.mod
  incubator/virtualcluster/pkg/vn-agent/server/route.go
  incubator/virtualcluster/pkg/vn-agent/server/server_test.go
  incubator/virtualcluster/pkg/vn-agent/testcerts/gencerts.sh
Labels: approved, cncf-cla: yes, lgtm, size/XL

#141 fill out virtualcluster and clusterversion
  incubator/virtualcluster/config/crds/tenancy_v1alpha1_clusterversion.yaml
  incubator/virtualcluster/config/crds/tenancy_v1alpha1_virtualcluster.yaml
  incubator/virtualcluster/config/rbac/rbac_role.yaml
  incubator/virtualcluster/pkg/apis/tenancy/v1alpha1/clusterversion_types.go
  incubator/virtualcluster/pkg/apis/tenancy/v1alpha1/virtualcluster_types.go
  incubator/virtualcluster/pkg/apis/tenancy/v1alpha1/zz_generated.deepcopy.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#145 kubectl hnc set-parent command fix
  incubator/hnc/pkg/kubectl/root.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#147 HNC: hardcoded value for resource is replaced by constant
  incubator/hnc/api/v1alpha1/hierarchy_types.go
  incubator/hnc/pkg/kubectl/root.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#150 Obey generic CLI flags
  incubator/hnc/go.mod
  incubator/hnc/go.sum
  incubator/hnc/pkg/kubectl/root.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#151 [incubator][vc] fix dockerfile after using go module
  incubator/virtualcluster/Dockerfile
Labels: approved, cncf-cla: yes, lgtm, size/S

#152 Add set command
  incubator/hnc/pkg/kubectl/root.go
  incubator/hnc/pkg/kubectl/set.go
  incubator/hnc/pkg/kubectl/setparent.go
  incubator/hnc/pkg/kubectl/sub.go
  incubator/hnc/pkg/kubectl/unsetparent.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#143 Clean up CritAncestor tests with hasCondition()
  incubator/hnc/pkg/controllers/hierarchy_controller_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#154 [incubator][vc] add script to build docker image for each component
  incubator/virtualcluster/.gitignore
  incubator/virtualcluster/Makefile
  incubator/virtualcluster/hack/lib/build.sh
  incubator/virtualcluster/hack/lib/docker-image.sh
  incubator/virtualcluster/hack/lib/init.sh
  incubator/virtualcluster/hack/lib/util.sh
  incubator/virtualcluster/hack/make-rules/build.sh
  incubator/virtualcluster/hack/make-rules/release-images.sh
Labels: approved, cncf-cla: yes, lgtm, size/L

#153 implement the functionality for constructing the PKI for virtual cluster
  incubator/virtualcluster/config/crds/tenancy_v1alpha1_clusterversion.yaml
  incubator/virtualcluster/config/crds/tenancy_v1alpha1_virtualcluster.yaml
  incubator/virtualcluster/config/rbac/auth_proxy_service.yaml
  incubator/virtualcluster/config/rbac/rbac_role.yaml
  incubator/virtualcluster/config/sampleswithspec/clusterversion_v1.yaml
  incubator/virtualcluster/config/sampleswithspec/virtualcluster.yaml
  incubator/virtualcluster/go.mod
  incubator/virtualcluster/go.sum
  incubator/virtualcluster/hack/remove-vc
  incubator/virtualcluster/pkg/apis/tenancy/v1alpha1/clusterversion.go
  incubator/virtualcluster/pkg/apis/tenancy/v1alpha1/clusterversion_types.go
  incubator/virtualcluster/pkg/apis/tenancy/v1alpha1/virtualcluster_types.go
  incubator/virtualcluster/pkg/controller/clusterversion/clusterversion_controller.go
  incubator/virtualcluster/pkg/controller/kubeconfig/kubeconfig.go
  incubator/virtualcluster/pkg/controller/pki/pki.go
  incubator/virtualcluster/pkg/controller/secret/secret.go
  incubator/virtualcluster/pkg/controller/util/util.go
  incubator/virtualcluster/pkg/controller/virtualcluster/virtualcluster_controller.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#155 Unbreak webhook config
  incubator/hnc/config/webhook/manifests.yaml
  incubator/hnc/pkg/validators/hierarchy.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#159 Minor change from controller-gen update that I missed
  incubator/hnc/api/v1alpha1/zz_generated.deepcopy.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#161 Separate intermediate files from Git files
  incubator/hnc/.gitignore
  incubator/hnc/Makefile
  incubator/hnc/README.md
  incubator/hnc/config/default/kustomization.yaml
  incubator/hnc/config/default/manager_image_patch.yaml
  incubator/hnc/hack/ci-test.sh
  incubator/hnc/kind-deploy
  incubator/hnc/kind-reset
  incubator/hnc/kind-watch
Labels: approved, cncf-cla: yes, lgtm, size/L

#160 Restructure update() to consolidate calls with forest lock
  incubator/hnc/pkg/controllers/object_controller.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#156 Check authz when changing a namespace's parent
  incubator/hnc/pkg/forest/forest.go
  incubator/hnc/pkg/validators/hierarchy.go
  incubator/hnc/pkg/validators/hierarchy_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#163 Remove very verbose log message
  incubator/hnc/pkg/controllers/object_controller.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#166 PSPs aren't namespaced and shouldn't be watched by the HNC
  incubator/hnc/pkg/controllers/object_controller.go
  incubator/hnc/pkg/controllers/setup.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#164 Make HNC easily deployable onto non-Kind clusters
  incubator/hnc/Makefile
  incubator/hnc/README.md
  incubator/hnc/devenv
Labels: approved, cncf-cla: yes, lgtm, size/L

#175 Add link to meeting notes and agenda document
  docs/links.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#168 Change API package import to 'api'
  incubator/hnc/cmd/manager/main.go
  incubator/hnc/pkg/controllers/hierarchy_controller.go
  incubator/hnc/pkg/controllers/hierarchy_controller_test.go
  incubator/hnc/pkg/controllers/object_controller_test.go
  incubator/hnc/pkg/controllers/suite_test.go
  incubator/hnc/pkg/forest/forest.go
  incubator/hnc/pkg/kubectl/root.go
  incubator/hnc/pkg/kubectl/tree.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#170 Include UserInfo.Extra in authz check
  incubator/hnc/pkg/validators/hierarchy.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#169 Improvements to generation and display of conditions
  incubator/hnc/pkg/controllers/hierarchy_controller.go
  incubator/hnc/pkg/kubectl/show.go
  incubator/hnc/pkg/kubectl/tree.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#174 Add --optionalChild flag and assorted changes to kubectl-hnc-set
  incubator/hnc/pkg/kubectl/root.go
  incubator/hnc/pkg/kubectl/set.go
  incubator/hnc/pkg/kubectl/show.go
  incubator/hnc/pkg/kubectl/tree.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#171 Better comparison of propagated objects
  incubator/hnc/pkg/controllers/object_controller.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#176 Fix inheritedFrom label to point to the orginal namespace
  incubator/hnc/pkg/controllers/object_controller.go
  incubator/hnc/pkg/controllers/object_controller_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#178 Code refactoring: move constants declared in `controller` to be in `api`
  incubator/hnc/api/v1alpha1/hierarchy_types.go
  incubator/hnc/pkg/controllers/hierarchy_controller.go
  incubator/hnc/pkg/controllers/hierarchy_controller_test.go
  incubator/hnc/pkg/controllers/object_controller.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#180 Flag added to show tree of all namespaces
  incubator/hnc/pkg/kubectl/tree.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#179 Enable multithreading in the HC controller
  incubator/hnc/cmd/manager/main.go
  incubator/hnc/config/default/manager_auth_proxy_patch.yaml
  incubator/hnc/config/manager/manager.yaml
  incubator/hnc/pkg/controllers/hierarchy_controller.go
  incubator/hnc/pkg/controllers/setup.go
  incubator/hnc/pkg/controllers/suite_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#182 the first test-version of vc
  incubator/virtualcluster/config/sampleswithspec/clusterversion_v1.yaml
  incubator/virtualcluster/go.mod
  incubator/virtualcluster/go.sum
  incubator/virtualcluster/hack/remove-vc
  incubator/virtualcluster/pkg/apis/tenancy/v1alpha1/clusterversion.go
  incubator/virtualcluster/pkg/controller/pki/pki.go
  incubator/virtualcluster/pkg/controller/secret/secret.go
  incubator/virtualcluster/pkg/controller/util/util.go
  incubator/virtualcluster/pkg/controller/virtualcluster/virtualcluster_controller.go
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/XL

#124 [incubator][vc] add resource syncer implementation
  incubator/virtualcluster/cmd/syncer/app/config/config.go
  incubator/virtualcluster/cmd/syncer/app/options/options.go
  incubator/virtualcluster/cmd/syncer/app/server.go
  incubator/virtualcluster/pkg/syncer/cluster/cluster.go
  incubator/virtualcluster/pkg/syncer/controller/controller.go
  incubator/virtualcluster/pkg/syncer/controllers/configmap/controller.go
  incubator/virtualcluster/pkg/syncer/controllers/namespace/controller.go
  incubator/virtualcluster/pkg/syncer/controllers/pod/controller.go
  incubator/virtualcluster/pkg/syncer/controllers/register.go
  incubator/virtualcluster/pkg/syncer/controllers/secret/controller.go
  incubator/virtualcluster/pkg/syncer/conversion/helper.go
  incubator/virtualcluster/pkg/syncer/handler/enqueue_object.go
  incubator/virtualcluster/pkg/syncer/handler/types.go
  incubator/virtualcluster/pkg/syncer/listener/listener.go
  incubator/virtualcluster/pkg/syncer/manager/manager.go
  incubator/virtualcluster/pkg/syncer/reconciler/reconciler.go
  incubator/virtualcluster/pkg/syncer/syncer.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#184 Validator reject illegal namespace names
  incubator/hnc/pkg/validators/hierarchy.go
  incubator/hnc/pkg/validators/hierarchy_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#190 Remove object modified annotation and fix flaky tests
  incubator/hnc/pkg/controllers/object_controller.go
  incubator/hnc/pkg/controllers/object_controller_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#187 HNC: Added Client Interface to support test cases for kubectl commands
  incubator/hnc/pkg/kubectl/root.go
  incubator/hnc/pkg/kubectl/set.go
  incubator/hnc/pkg/kubectl/show.go
  incubator/hnc/pkg/kubectl/tree.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#191 fix golint error
  incubator/hnc/pkg/forest/forest.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#193 remove label when hierarchy changes
  incubator/hnc/pkg/controllers/hierarchy_controller.go
  incubator/hnc/pkg/controllers/hierarchy_controller_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#194 go lint errors
  incubator/hnc/pkg/controllers/hierarchy_controller.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#199 Fix project path
  tenant/Makefile
  tenant/cmd/manager/main.go
  tenant/pkg/apis/addtoscheme_tenancy_v1alpha1.go
  tenant/pkg/apis/tenancy/v1alpha1/doc.go
  tenant/pkg/apis/tenancy/v1alpha1/register.go
  tenant/pkg/controller/add_tenant.go
  tenant/pkg/controller/add_tenantnamespace.go
  tenant/pkg/controller/tenant/tenant_controller.go
  tenant/pkg/controller/tenant/tenant_controller_suite_test.go
  tenant/pkg/controller/tenant/tenant_controller_test.go
  tenant/pkg/controller/tenantnamespace/tenantnamespace_controller.go
  tenant/pkg/controller/tenantnamespace/tenantnamespace_controller_suite_test.go
  tenant/pkg/controller/tenantnamespace/tenantnamespace_controller_test.go
  tenant/pkg/controller/tenantnamespace/tenantnamespace_event_handler.go
  tenant/pkg/util/tenant_utils.go
  tenant/pkg/webhook/add_default_server.go
  tenant/pkg/webhook/default_server/add_validating_tenant.go
  tenant/pkg/webhook/default_server/add_validating_tenantnamespace.go
  tenant/pkg/webhook/default_server/tenant/validating/create_update_webhook.go
  tenant/pkg/webhook/default_server/tenant/validating/tenant_create_update_handler.go
  tenant/pkg/webhook/default_server/tenantnamespace/validating/create_update_webhook.go
  tenant/pkg/webhook/default_server/tenantnamespace/validating/tenantnamespace_create_update_handler.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#181 Prevent users from applying the inheritedFrom label
  incubator/hnc/cmd/manager/main.go
  incubator/hnc/pkg/config/gvk.go
  incubator/hnc/pkg/controllers/setup.go
  incubator/hnc/pkg/validators/hierarchy.go
  incubator/hnc/pkg/validators/object.go
  incubator/hnc/pkg/validators/object_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#198 HNC: Code refactoring to make set command function testable
  incubator/hnc/pkg/kubectl/set.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#204 use sed instead of tac
  incubator/virtualcluster/Makefile
  incubator/virtualcluster/hack/lib/util.sh
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/XS

#205 replace the old import path
  incubator/virtualcluster/Dockerfile
  incubator/virtualcluster/PROJECT
  incubator/virtualcluster/cmd/manager/main.go
  incubator/virtualcluster/cmd/vcctl/subcmd/create.go
  incubator/virtualcluster/cmd/vcctl/subcmd/delete.go
  incubator/virtualcluster/cmd/vcctl/vcctl.go
  incubator/virtualcluster/go.mod
  incubator/virtualcluster/pkg/apis/addtoscheme_tenancy_v1alpha1.go
  incubator/virtualcluster/pkg/apis/tenancy/v1alpha1/doc.go
  incubator/virtualcluster/pkg/apis/tenancy/v1alpha1/register.go
  incubator/virtualcluster/pkg/controller/add_clusterversion.go
  incubator/virtualcluster/pkg/controller/add_virtualcluster.go
  incubator/virtualcluster/pkg/controller/clusterversion/clusterversion_controller.go
  incubator/virtualcluster/pkg/controller/clusterversion/clusterversion_controller_suite_test.go
  incubator/virtualcluster/pkg/controller/clusterversion/clusterversion_controller_test.go
  incubator/virtualcluster/pkg/controller/kubeconfig/kubeconfig.go
  incubator/virtualcluster/pkg/controller/pki/pki.go
  incubator/virtualcluster/pkg/controller/secret/secret.go
  incubator/virtualcluster/pkg/controller/virtualcluster/virtualcluster_controller.go
  incubator/virtualcluster/pkg/controller/virtualcluster/virtualcluster_controller_suite_test.go
  incubator/virtualcluster/pkg/controller/virtualcluster/virtualcluster_controller_test.go
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/M

#206 [VC] Fix project path
  incubator/virtualcluster/cmd/syncer/app/config/config.go
  incubator/virtualcluster/cmd/syncer/app/options/options.go
  incubator/virtualcluster/cmd/syncer/app/server.go
  incubator/virtualcluster/cmd/syncer/main.go
  incubator/virtualcluster/cmd/vn-agent/main.go
  incubator/virtualcluster/go.mod
  incubator/virtualcluster/hack/lib/build.sh
  incubator/virtualcluster/pkg/apis/tenancy/v1alpha1/zz_generated.deepcopy.go
  incubator/virtualcluster/pkg/client/clientset/versioned/clientset.go
  incubator/virtualcluster/pkg/client/clientset/versioned/fake/clientset_generated.go
  incubator/virtualcluster/pkg/client/clientset/versioned/fake/register.go
  incubator/virtualcluster/pkg/client/clientset/versioned/scheme/register.go
  incubator/virtualcluster/pkg/client/clientset/versioned/typed/tenancy/v1alpha1/fake/fake_tenancy_client.go
  incubator/virtualcluster/pkg/client/clientset/versioned/typed/tenancy/v1alpha1/fake/fake_virtualcluster.go
  incubator/virtualcluster/pkg/client/clientset/versioned/typed/tenancy/v1alpha1/tenancy_client.go
  incubator/virtualcluster/pkg/client/clientset/versioned/typed/tenancy/v1alpha1/virtualcluster.go
  incubator/virtualcluster/pkg/client/informers/externalversions/factory.go
  incubator/virtualcluster/pkg/client/informers/externalversions/generic.go
  incubator/virtualcluster/pkg/client/informers/externalversions/internalinterfaces/factory_interfaces.go
  incubator/virtualcluster/pkg/client/informers/externalversions/tenancy/interface.go
  incubator/virtualcluster/pkg/client/informers/externalversions/tenancy/v1alpha1/interface.go
  incubator/virtualcluster/pkg/client/informers/externalversions/tenancy/v1alpha1/virtualcluster.go
  incubator/virtualcluster/pkg/client/listers/tenancy/v1alpha1/virtualcluster.go
  incubator/virtualcluster/pkg/syncer/cluster/cluster.go
  incubator/virtualcluster/pkg/syncer/controller/controller.go
  incubator/virtualcluster/pkg/syncer/controllers/configmap/controller.go
  incubator/virtualcluster/pkg/syncer/controllers/namespace/controller.go
  incubator/virtualcluster/pkg/syncer/controllers/pod/controller.go
  incubator/virtualcluster/pkg/syncer/controllers/register.go
  incubator/virtualcluster/pkg/syncer/controllers/secret/controller.go
  incubator/virtualcluster/pkg/syncer/handler/enqueue_object.go
  incubator/virtualcluster/pkg/syncer/listener/listener.go
  incubator/virtualcluster/pkg/syncer/syncer.go
  incubator/virtualcluster/pkg/vn-agent/certificate/cert.go
  incubator/virtualcluster/pkg/vn-agent/server/server.go
  incubator/virtualcluster/pkg/vn-agent/server/server_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#208 Fix object webhook configuration
  incubator/hnc/config/webhook/manifests.yaml
  incubator/hnc/pkg/validators/object.go
Labels: approved, cncf-cla: yes, lgtm, size/L
