Repository kubernetes-sigs/multi-tenancy, pull requests merged in 2020-01, with the labels that each got.

#337 [vc] fix resource syncer build issue
  incubator/virtualcluster/go.mod
  incubator/virtualcluster/pkg/syncer/controllers/event/controller.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#338 fix klog not enough input args error
  incubator/virtualcluster/pkg/syncer/controllers/pod/checker.go
  incubator/virtualcluster/pkg/syncer/conversion/helper.go
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/XS

#339 [Incubator][VC] Rename syncer/controllers to syncer/resources
  incubator/virtualcluster/pkg/syncer/resources/configmap/controller.go
  incubator/virtualcluster/pkg/syncer/resources/endpoints/controller.go
  incubator/virtualcluster/pkg/syncer/resources/event/controller.go
  incubator/virtualcluster/pkg/syncer/resources/event/uws.go
  incubator/virtualcluster/pkg/syncer/resources/namespace/controller.go
  incubator/virtualcluster/pkg/syncer/resources/node/controller.go
  incubator/virtualcluster/pkg/syncer/resources/node/node.go
  incubator/virtualcluster/pkg/syncer/resources/node/uws.go
  incubator/virtualcluster/pkg/syncer/resources/pod/checker.go
  incubator/virtualcluster/pkg/syncer/resources/pod/controller.go
  incubator/virtualcluster/pkg/syncer/resources/pod/uws.go
  incubator/virtualcluster/pkg/syncer/resources/register.go
  incubator/virtualcluster/pkg/syncer/resources/secret/controller.go
  incubator/virtualcluster/pkg/syncer/resources/service/controller.go
  incubator/virtualcluster/pkg/syncer/resources/serviceaccount/controller.go
  incubator/virtualcluster/pkg/syncer/syncer.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#340 [Incubator][VC] Clean up - Refactor resource controller - Part 1
  incubator/virtualcluster/go.mod
  incubator/virtualcluster/pkg/syncer/resources/configmap/controller.go
  incubator/virtualcluster/pkg/syncer/resources/configmap/dws.go
  incubator/virtualcluster/pkg/syncer/resources/endpoints/controller.go
  incubator/virtualcluster/pkg/syncer/resources/endpoints/dws.go
  incubator/virtualcluster/pkg/syncer/resources/event/controller.go
  incubator/virtualcluster/pkg/syncer/resources/namespace/controller.go
  incubator/virtualcluster/pkg/syncer/resources/namespace/dws.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#342 [Incubator][VC]Clean up - Refactor resource controller - Part 2
  incubator/virtualcluster/pkg/syncer/resources/node/controller.go
  incubator/virtualcluster/pkg/syncer/resources/node/dws.go
  incubator/virtualcluster/pkg/syncer/resources/node/util.go
  incubator/virtualcluster/pkg/syncer/resources/pod/controller.go
  incubator/virtualcluster/pkg/syncer/resources/pod/dws.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#343 Allow user to choose different underlying platforms to provision tenant master
  incubator/virtualcluster/cmd/manager/main.go
  incubator/virtualcluster/pkg/controller/clusterversion/clusterversion_controller.go
  incubator/virtualcluster/pkg/controller/controller.go
  incubator/virtualcluster/pkg/controller/virtualcluster/master_provisioner.go
  incubator/virtualcluster/pkg/controller/virtualcluster/master_provisioner_aliyun.go
  incubator/virtualcluster/pkg/controller/virtualcluster/master_provisioner_native.go
  incubator/virtualcluster/pkg/controller/virtualcluster/virtualcluster_controller.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XL

#345 [Incubator][VC]Clean up - Refactor resource controller - Part 3
  incubator/virtualcluster/pkg/controller/virtualcluster/virtualcluster_controller_test.go
  incubator/virtualcluster/pkg/syncer/resources/secret/controller.go
  incubator/virtualcluster/pkg/syncer/resources/secret/dws.go
  incubator/virtualcluster/pkg/syncer/resources/serviceaccount/controller.go
  incubator/virtualcluster/pkg/syncer/resources/serviceaccount/dws.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#341 [incubator][VC] support tenant aware dns server
  incubator/virtualcluster/pkg/syncer/cluster/cluster.go
  incubator/virtualcluster/pkg/syncer/constants/constants.go
  incubator/virtualcluster/pkg/syncer/conversion/helper.go
  incubator/virtualcluster/pkg/syncer/conversion/mutate.go
  incubator/virtualcluster/pkg/syncer/mccontroller/mccontroller.go
  incubator/virtualcluster/pkg/syncer/resources/pod/dws.go
  incubator/virtualcluster/pkg/syncer/resources/service/controller.go
  incubator/virtualcluster/pkg/syncer/syncer.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#336 [MTB] Complete multi-tenancy profile level 1 benchmarks
  benchmarks/README.md
  benchmarks/documentation/definitions.md
  benchmarks/e2e/tests/block_add_capabilities/README.md
  benchmarks/e2e/tests/block_bind_mounts/README.md
  benchmarks/e2e/tests/block_cluster_resources/README.md
  benchmarks/e2e/tests/block_host_ipc/README.md
  benchmarks/e2e/tests/block_host_net_ports/README.md
  benchmarks/e2e/tests/block_host_pid/README.md
  benchmarks/e2e/tests/block_multitenant_resources/README.md
  benchmarks/e2e/tests/block_nodeports/README.md
  benchmarks/e2e/tests/block_ns_quotas/README.md
  benchmarks/e2e/tests/block_other_tenant_resources/README.md
  benchmarks/e2e/tests/block_privilege_escalation/README.md
  benchmarks/e2e/tests/block_privileged_containers/README.md
  benchmarks/e2e/tests/configure_ns_quotas/README.md
  benchmarks/e2e/tests/default_deny_net_conn/README.md
  benchmarks/e2e/tests/require_run_as_non_root/README.md
Labels: approved, cncf-cla: yes, lgtm, size/L

#346 implement aliyun mode for vc-manager
  incubator/virtualcluster/config/rbac/rbac_role.yaml
  incubator/virtualcluster/config/setup/all_in_one_aliyun.yaml
  incubator/virtualcluster/go.mod
  incubator/virtualcluster/go.sum
  incubator/virtualcluster/pkg/controller/clusterversion/clusterversion_controller.go
  incubator/virtualcluster/pkg/controller/util/kube/util.go
  incubator/virtualcluster/pkg/controller/util/strings/util.go
  incubator/virtualcluster/pkg/controller/virtualcluster/master_provisioner.go
  incubator/virtualcluster/pkg/controller/virtualcluster/master_provisioner_aliyun.go
  incubator/virtualcluster/pkg/controller/virtualcluster/master_provisioner_native.go
  incubator/virtualcluster/pkg/controller/virtualcluster/virtualcluster_controller.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XL

#348 fix creation timeout bug.
  incubator/virtualcluster/pkg/controller/util/strings/util.go
  incubator/virtualcluster/pkg/controller/virtualcluster/master_provisioner_aliyun.go
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/L

#351 Increase memory limits
  incubator/hnc/config/manager/manager.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#354 [Incubator][VC]Fix cluster cache not ready race
  incubator/virtualcluster/pkg/syncer/cluster/cluster.go
  incubator/virtualcluster/pkg/syncer/mccontroller/mccontroller.go
  incubator/virtualcluster/pkg/syncer/syncer.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#355 [incubator][VC] add ownerReference meta info to super pod meta as annotation
  incubator/virtualcluster/pkg/syncer/constants/constants.go
  incubator/virtualcluster/pkg/syncer/conversion/helper.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#356 [incubator][VC] make tenant dns server optional
  incubator/virtualcluster/pkg/syncer/conversion/mutate.go
  incubator/virtualcluster/pkg/syncer/resources/pod/dws.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#352 [incubator][VC]Add sync controller for StorageClass resource
  incubator/virtualcluster/pkg/syncer/constants/constants.go
  incubator/virtualcluster/pkg/syncer/conversion/equality.go
  incubator/virtualcluster/pkg/syncer/conversion/helper.go
  incubator/virtualcluster/pkg/syncer/resources/register.go
  incubator/virtualcluster/pkg/syncer/resources/storageclass/controller.go
  incubator/virtualcluster/pkg/syncer/resources/storageclass/uws.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#357 [incubator][VC] make virtual node unschedulable to avoid possible scheduler
  incubator/virtualcluster/pkg/syncer/resources/node/util.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#358 [incubator][VC] add extend info (deployment) to vPod
  incubator/virtualcluster/pkg/syncer/constants/constants.go
  incubator/virtualcluster/pkg/syncer/conversion/mutate.go
  incubator/virtualcluster/pkg/syncer/resources/pod/dws.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#359 [incubator][VC] add service resource checker
  incubator/virtualcluster/pkg/syncer/constants/constants.go
  incubator/virtualcluster/pkg/syncer/conversion/equality.go
  incubator/virtualcluster/pkg/syncer/conversion/helper.go
  incubator/virtualcluster/pkg/syncer/conversion/mutate.go
  incubator/virtualcluster/pkg/syncer/manager/manager.go
  incubator/virtualcluster/pkg/syncer/resources/configmap/controller.go
  incubator/virtualcluster/pkg/syncer/resources/endpoints/controller.go
  incubator/virtualcluster/pkg/syncer/resources/event/controller.go
  incubator/virtualcluster/pkg/syncer/resources/namespace/controller.go
  incubator/virtualcluster/pkg/syncer/resources/node/controller.go
  incubator/virtualcluster/pkg/syncer/resources/pod/checker.go
  incubator/virtualcluster/pkg/syncer/resources/secret/controller.go
  incubator/virtualcluster/pkg/syncer/resources/service/checker.go
  incubator/virtualcluster/pkg/syncer/resources/service/controller.go
  incubator/virtualcluster/pkg/syncer/resources/serviceaccount/controller.go
  incubator/virtualcluster/pkg/syncer/resources/storageclass/controller.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#360 User DelegatingCache for tenant apiserver read and save clientset client pointer
  incubator/virtualcluster/pkg/syncer/cluster/cluster.go
  incubator/virtualcluster/pkg/syncer/mccontroller/mccontroller.go
  incubator/virtualcluster/pkg/syncer/resources/node/uws.go
  incubator/virtualcluster/pkg/syncer/resources/pod/checker.go
  incubator/virtualcluster/pkg/syncer/resources/pod/controller.go
  incubator/virtualcluster/pkg/syncer/resources/pod/dws.go
  incubator/virtualcluster/pkg/syncer/resources/pod/uws.go
  incubator/virtualcluster/pkg/syncer/resources/storageclass/uws.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#361 [Incubator][VC]Refactor Cluster and MultiClusterController interface methods
  incubator/virtualcluster/pkg/syncer/cluster/cluster.go
  incubator/virtualcluster/pkg/syncer/conversion/mutate.go
  incubator/virtualcluster/pkg/syncer/mccontroller/mccontroller.go
  incubator/virtualcluster/pkg/syncer/resources/event/uws.go
  incubator/virtualcluster/pkg/syncer/resources/node/util.go
  incubator/virtualcluster/pkg/syncer/resources/node/uws.go
  incubator/virtualcluster/pkg/syncer/resources/pod/checker.go
  incubator/virtualcluster/pkg/syncer/resources/pod/dws.go
  incubator/virtualcluster/pkg/syncer/resources/pod/uws.go
  incubator/virtualcluster/pkg/syncer/resources/service/checker.go
  incubator/virtualcluster/pkg/syncer/resources/service/controller.go
  incubator/virtualcluster/pkg/syncer/resources/storageclass/uws.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#364 [Incubator][VC]Do not sync tenant Pod with NodeName set in the spec
  incubator/virtualcluster/pkg/syncer/resources/pod/checker.go
  incubator/virtualcluster/pkg/syncer/resources/pod/dws.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#362 [Incubator][VC]Increase node status monitor grace period
  incubator/virtualcluster/config/sampleswithspec/clusterversion_v1_loadbalancer.yaml
  incubator/virtualcluster/config/sampleswithspec/clusterversion_v1_nodeport.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#363 [Incubator][VC] Add storageclass object periodic checker
  incubator/virtualcluster/pkg/syncer/resources/service/checker.go
  incubator/virtualcluster/pkg/syncer/resources/storageclass/checker.go
  incubator/virtualcluster/pkg/syncer/resources/storageclass/controller.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#365 fix the master service namespace bug
  incubator/virtualcluster/pkg/syncer/conversion/mutate.go
  incubator/virtualcluster/pkg/syncer/resources/service/controller.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#366 [Incubator][VC]Refactor Node syncer
  incubator/virtualcluster/pkg/syncer/constants/constants.go
  incubator/virtualcluster/pkg/syncer/resources/node/controller.go
  incubator/virtualcluster/pkg/syncer/resources/node/dws.go
  incubator/virtualcluster/pkg/syncer/resources/node/util.go
  incubator/virtualcluster/pkg/syncer/resources/node/uws.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#367 [incubator][VC] provide kubeconfig according to service account
  incubator/virtualcluster/cmd/syncer/app/options/options.go
  incubator/virtualcluster/cmd/syncer/app/server.go
  incubator/virtualcluster/config/sampleswithspec/example_foo.yaml
  incubator/virtualcluster/config/setup/sample_foo_controller.yaml
  incubator/virtualcluster/pkg/syncer/apis/config/types.go
  incubator/virtualcluster/pkg/syncer/cluster/cluster.go
  incubator/virtualcluster/pkg/syncer/conversion/helper.go
  incubator/virtualcluster/pkg/syncer/conversion/mutate.go
  incubator/virtualcluster/pkg/syncer/mccontroller/mccontroller.go
  incubator/virtualcluster/pkg/syncer/resources/configmap/controller.go
  incubator/virtualcluster/pkg/syncer/resources/endpoints/controller.go
  incubator/virtualcluster/pkg/syncer/resources/event/controller.go
  incubator/virtualcluster/pkg/syncer/resources/namespace/controller.go
  incubator/virtualcluster/pkg/syncer/resources/node/controller.go
  incubator/virtualcluster/pkg/syncer/resources/pod/controller.go
  incubator/virtualcluster/pkg/syncer/resources/pod/dws.go
  incubator/virtualcluster/pkg/syncer/resources/register.go
  incubator/virtualcluster/pkg/syncer/resources/secret/controller.go
  incubator/virtualcluster/pkg/syncer/resources/service/controller.go
  incubator/virtualcluster/pkg/syncer/resources/serviceaccount/controller.go
  incubator/virtualcluster/pkg/syncer/resources/storageclass/controller.go
  incubator/virtualcluster/pkg/syncer/syncer.go
  incubator/virtualcluster/pkg/syncer/utils/string.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#371 Update README comments for HNC
  incubator/hnc/README.md
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/XS
