Repository kubernetes-sigs/multi-tenancy, pull requests merged in 2020-09, with the labels that each got.

#1069 Corrected policy file
  benchmarks/kubectl-mtb/.gitignore
  benchmarks/kubectl-mtb/test/benchmarks/block_add_capabilities/block_add_capabilities.go
  benchmarks/kubectl-mtb/test/benchmarks/block_privilege_escalation/block_privilege_escalation.go
  benchmarks/kubectl-mtb/test/benchmarks/block_privileged_containers/block_privileged_containers.go
  benchmarks/kubectl-mtb/test/benchmarks/block_use_of_bind_mounts/block_use_of_bind_mounts.go
  benchmarks/kubectl-mtb/test/benchmarks/block_use_of_host_ipc/block_use_of_host_ipc.go
  benchmarks/kubectl-mtb/test/benchmarks/block_use_of_host_networking_and_ports/block_use_of_host_networking_and_ports.go
  benchmarks/kubectl-mtb/test/benchmarks/block_use_of_host_pid/block_use_of_host_pid.go
  benchmarks/kubectl-mtb/test/policies/kyverno/all_policies.yaml
  benchmarks/kubectl-mtb/test/utils/resources/pod/pod.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1071 Network policy bug fix
  benchmarks/kubectl-mtb/test/benchmarks/create_network_policies/create_network_policies.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1072 [MTB] Fixed links
  benchmarks/kubectl-mtb/README.md
  benchmarks/kubectl-mtb/test/quotas/ns_quota.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1075 Feature/Improve CLI and docs
  benchmarks/kubectl-mtb/README.md
  benchmarks/kubectl-mtb/internal/kubectl-mtb/get.go
  benchmarks/kubectl-mtb/internal/kubectl-mtb/root.go
  benchmarks/kubectl-mtb/internal/kubectl-mtb/run.go
  benchmarks/kubectl-mtb/internal/kubectl-mtb/util.go
  benchmarks/kubectl-mtb/internal/reporter/default_reporter.go
  benchmarks/kubectl-mtb/internal/reporter/policy_reporter.go
  benchmarks/kubectl-mtb/internal/reporter/types.go
  benchmarks/kubectl-mtb/pkg/benchmark_suite/benchmarks_suite.go
  benchmarks/kubectl-mtb/test/benchmarks/block_add_capabilities/block_add_capabilities.go
  benchmarks/kubectl-mtb/test/benchmarks/block_use_of_host_path/README.md
  benchmarks/kubectl-mtb/test/benchmarks/block_use_of_host_path/block_use_of_host_path.go
  benchmarks/kubectl-mtb/test/benchmarks/block_use_of_host_path/block_use_of_host_path_test.go
  benchmarks/kubectl-mtb/test/benchmarks/block_use_of_host_path/config.yaml
  benchmarks/kubectl-mtb/test/policies/kyverno/all_policies.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#1068 Fix some flaky testes
  incubator/hnc/test/e2e/delete_crd_test.go
  incubator/hnc/test/e2e/demo_test.go
  incubator/hnc/test/e2e/e2e_test.go
  incubator/hnc/test/e2e/issues_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1078 fix typo `hns` -> `subns`
  incubator/hnc/docs/user-guide/how-to.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#1081 [VC] Add kubecon talk to README.md
  incubator/virtualcluster/README.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#1055 changed logger initiator
  benchmarks/kubectl-mtb/.gitignore
  benchmarks/kubectl-mtb/Makefile
  benchmarks/kubectl-mtb/go.sum
  benchmarks/kubectl-mtb/internal/kubectl-mtb/run.go
  benchmarks/kubectl-mtb/test/benchmarks/block_access_to_cluster_resources/block_access_to_cluster_resources.go
  benchmarks/kubectl-mtb/test/benchmarks/block_add_capabilities/block_add_capabilities.go
  benchmarks/kubectl-mtb/test/benchmarks/block_add_capabilities/block_add_capabilities_test.go
  benchmarks/kubectl-mtb/test/benchmarks/block_ns_quota/block_ns_quota.go
  benchmarks/kubectl-mtb/test/benchmarks/block_privilege_escalation/block_privilege_escalation.go
  benchmarks/kubectl-mtb/test/benchmarks/block_privilege_escalation/block_privilege_escalation_test.go
  benchmarks/kubectl-mtb/test/benchmarks/block_privileged_containers/block_privileged_containers.go
  benchmarks/kubectl-mtb/test/benchmarks/block_privileged_containers/block_privileged_containers_test.go
  benchmarks/kubectl-mtb/test/benchmarks/block_use_of_host_ipc/block_use_of_host_ipc.go
  benchmarks/kubectl-mtb/test/benchmarks/block_use_of_host_ipc/block_use_of_host_ipc_test.go
  benchmarks/kubectl-mtb/test/benchmarks/block_use_of_host_networking_and_ports/block_use_of_host_networking_and_ports.go
  benchmarks/kubectl-mtb/test/benchmarks/block_use_of_host_networking_and_ports/block_use_of_host_networking_and_ports_test.go
  benchmarks/kubectl-mtb/test/benchmarks/block_use_of_host_path/block_use_of_host_path.go
  benchmarks/kubectl-mtb/test/benchmarks/block_use_of_host_path/block_use_of_host_path_test.go
  benchmarks/kubectl-mtb/test/benchmarks/block_use_of_host_pid/block_use_of_host_pid.go
  benchmarks/kubectl-mtb/test/benchmarks/block_use_of_host_pid/block_use_of_host_pid_test.go
  benchmarks/kubectl-mtb/test/benchmarks/block_use_of_nodeport_services/block_use_of_nodeport_services.go
  benchmarks/kubectl-mtb/test/benchmarks/block_use_of_nodeport_services/block_use_of_nodeport_services_test.go
  benchmarks/kubectl-mtb/test/benchmarks/configure_ns_object_quota/configure_ns_object_quota.go
  benchmarks/kubectl-mtb/test/benchmarks/configure_ns_quotas/configure_ns_quotas.go
  benchmarks/kubectl-mtb/test/benchmarks/create_network_policies/create_network_policies.go
  benchmarks/kubectl-mtb/test/benchmarks/require_run_as_non_root_user/require_run_as_non_root_user.go
  benchmarks/kubectl-mtb/test/benchmarks/require_run_as_non_root_user/require_run_as_non_root_user_test.go
  benchmarks/kubectl-mtb/test/policies/kyverno/all_policies.yaml
  benchmarks/kubectl-mtb/test/utils/log/log.go
  benchmarks/kubectl-mtb/types/types.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1083 fix broken link for VirtualCluster
  incubator/virtualcluster/README.md
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/XS

#1082 add rest config into SyncerConfiguration
  incubator/virtualcluster/cmd/syncer/app/options/options.go
  incubator/virtualcluster/pkg/syncer/apis/config/types.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#1077 Update object reconciler to overwrite conflicting source
  incubator/hnc/internal/reconcilers/object.go
  incubator/hnc/internal/reconcilers/object_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1065 Add KUBERNETES_SERVICE_HOST env variable to synced pods
  incubator/virtualcluster/pkg/syncer/conversion/mutate.go
  incubator/virtualcluster/pkg/syncer/resources/pod/dws_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#1087 Move webhook setup before manager start
  incubator/hnc/cmd/manager/main.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1088 Fix a flaky test for Prow specifically
  incubator/hnc/internal/reconcilers/object_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1086 Remove resource creation time rest.
  incubator/virtualcluster/pkg/syncer/conversion/helper.go
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/XS

#1093 Upgrade controller-tools to enable unservedversion
  incubator/hnc/go.mod
  incubator/hnc/go.sum
  incubator/hnc/vendor/modules.txt
  incubator/hnc/vendor/sigs.k8s.io/controller-tools/pkg/crd/conv.go
  incubator/hnc/vendor/sigs.k8s.io/controller-tools/pkg/crd/gen.go
  incubator/hnc/vendor/sigs.k8s.io/controller-tools/pkg/crd/markers/crd.go
  incubator/hnc/vendor/sigs.k8s.io/controller-tools/pkg/crd/markers/zz_generated.markerhelp.go
  incubator/hnc/vendor/sigs.k8s.io/controller-tools/pkg/crd/spec.go
  incubator/hnc/vendor/sigs.k8s.io/controller-tools/pkg/genall/options.go
  incubator/hnc/vendor/sigs.k8s.io/controller-tools/pkg/markers/parse.go
  incubator/hnc/vendor/sigs.k8s.io/controller-tools/pkg/rbac/parser.go
  incubator/hnc/vendor/sigs.k8s.io/controller-tools/pkg/rbac/zz_generated.markerhelp.go
  incubator/hnc/vendor/sigs.k8s.io/controller-tools/pkg/schemapatcher/gen.go
  incubator/hnc/vendor/sigs.k8s.io/controller-tools/pkg/schemapatcher/internal/yaml/convert.go
  incubator/hnc/vendor/sigs.k8s.io/controller-tools/pkg/schemapatcher/internal/yaml/nested.go
  incubator/hnc/vendor/sigs.k8s.io/controller-tools/pkg/webhook/parser.go
  incubator/hnc/vendor/sigs.k8s.io/controller-tools/pkg/webhook/zz_generated.markerhelp.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1085 Update object webhook to deny creating conflict object
  incubator/hnc/internal/validators/object.go
  incubator/hnc/internal/validators/object_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1095 Fix make target kind-deploy for KIND environment
  incubator/hnc/Makefile
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#1099 VC: Use optional env var for Docker registry in Makefile
  incubator/virtualcluster/Makefile
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/XS

#1091 Fix the Rolebinding update logic
  incubator/hnc/internal/reconcilers/object.go
  incubator/hnc/test/e2e/rolebinding_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1097 Update dev instructions
  incubator/hnc/README.md
  incubator/hnc/devenv
Labels: approved, cncf-cla: yes, lgtm, size/L

#1089 [MTB] added 3 unit tests
  benchmarks/kubectl-mtb/test/benchmarks/block_access_to_cluster_resources/block_access_to_cluster_resources_test.go
  benchmarks/kubectl-mtb/test/benchmarks/block_ns_quota/block_ns_quota_test.go
  benchmarks/kubectl-mtb/test/benchmarks/create_network_policies/create_network_policies_test.go
  benchmarks/kubectl-mtb/test/utils/unittestutils/client.go
  benchmarks/kubectl-mtb/test/utils/unittestutils/rbac_create.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#1101 Add test for propagating object to selected namespaces
  incubator/hnc/internal/reconcilers/object_test.go
  incubator/hnc/internal/reconcilers/test_helpers_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1105 update benchmark documentation for kubectl-mtb
  benchmarks/README.md
  benchmarks/documentation/contributing.md
  benchmarks/documentation/definitions.md
  benchmarks/documentation/run.md
  benchmarks/e2e/config/config.go
  benchmarks/e2e/config/utils.go
  benchmarks/e2e/tests/block_add_capabilities/README.md
  benchmarks/e2e/tests/block_add_capabilities/block_add_capabilities.go
  benchmarks/e2e/tests/block_bind_mounts/README.md
  benchmarks/e2e/tests/block_bind_mounts/block_bind_mounts.go
  benchmarks/e2e/tests/block_cluster_resources/README.md
  benchmarks/e2e/tests/block_cluster_resources/block_cluster_resources.go
  benchmarks/e2e/tests/block_host_ipc/README.md
  benchmarks/e2e/tests/block_host_ipc/block_host_ipc.go
  benchmarks/e2e/tests/block_host_net_ports/README.md
  benchmarks/e2e/tests/block_host_net_ports/block_host_net_ports.go
  benchmarks/e2e/tests/block_host_pid/README.md
  benchmarks/e2e/tests/block_host_pid/block_host_pid.go
  benchmarks/e2e/tests/block_multitenant_resources/README.md
  benchmarks/e2e/tests/block_multitenant_resources/block_multitenant_resources.go
  benchmarks/e2e/tests/block_nodeports/README.md
  benchmarks/e2e/tests/block_nodeports/block_nodeports.go
  benchmarks/e2e/tests/block_ns_quotas/README.md
  benchmarks/e2e/tests/block_ns_quotas/block_ns_quotas.go
  benchmarks/e2e/tests/block_other_tenant_resources/README.md
  benchmarks/e2e/tests/block_other_tenant_resources/block_other_tenant_resources.go
  benchmarks/e2e/tests/block_privilege_escalation/README.md
  benchmarks/e2e/tests/block_privilege_escalation/block_privilege_escalation.go
  benchmarks/e2e/tests/block_privileged_containers/README.md
  benchmarks/e2e/tests/block_privileged_containers/block_privilege_container.go
  benchmarks/e2e/tests/configure_ns_object_quotas/README.md
  benchmarks/e2e/tests/configure_ns_object_quotas/configure_ns_object_quotas.go
  benchmarks/e2e/tests/configure_ns_quotas/README.md
  benchmarks/e2e/tests/configure_ns_quotas/configure_ns_quotas.go
  benchmarks/e2e/tests/create_network_policies/README.md
  benchmarks/e2e/tests/create_network_policies/create_network_policies.go
  benchmarks/e2e/tests/create_role_bindings/README.md
  benchmarks/e2e/tests/create_role_bindings/create_role_bindings.go
  benchmarks/e2e/tests/create_tenant_crds/README.md
  benchmarks/e2e/tests/default_deny_net_conn/README.md
  benchmarks/e2e/tests/default_deny_net_conn/default_deny_net_conn.go
  benchmarks/e2e/tests/e2e.go
  benchmarks/e2e/tests/e2e_test.go
  benchmarks/e2e/tests/require_run_as_non_root/README.md
  benchmarks/e2e/tests/require_run_as_non_root/require_run_as_non_root.go
  benchmarks/kubectl-mtb/README.md
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#1092 Update hc validator to check object conflicts
  incubator/hnc/internal/forest/namespaceobjects.go
  incubator/hnc/internal/reconcilers/object.go
  incubator/hnc/internal/validators/hierarchy.go
  incubator/hnc/internal/validators/hierarchy_test.go
  incubator/hnc/internal/validators/object.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1121 Fix a nil pointer issue in HC webhook when setting as root
  incubator/hnc/internal/validators/hierarchy.go
  incubator/hnc/internal/validators/hierarchy_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1125 Fix certs in K8s 1.19
  incubator/hnc/third_party/open-policy-agent/gatekeeper/pkg/webhook/certs.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1124 Regenerate CRD yamls
  incubator/hnc/config/crd/bases/hnc.x-k8s.io_hierarchyconfigurations.yaml
  incubator/hnc/config/crd/bases/hnc.x-k8s.io_hncconfigurations.yaml
  incubator/hnc/config/crd/bases/hnc.x-k8s.io_subnamespaceanchors.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#1126 Update to controller-runtime v0.6.3
  incubator/hnc/go.mod
  incubator/hnc/go.sum
  incubator/hnc/test/e2e/rolebinding_test.go
  incubator/hnc/vendor/github.com/evanphx/json-patch/.travis.yml
  incubator/hnc/vendor/github.com/evanphx/json-patch/LICENSE
  incubator/hnc/vendor/github.com/evanphx/json-patch/README.md
  incubator/hnc/vendor/github.com/evanphx/json-patch/merge.go
  incubator/hnc/vendor/github.com/evanphx/json-patch/patch.go
  incubator/hnc/vendor/k8s.io/apimachinery/pkg/apis/meta/v1/types.go
  incubator/hnc/vendor/k8s.io/apimachinery/pkg/util/net/http.go
  incubator/hnc/vendor/k8s.io/client-go/tools/cache/reflector.go
  incubator/hnc/vendor/modules.txt
  incubator/hnc/vendor/sigs.k8s.io/controller-runtime/OWNERS_ALIASES
  incubator/hnc/vendor/sigs.k8s.io/controller-runtime/VERSIONING.md
  incubator/hnc/vendor/sigs.k8s.io/controller-runtime/alias.go
  incubator/hnc/vendor/sigs.k8s.io/controller-runtime/go.mod
  incubator/hnc/vendor/sigs.k8s.io/controller-runtime/go.sum
  incubator/hnc/vendor/sigs.k8s.io/controller-runtime/pkg/builder/controller.go
  incubator/hnc/vendor/sigs.k8s.io/controller-runtime/pkg/controller/controller.go
  incubator/hnc/vendor/sigs.k8s.io/controller-runtime/pkg/envtest/printer/prow.go
  incubator/hnc/vendor/sigs.k8s.io/controller-runtime/pkg/envtest/server.go
  incubator/hnc/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go
  incubator/hnc/vendor/sigs.k8s.io/controller-runtime/pkg/leaderelection/leader_election.go
  incubator/hnc/vendor/sigs.k8s.io/controller-runtime/pkg/log/log.go
  incubator/hnc/vendor/sigs.k8s.io/controller-runtime/pkg/log/zap/flags.go
  incubator/hnc/vendor/sigs.k8s.io/controller-runtime/pkg/log/zap/zap.go
  incubator/hnc/vendor/sigs.k8s.io/controller-runtime/pkg/manager/internal.go
  incubator/hnc/vendor/sigs.k8s.io/controller-runtime/pkg/manager/manager.go
  incubator/hnc/vendor/sigs.k8s.io/controller-runtime/pkg/predicate/predicate.go
  incubator/hnc/vendor/sigs.k8s.io/controller-runtime/pkg/reconcile/reconcile.go
  incubator/hnc/vendor/sigs.k8s.io/controller-runtime/pkg/webhook/admission/http.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#1127 Fix HNC startup issues
  incubator/hnc/cmd/manager/main.go
  incubator/hnc/go.mod
  incubator/hnc/go.sum
  incubator/hnc/vendor/modules.txt
  incubator/hnc/vendor/sigs.k8s.io/controller-runtime/pkg/envtest/webhook.go
  incubator/hnc/vendor/sigs.k8s.io/controller-runtime/pkg/manager/internal.go
  incubator/hnc/vendor/sigs.k8s.io/controller-runtime/pkg/webhook/server.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1139 Let subns with propagated objects be deleted
  incubator/hnc/internal/reconcilers/hierarchy_config.go
  incubator/hnc/test/e2e/issues_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1131 Fix some e2e tests
  incubator/hnc/pkg/testutils/testutils.go
  incubator/hnc/test/e2e/demo_test.go
  incubator/hnc/test/e2e/issues_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#1137 Build Krew archive
  incubator/hnc/cloudbuild.yaml
  incubator/hnc/hack/krew-hierarchical-namespaces.yaml
  incubator/hnc/hack/krew-kubectl-hns.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#1136 Build Krew archive and manifest
  incubator/hnc/Makefile
  incubator/hnc/cloudbuild.yaml
  incubator/hnc/docs/releasing.md
  incubator/hnc/hack/krew-hierarchical-namespaces.yaml
  incubator/hnc/hack/krew-kubectl-hns.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#1141 Let subns with propagated objects be deleted
  incubator/hnc/internal/reconcilers/hierarchy_config.go
  incubator/hnc/test/e2e/issues_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1106 Update hncconfig webhook to handle object overwriting and refactor forest `sourceObjects` field
  incubator/hnc/internal/forest/forest.go
  incubator/hnc/internal/forest/namespace.go
  incubator/hnc/internal/forest/namespaceobjects.go
  incubator/hnc/internal/reconcilers/hnc_config.go
  incubator/hnc/internal/reconcilers/object.go
  incubator/hnc/internal/reconcilers/object_test.go
  incubator/hnc/internal/validators/hierarchy.go
  incubator/hnc/internal/validators/hncconfig.go
  incubator/hnc/internal/validators/hncconfig_test.go
  incubator/hnc/internal/validators/object.go
  incubator/hnc/internal/validators/object_test.go
  incubator/hnc/internal/validators/setup.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1128 Use official cert-controller and support K8s 1.19
  incubator/hnc/Dockerfile
  incubator/hnc/Makefile
  incubator/hnc/go.mod
  incubator/hnc/go.sum
  incubator/hnc/internal/validators/setup.go
  incubator/hnc/third_party/open-policy-agent/gatekeeper/README.md
  incubator/hnc/third_party/open-policy-agent/gatekeeper/pkg/webhook/certs_test.go
  incubator/hnc/vendor/github.com/open-policy-agent/cert-controller/LICENSE
  incubator/hnc/vendor/github.com/open-policy-agent/cert-controller/NOTICE
  incubator/hnc/vendor/github.com/open-policy-agent/cert-controller/pkg/rotator/rotator.go
  incubator/hnc/vendor/github.com/pkg/errors/.travis.yml
  incubator/hnc/vendor/github.com/pkg/errors/Makefile
  incubator/hnc/vendor/github.com/pkg/errors/README.md
  incubator/hnc/vendor/github.com/pkg/errors/errors.go
  incubator/hnc/vendor/github.com/pkg/errors/go113.go
  incubator/hnc/vendor/github.com/pkg/errors/stack.go
  incubator/hnc/vendor/modules.txt
Labels: approved, cncf-cla: yes, lgtm, size/L

#1115 Cherrypick: Handle source object overwriting conflict
  incubator/hnc/internal/forest/namespaceobjects.go
  incubator/hnc/internal/reconcilers/object.go
  incubator/hnc/internal/reconcilers/object_test.go
  incubator/hnc/internal/validators/hierarchy.go
  incubator/hnc/internal/validators/hierarchy_test.go
  incubator/hnc/internal/validators/object.go
  incubator/hnc/internal/validators/object_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1135 VC: implement fair queuing
  incubator/virtualcluster/go.mod
  incubator/virtualcluster/pkg/syncer/fairqueue/balancer/balancer.go
  incubator/virtualcluster/pkg/syncer/fairqueue/balancer/weightedroundrobin/scheduler.go
  incubator/virtualcluster/pkg/syncer/fairqueue/balancer/weightedroundrobin/scheduler_test.go
  incubator/virtualcluster/pkg/syncer/fairqueue/delaying.go
  incubator/virtualcluster/pkg/syncer/fairqueue/fair.go
  incubator/virtualcluster/pkg/syncer/fairqueue/fair_test.go
  incubator/virtualcluster/pkg/syncer/handler/enqueue_object.go
  incubator/virtualcluster/pkg/syncer/handler/enqueue_object_test.go
  incubator/virtualcluster/pkg/syncer/reconciler/reconciler.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#1132 Add gofmt enforcement
  incubator/hnc/Makefile
  incubator/hnc/hack/ci-test.sh
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/S

#1143 Ensure controller-gen is rebuilt properly
  incubator/hnc/Makefile
  incubator/hnc/config/crd/bases/hnc.x-k8s.io_hierarchyconfigurations.yaml
  incubator/hnc/config/crd/bases/hnc.x-k8s.io_hncconfigurations.yaml
  incubator/hnc/config/crd/bases/hnc.x-k8s.io_subnamespaceanchors.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#1147 VC: adding healthz for vc-syncer,vc-manager
  incubator/virtualcluster/cmd/manager/main.go
  incubator/virtualcluster/cmd/syncer/app/server.go
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/S

#1150 Don't delete subns if anchor has conflict
  incubator/hnc/internal/reconcilers/anchor.go
  incubator/hnc/test/e2e/issues_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1152 Fix a very rare flaky test on Prow
  incubator/hnc/internal/reconcilers/object_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1144 Update and add test case for exception
  incubator/hnc/internal/reconcilers/object_test.go
  incubator/hnc/internal/reconcilers/test_helpers_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1074 Set crd:trivialVersions=false and add patch per-version
  incubator/hnc/Makefile
  incubator/hnc/api/v1alpha1/hierarchy_types.go
  incubator/hnc/api/v1alpha1/hnc_config.go
  incubator/hnc/api/v1alpha1/subnamespace_anchor.go
  incubator/hnc/api/v1alpha2/hierarchy_types.go
  incubator/hnc/config/crd/bases/hnc.x-k8s.io_hierarchyconfigurations.yaml
  incubator/hnc/config/crd/bases/hnc.x-k8s.io_hncconfigurations.yaml
  incubator/hnc/config/crd/bases/hnc.x-k8s.io_subnamespaceanchors.yaml
  incubator/hnc/config/crd/kustomization.yaml
  incubator/hnc/config/crd/patches/singleton_validation_hierarchyconfiguration.yaml
  incubator/hnc/config/crd/patches/singleton_validation_hncconfiguration.yaml
  incubator/hnc/config/crd/patches/webhook_in_hierarchyconfigurations.yaml
  incubator/hnc/config/crd/patches/webhook_in_hncconfigurations.yaml
  incubator/hnc/config/crd/patches/webhook_in_subnamespaceanchors.yaml
  incubator/hnc/hack/crd_patches/config_singleton_enum.yaml
  incubator/hnc/hack/crd_patches/ensure-all-served-for-envtest.sh
  incubator/hnc/hack/crd_patches/hierarchy_singleton_enum.yaml
  incubator/hnc/hack/crd_patches/singleton-enum-patch.sh
  incubator/hnc/internal/reconcilers/suite_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#1117 [MTB] Add Kyverno policy - Require always image pull
  benchmarks/README.md
  benchmarks/kubectl-mtb/docs/main.go
  benchmarks/kubectl-mtb/test/benchmarks/block_access_to_cluster_resources/README.md
  benchmarks/kubectl-mtb/test/benchmarks/block_add_capabilities/README.md
  benchmarks/kubectl-mtb/test/benchmarks/block_multitenant_resources/README.md
  benchmarks/kubectl-mtb/test/benchmarks/block_ns_quota/README.md
  benchmarks/kubectl-mtb/test/benchmarks/block_privilege_escalation/README.md
  benchmarks/kubectl-mtb/test/benchmarks/block_privileged_containers/README.md
  benchmarks/kubectl-mtb/test/benchmarks/block_use_of_host_ipc/README.md
  benchmarks/kubectl-mtb/test/benchmarks/block_use_of_host_networking_and_ports/README.md
  benchmarks/kubectl-mtb/test/benchmarks/block_use_of_host_path/README.md
  benchmarks/kubectl-mtb/test/benchmarks/block_use_of_host_pid/README.md
  benchmarks/kubectl-mtb/test/benchmarks/block_use_of_nodeport_services/README.md
  benchmarks/kubectl-mtb/test/benchmarks/configure_ns_object_quota/README.md
  benchmarks/kubectl-mtb/test/benchmarks/configure_ns_quotas/README.md
  benchmarks/kubectl-mtb/test/benchmarks/create_network_policies/README.md
  benchmarks/kubectl-mtb/test/benchmarks/create_role_bindings/README.md
  benchmarks/kubectl-mtb/test/benchmarks/require_always_pull_image/README.md
  benchmarks/kubectl-mtb/test/benchmarks/require_always_pull_image/config.yaml
  benchmarks/kubectl-mtb/test/benchmarks/require_always_pull_image/require_always_pull_image.go
  benchmarks/kubectl-mtb/test/benchmarks/require_always_pull_image/require_always_pull_image_test.go
  benchmarks/kubectl-mtb/test/benchmarks/require_run_as_non_root_user/README.md
  benchmarks/kubectl-mtb/test/policies/kyverno/all_policies.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#1156 Fix vc manager http server healthz can't start
  incubator/virtualcluster/cmd/manager/main.go
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/S

#1037 Update v1alpha2 HC schema with allowCascadingDeletion
  incubator/hnc/api/v1alpha1/hierarchy_types_conversion.go
  incubator/hnc/api/v1alpha2/hierarchy_types.go
  incubator/hnc/config/crd/bases/hnc.x-k8s.io_hierarchyconfigurations.yaml
  incubator/hnc/docs/user-guide/how-to.md
  incubator/hnc/internal/forest/namespace.go
  incubator/hnc/internal/kubectl/set.go
  incubator/hnc/internal/reconcilers/anchor.go
  incubator/hnc/internal/reconcilers/anchor_test.go
  incubator/hnc/internal/reconcilers/hierarchy_config.go
  incubator/hnc/internal/validators/anchor.go
  incubator/hnc/internal/validators/anchor_test.go
  incubator/hnc/internal/validators/namespace.go
  incubator/hnc/internal/validators/namespace_test.go
  incubator/hnc/test/conversion/conversion_test.go
  incubator/hnc/test/e2e/issues_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1160 Unbreak demo e2e test
  incubator/hnc/test/e2e/demo_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1162 Create minimial v1a2 to v1a1 converters
  incubator/hnc/api/v1alpha1/hierarchy_types_conversion.go
  incubator/hnc/api/v1alpha1/hnc_config_conversion.go
  incubator/hnc/api/v1alpha1/subnamespace_anchor_conversion.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1159 Update docs for v0.5.3
  incubator/hnc/README.md
  incubator/hnc/docs/user-guide/how-to.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#1166 Update docs for v0.5.3
  incubator/hnc/README.md
  incubator/hnc/docs/user-guide/how-to.md
Labels: approved, cncf-cla: yes, lgtm, size/M
