Repository kubernetes-sigs/multi-tenancy, pull requests merged in 2020-11, with the labels that each got.

#1250 Add check for exceptions when checking conflicting objects on mode change
  incubator/hnc/internal/validators/hncconfig.go
  incubator/hnc/internal/validators/hncconfig_test.go
  incubator/hnc/internal/validators/object.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1253 Check if more than one selector is created
  incubator/hnc/internal/validators/object.go
  incubator/hnc/internal/validators/object_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1256 [vc] adding support for custom vn-agent ports
  incubator/virtualcluster/cmd/syncer/app/options/options.go
  incubator/virtualcluster/pkg/syncer/apis/config/types.go
  incubator/virtualcluster/pkg/syncer/resources/node/util.go
  incubator/virtualcluster/pkg/syncer/resources/pod/uws.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#1257 Update namespace deletion validator
  incubator/hnc/internal/validators/namespace.go
  incubator/hnc/internal/validators/namespace_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#1258 [VC] Fix an enqueobject bug
  incubator/virtualcluster/pkg/syncer/handler/enqueue_object.go
  incubator/virtualcluster/pkg/syncer/handler/enqueue_object_test.go
  incubator/virtualcluster/pkg/syncer/resources/register.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1259 VC: introduce vnode provider
  incubator/virtualcluster/pkg/syncer/resources/node/uws.go
  incubator/virtualcluster/pkg/syncer/resources/pod/controller.go
  incubator/virtualcluster/pkg/syncer/resources/pod/uws.go
  incubator/virtualcluster/pkg/syncer/vnode/native/provider.go
  incubator/virtualcluster/pkg/syncer/vnode/vnode.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1264 Add syncer RBAC settings for PriorityClass and Ingress
  incubator/virtualcluster/config/setup/all_in_one.yaml
  incubator/virtualcluster/config/setup/all_in_one_aliyun.yaml
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/M

#1265 Update HNC demo link as the old doc is deprecated
  incubator/hnc/README.md
  incubator/hnc/docs/links.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1266 Quick fix for missing space
  incubator/hnc/docs/user-guide/how-to.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1263 Fixed issues with local development on OSX
  incubator/hnc/Makefile
  incubator/hnc/README.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#1267 HNC: kubectl supports case-insensitive mode
  incubator/hnc/internal/kubectl/configset.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#1271 Better debug and error logging
  incubator/hnc/cmd/manager/main.go
  incubator/hnc/go.mod
  incubator/hnc/vendor/modules.txt
Labels: approved, cncf-cla: yes, lgtm, size/S

#1268 [VirtualCluster] Fix `clusterversions` CRD, add `kind` support and review the demo flow
  incubator/virtualcluster/config/sampleswithspec/tenancy.x-k8s.io_clusterversions.yaml
  incubator/virtualcluster/doc/demo.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#1277 VC: fix: don't call next twice in a loop
  incubator/virtualcluster/pkg/syncer/fairqueue/fair.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1252 MTB: added pv reclaim kyverno policy
  benchmarks/kubectl-mtb/test/policies/kyverno/all_policies.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#1278 Fix E2E tests and namespace deletion validation
  incubator/hnc/internal/validators/namespace.go
  incubator/hnc/pkg/testutils/testutils.go
  incubator/hnc/test/e2e/delete_crd_test.go
  incubator/hnc/test/e2e/issues_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1279 Add to user doc on how to resolve parent missing condition
  incubator/hnc/docs/user-guide/how-to.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#1287 [VirtualCluster] patch to correct the CRDs generated by controller-gen and use them in demo
  incubator/virtualcluster/Makefile
  incubator/virtualcluster/config/crds/tenancy.x-k8s.io_clusterversions.yaml
  incubator/virtualcluster/config/sampleswithspec/clusterversion_v1_loadbalancer.yaml
  incubator/virtualcluster/config/sampleswithspec/clusterversion_v1_nodeport.yaml
  incubator/virtualcluster/doc/demo.md
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/XXL

#1283 CleanupNamespaces shouldn't require an explicit list of namespaces
  incubator/hnc/pkg/testutils/testutils.go
  incubator/hnc/test/conversion/conversion_test.go
  incubator/hnc/test/e2e/delete_crd_test.go
  incubator/hnc/test/e2e/issues_test.go
  incubator/hnc/test/e2e/namespace_test.go
  incubator/hnc/test/e2e/quickstart_test.go
  incubator/hnc/test/e2e/rolebinding_test.go
  incubator/hnc/test/e2e/subnamespace_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#1289 Upgrade controller-runtime to v0.6.4 to replace our patched v0.6.3
  incubator/hnc/go.mod
  incubator/hnc/go.sum
  incubator/hnc/vendor/k8s.io/apimachinery/pkg/apis/meta/internalversion/scheme/doc.go
  incubator/hnc/vendor/k8s.io/apimachinery/pkg/apis/meta/internalversion/scheme/register.go
  incubator/hnc/vendor/k8s.io/client-go/metadata/interface.go
  incubator/hnc/vendor/k8s.io/client-go/metadata/metadata.go
  incubator/hnc/vendor/modules.txt
  incubator/hnc/vendor/sigs.k8s.io/controller-runtime/pkg/builder/controller.go
  incubator/hnc/vendor/sigs.k8s.io/controller-runtime/pkg/builder/options.go
  incubator/hnc/vendor/sigs.k8s.io/controller-runtime/pkg/cache/internal/deleg_map.go
  incubator/hnc/vendor/sigs.k8s.io/controller-runtime/pkg/cache/internal/informers_map.go
  incubator/hnc/vendor/sigs.k8s.io/controller-runtime/pkg/client/apiutil/apimachinery.go
  incubator/hnc/vendor/sigs.k8s.io/controller-runtime/pkg/client/client.go
  incubator/hnc/vendor/sigs.k8s.io/controller-runtime/pkg/client/metadata_client.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#1290 [VC] Fix makefile error
  incubator/virtualcluster/Makefile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1281 Validate only one non-negated namespace for treeSelect
  incubator/hnc/internal/pkg/selectors/selectors.go
  incubator/hnc/internal/validators/object_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1291 Fix MustNotRun() can pass without error bug
  incubator/hnc/pkg/testutils/testutils.go
Labels: approved, cncf-cla: yes, lgtm, size/XS
