Repository kubernetes-sigs/multi-tenancy, pull requests merged in 2020-07, with the labels that each got.

#835 Move manager args to config/manager
  incubator/hnc/config/default/manager_auth_proxy_patch.yaml
  incubator/hnc/config/manager/manager.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#836 Restart the pod if certs change
  incubator/hnc/config/manager/manager.yaml
  incubator/hnc/third_party/open-policy-agent/gatekeeper/pkg/webhook/certs.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#833 Allow finalizers to be removed when deleting CRDs
  incubator/hnc/api/v1alpha1/hierarchy_types.go
  incubator/hnc/config/crd/bases/hnc.x-k8s.io_hierarchyconfigurations.yaml
  incubator/hnc/hack/test-delete-hc-and-anchor-crd.sh
  incubator/hnc/internal/reconcilers/anchor.go
  incubator/hnc/internal/reconcilers/hierarchy_config.go
  incubator/hnc/internal/reconcilers/hnc_config.go
  incubator/hnc/internal/reconcilers/setup.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#839 Document changes in HNC v0.5
  incubator/hnc/docs/user-guide/how-to.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#838 [VC] fix: register UWSOperationCounter
  incubator/virtualcluster/pkg/syncer/metrics/metrics.go
  incubator/virtualcluster/pkg/syncer/resources/storageclass/checker.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#840 Update release instructions
  incubator/hnc/README.md
  incubator/hnc/docs/releasing.md
Labels: approved, cncf-cla: yes, lgtm, size/L

#841 Use CRD validation to enforce singletons
  incubator/hnc/api/v1alpha1/hnc_config.go
  incubator/hnc/config/crd/kustomization.yaml
  incubator/hnc/config/crd/patches/singleton_validation_hierarchyconfiguration.yaml
  incubator/hnc/config/crd/patches/singleton_validation_hncconfiguration.yaml
  incubator/hnc/internal/reconcilers/hnc_config.go
  incubator/hnc/internal/reconcilers/hnc_config_test.go
  incubator/hnc/internal/validators/hncconfig.go
  incubator/hnc/internal/validators/hncconfig_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#848 Update docs to refer to HNC v0.5
  incubator/hnc/README.md
  incubator/hnc/docs/user-guide/README.md
  incubator/hnc/docs/user-guide/how-to.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#849 Update docs to refer to HNC v0.5
  incubator/hnc/README.md
  incubator/hnc/docs/user-guide/README.md
  incubator/hnc/docs/user-guide/how-to.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#826 [MTB]Add additional fields dynamically to README
  benchmarks/kubectl-mtb/docs/main.go
  benchmarks/kubectl-mtb/go.mod
  benchmarks/kubectl-mtb/go.sum
  benchmarks/kubectl-mtb/test/benchmarks/block_privileged_containers/README.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#837 Fix compilation error with latest k8s API
  tenant/pkg/controller/tenant/tenant_controller.go
  tenant/pkg/controller/tenantnamespace/tenantnamespace_controller.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#851 Regenerate manifest files
  incubator/hnc/config/crd/bases/hnc.x-k8s.io_hncconfigurations.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#842 Add timer for webhook server to get ready before test
  incubator/hnc/Makefile
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#815 [MTB] auto register benchmark
  benchmarks/kubectl-mtb/.gitignore
  benchmarks/kubectl-mtb/Makefile
  benchmarks/kubectl-mtb/bundle/box/blob.go
  benchmarks/kubectl-mtb/bundle/importer/generator.go
  benchmarks/kubectl-mtb/cmd/mtb_builder/main.go
  benchmarks/kubectl-mtb/go.mod
  benchmarks/kubectl-mtb/go.sum
  benchmarks/kubectl-mtb/internal/kubectl/root.go
  benchmarks/kubectl-mtb/internal/mtb_builder/create.go
  benchmarks/kubectl-mtb/internal/mtb_builder/root.go
  benchmarks/kubectl-mtb/internal/mtb_builder/tpl.go
  benchmarks/kubectl-mtb/main.go
  benchmarks/kubectl-mtb/test/benchmarks/block_privileged_containers/block_privileged_containers.go
  benchmarks/kubectl-mtb/test/test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#821 [MTB] Added Default Reporter
  benchmarks/kubectl-mtb/go.mod
  benchmarks/kubectl-mtb/go.sum
  benchmarks/kubectl-mtb/internal/kubectl/test.go
  benchmarks/kubectl-mtb/internal/reporter/default_reporter.go
  benchmarks/kubectl-mtb/internal/reporter/printer/console_logging.go
  benchmarks/kubectl-mtb/internal/reporter/reporter.go
  benchmarks/kubectl-mtb/internal/reporter/types.go
  benchmarks/kubectl-mtb/main.go
  benchmarks/kubectl-mtb/test/benchmarks/block_privileged_containers/block_privileged_containers.go
  benchmarks/kubectl-mtb/test/test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#812 [MTB] added readme
  benchmarks/kubectl-mtb/Makefile
  benchmarks/kubectl-mtb/README.md
  benchmarks/kubectl-mtb/bundle/importer/generator.go
  benchmarks/kubectl-mtb/cmd/kubectl-mtb/main.go
  benchmarks/kubectl-mtb/internal/kubectl-mtb/get.go
  benchmarks/kubectl-mtb/internal/kubectl-mtb/root.go
  benchmarks/kubectl-mtb/internal/kubectl-mtb/test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#857 Changes to import tenant namespace controller
  tenant/pkg/controller/tenant/tenant_controller_suite.go
  tenant/pkg/controller/tenantnamespace/tenantnamespace_controller.go
  tenant/pkg/controller/tenantnamespace/tenantnamespace_controller_suite_test.go
  tenant/pkg/controller/tenantnamespace/tenantnamespace_controller_test.go
  tenant/pkg/controller/tenantnamespace/tenantnamespace_helper.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#858 Remove deploy before E2E test
  incubator/hnc/Makefile
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#855 Prevent deletion of propagated objects
  incubator/hnc/config/webhook/manifests.yaml
  incubator/hnc/internal/validators/object.go
  incubator/hnc/internal/validators/object_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#853 Prevent deletion of propagated objects
  incubator/hnc/config/webhook/manifests.yaml
  incubator/hnc/internal/validators/object.go
  incubator/hnc/internal/validators/object_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#867 Restore webhook in e2e test from the current manifest
  incubator/hnc/hack/test-issue-797-leaf.sh
  incubator/hnc/hack/test-issue-797-non-leaf.sh
Labels: approved, cncf-cla: yes, lgtm, size/S

#863 [VC] Fixing "complement" spelling funcs
  incubator/virtualcluster/pkg/controller/virtualcluster/master_provisioner_native.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#862 [MTB] added policy reporter
  benchmarks/kubectl-mtb/go.mod
  benchmarks/kubectl-mtb/go.sum
  benchmarks/kubectl-mtb/internal/kubectl-mtb/test.go
  benchmarks/kubectl-mtb/internal/reporter/default_reporter.go
  benchmarks/kubectl-mtb/internal/reporter/policy_reporter.go
  benchmarks/kubectl-mtb/internal/reporter/reporter.go
  benchmarks/kubectl-mtb/internal/reporter/types.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#864 [MTB]Setup to Add Unittests
  benchmarks/kubectl-mtb/Makefile
  benchmarks/kubectl-mtb/docs/main.go
  benchmarks/kubectl-mtb/go.mod
  benchmarks/kubectl-mtb/go.sum
  benchmarks/kubectl-mtb/test/assets/kyverno.yaml
  benchmarks/kubectl-mtb/test/assets/tenancy_v1alpha1_tenant.yaml
  benchmarks/kubectl-mtb/test/assets/tenancy_v1alpha1_tenantnamespace.yaml
  benchmarks/kubectl-mtb/test/benchmarks/block_privileged_containers/block_privileged_containers.go
  benchmarks/kubectl-mtb/test/benchmarks/block_privileged_containers/block_privileged_containers_test.go
  benchmarks/kubectl-mtb/test/utils/resources/pod/pod.go
  benchmarks/kubectl-mtb/test/utils/unittestutils/client.go
  benchmarks/kubectl-mtb/test/utils/unittestutils/cluster.go
  benchmarks/kubectl-mtb/test/utils/unittestutils/create_policy.go
  benchmarks/kubectl-mtb/test/utils/unittestutils/manifests.go
  benchmarks/kubectl-mtb/test/utils/unittestutils/rbac_create.go
  benchmarks/kubectl-mtb/test/utils/unittestutils/tenants_test_util.go
  benchmarks/kubectl-mtb/test/utils/util.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XXL

#870 Restructure handle() in the namespace validator
  incubator/hnc/internal/validators/namespace.go
  incubator/hnc/internal/validators/namespace_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#875 Support using ClusterIP for the API Server service
  incubator/virtualcluster/cmd/vcctl/subcmd/create.go
  incubator/virtualcluster/pkg/controller/virtualcluster/master_provisioner_native.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#860 convert test-delete-anchor-crd to go test file
  incubator/hnc/e2e/tests/delete_crd_test.go
  incubator/hnc/e2e/tests/e2e_test.go
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/M

#877 Add nodes/proxy to vn-agent RBAC
  incubator/virtualcluster/config/setup/all_in_one.yaml
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/XS

#882 Refactor e2e test
  incubator/hnc/e2e/tests/delete_crd_test.go
  incubator/hnc/e2e/tests/e2e_test.go
  incubator/hnc/e2e/tests/namespace_test.go
  incubator/hnc/e2e/tests/subnamespace_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#866 Allow subnamespace deletion if parent/anchor is missing
  incubator/hnc/internal/forest/namespace.go
  incubator/hnc/internal/validators/namespace.go
  incubator/hnc/internal/validators/namespace_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#879 [VC] setup e2e testing framework
  incubator/virtualcluster/go.mod
  incubator/virtualcluster/go.sum
  incubator/virtualcluster/pkg/syncer/constants/constants.go
  incubator/virtualcluster/pkg/syncer/conversion/helper.go
  incubator/virtualcluster/pkg/syncer/syncer.go
  incubator/virtualcluster/test/e2e/e2e.go
  incubator/virtualcluster/test/e2e/e2e_test.go
  incubator/virtualcluster/test/e2e/framework/cleanup.go
  incubator/virtualcluster/test/e2e/framework/clusterversion/create.go
  incubator/virtualcluster/test/e2e/framework/clusterversion/delete.go
  incubator/virtualcluster/test/e2e/framework/framework.go
  incubator/virtualcluster/test/e2e/framework/text_context.go
  incubator/virtualcluster/test/e2e/framework/util.go
  incubator/virtualcluster/test/e2e/framework/vc.go
  incubator/virtualcluster/test/e2e/framework/virtualcluster/wait.go
  incubator/virtualcluster/test/e2e/multi-tenancy/framework.go
  incubator/virtualcluster/test/e2e/multi-tenancy/virtual_cluster.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#884 Warn the testers if HNC cannot be repaired
  incubator/hnc/e2e/tests/delete_crd_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#888 Add delete-hc-crd test to e2e test suite
  incubator/hnc/e2e/tests/delete_crd_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#887 Make it easier to uninstall HNC
  incubator/hnc/Makefile
Labels: approved, cncf-cla: yes, lgtm, size/S

#890 Unbreak object validator on 1.14
  incubator/hnc/internal/validators/object.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#892 [VC] syncer: drop uws request if cluster is not found
  incubator/virtualcluster/pkg/syncer/errors/errors.go
  incubator/virtualcluster/pkg/syncer/errors/errors_test.go
  incubator/virtualcluster/pkg/syncer/mccontroller/mccontroller.go
  incubator/virtualcluster/pkg/syncer/resources/event/uws.go
  incubator/virtualcluster/pkg/syncer/resources/persistentvolume/uws.go
  incubator/virtualcluster/pkg/syncer/resources/pod/uws.go
  incubator/virtualcluster/pkg/syncer/resources/service/uws.go
  incubator/virtualcluster/pkg/syncer/syncer.go
  incubator/virtualcluster/pkg/syncer/uwcontroller/uwcontroller.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#894 Add delete-hc-and-anchor-crd test
  incubator/hnc/e2e/tests/delete_crd_test.go
  incubator/hnc/e2e/tests/e2e_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#895 Change HNC image name to hnc-manager
  incubator/hnc/Makefile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#900 Fix BeforeEach()
  incubator/hnc/e2e/tests/delete_crd_test.go
  incubator/hnc/e2e/tests/namespace_test.go
  incubator/hnc/e2e/tests/subnamespace_test.go
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/XS

#898 Add e2e test for issue 328
  incubator/hnc/e2e/tests/delete_crd_test.go
  incubator/hnc/e2e/tests/e2e_test.go
  incubator/hnc/e2e/tests/issues_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#903 Replace pattern with enum to enforce singleton
  incubator/hnc/config/crd/patches/singleton_validation_hierarchyconfiguration.yaml
  incubator/hnc/config/crd/patches/singleton_validation_hncconfiguration.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#897 [MTB]Changed unit test setup
  benchmarks/kubectl-mtb/Makefile
  benchmarks/kubectl-mtb/internal/mtb_builder/tpl.go
  benchmarks/kubectl-mtb/test/benchmarks/block_privileged_containers/block_privileged_containers_test.go
  benchmarks/kubectl-mtb/test/utils/unittestutils/cluster.go
  benchmarks/kubectl-mtb/test/utils/unittestutils/tenants_test_util.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#883 [MTB]Added table to display benchmark summary
  benchmarks/kubectl-mtb/go.mod
  benchmarks/kubectl-mtb/go.sum
  benchmarks/kubectl-mtb/internal/kubectl-mtb/test.go
  benchmarks/kubectl-mtb/internal/reporter/default_reporter.go
  benchmarks/kubectl-mtb/internal/reporter/policy_reporter.go
  benchmarks/kubectl-mtb/internal/reporter/reporter.go
  benchmarks/kubectl-mtb/internal/reporter/types.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#893 [MTB]Added check for tenant-admin and tenant namespace
  benchmarks/kubectl-mtb/internal/kubectl-mtb/test.go
  benchmarks/kubectl-mtb/test/utils/apiutils.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#896 [MTB] added chain reporter
  benchmarks/kubectl-mtb/internal/kubectl-mtb/test.go
  benchmarks/kubectl-mtb/internal/reporter/default_reporter.go
  benchmarks/kubectl-mtb/internal/reporter/policy_reporter.go
  benchmarks/kubectl-mtb/internal/reporter/reporter.go
  benchmarks/kubectl-mtb/internal/reporter/types.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#902 Use enum schema validation for HNCConfig spec modes
  incubator/hnc/api/v1alpha1/hnc_config.go
  incubator/hnc/config/crd/bases/hnc.x-k8s.io_hncconfigurations.yaml
  incubator/hnc/internal/validators/hncconfig.go
  incubator/hnc/internal/validators/hncconfig_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#905 Add e2e test for issue 501
  incubator/hnc/e2e/tests/e2e_test.go
  incubator/hnc/e2e/tests/issues_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#909 Add e2e test for clearing CannotUpdate conditions in descendants when a
  incubator/hnc/e2e/tests/issues_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#906 Use discovery to validate types in hncconfig
  incubator/hnc/internal/validators/hncconfig.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#913 Add test for CritParentMissing condition
  incubator/hnc/e2e/tests/issues_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#912 [VC] exclude e2e test from default test
  incubator/virtualcluster/Makefile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#918 Add test for deleting leaf namespace
  incubator/hnc/e2e/tests/issues_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#920 Change folder name from e2e/tests to test/e2e
  incubator/hnc/Makefile
  incubator/hnc/test/e2e/delete_crd_test.go
  incubator/hnc/test/e2e/e2e_test.go
  incubator/hnc/test/e2e/issues_test.go
  incubator/hnc/test/e2e/namespace_test.go
  incubator/hnc/test/e2e/subnamespace_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#921 Remove tests under hack/ which are already converted to e2e tests
  incubator/hnc/hack/test-delete-anchor-crd.sh
  incubator/hnc/hack/test-delete-hc-and-anchor-crd.sh
  incubator/hnc/hack/test-delete-hc-crd.sh
  incubator/hnc/hack/test-issue-328.sh
  incubator/hnc/hack/test-issue-501.sh
  incubator/hnc/hack/test-issue-605.sh
  incubator/hnc/hack/test-issue-716-full.sh
  incubator/hnc/hack/test-issue-716-leafsub.sh
Labels: approved, cncf-cla: yes, lgtm, size/L

#911 [VC] fix data race when there are multi sa secret
  incubator/virtualcluster/pkg/syncer/conversion/helper_test.go
  incubator/virtualcluster/pkg/syncer/conversion/mutate.go
  incubator/virtualcluster/pkg/syncer/resources/pod/checker_test.go
  incubator/virtualcluster/pkg/syncer/resources/pod/dws.go
  incubator/virtualcluster/pkg/syncer/resources/pod/dws_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#922 [VC] Make sure VolumeMount is a secret volume before mutation
  incubator/virtualcluster/pkg/syncer/constants/constants.go
  incubator/virtualcluster/pkg/syncer/conversion/helper_test.go
  incubator/virtualcluster/pkg/syncer/conversion/mutate.go
  incubator/virtualcluster/pkg/syncer/resources/secret/dws_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#880 [MTB]Added Remaining benchmarks
  benchmarks/kubectl-mtb/test/benchmarks/configure_ns_object_quota/README.md
  benchmarks/kubectl-mtb/test/benchmarks/configure_ns_object_quota/config.yaml
  benchmarks/kubectl-mtb/test/benchmarks/configure_ns_object_quota/configure_ns_object_quota.go
  benchmarks/kubectl-mtb/test/benchmarks/configure_ns_object_quota/configure_ns_object_quota_test.go
  benchmarks/kubectl-mtb/test/benchmarks/configure_ns_quotas/README.md
  benchmarks/kubectl-mtb/test/benchmarks/configure_ns_quotas/config.yaml
  benchmarks/kubectl-mtb/test/benchmarks/configure_ns_quotas/configure_ns_quotas.go
  benchmarks/kubectl-mtb/test/benchmarks/configure_ns_quotas/configure_ns_quotas_test.go
  benchmarks/kubectl-mtb/test/quotas/ns_quota.yaml
  benchmarks/kubectl-mtb/test/utils/apiutils.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#910 [MTB] Added docs
  benchmarks/kubectl-mtb/README.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#919 [MTB] added unit tests
  benchmarks/kubectl-mtb/Makefile
  benchmarks/kubectl-mtb/internal/mtb_builder/tpl.go
  benchmarks/kubectl-mtb/test/benchmarks/block_access_to_cluster_resources/block_access_to_cluster_resources_test.go
  benchmarks/kubectl-mtb/test/benchmarks/block_add_capabilities/block_add_capabilities_test.go
  benchmarks/kubectl-mtb/test/benchmarks/block_privilege_escalation/block_privilege_escalation_test.go
  benchmarks/kubectl-mtb/test/benchmarks/block_privileged_containers/block_privileged_containers_test.go
  benchmarks/kubectl-mtb/test/benchmarks/block_use_of_bind_mounts/block_use_of_bind_mounts_test.go
  benchmarks/kubectl-mtb/test/benchmarks/block_use_of_host_ipc/block_use_of_host_ipc_test.go
  benchmarks/kubectl-mtb/test/benchmarks/block_use_of_host_networking_and_ports/block_use_of_host_networking_and_ports_test.go
  benchmarks/kubectl-mtb/test/benchmarks/block_use_of_host_pid/block_use_of_host_pid_test.go
  benchmarks/kubectl-mtb/test/benchmarks/block_use_of_nodeport_services/block_use_of_nodeport_services.go
  benchmarks/kubectl-mtb/test/benchmarks/block_use_of_nodeport_services/block_use_of_nodeport_services_test.go
  benchmarks/kubectl-mtb/test/benchmarks/require_run_as_non_root_user/require_run_as_non_root_user_test.go
  benchmarks/kubectl-mtb/test/utils/unittestutils/client.go
  benchmarks/kubectl-mtb/test/utils/unittestutils/manifests.go
  benchmarks/kubectl-mtb/test/utils/unittestutils/rbac_create.go
  benchmarks/kubectl-mtb/test/utils/unittestutils/tenants_test_util.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XXL

#917 Unbreak object validator on 1.14
  incubator/hnc/internal/validators/object.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#924 Add test for deleting a non-leaf subnamespace
  incubator/hnc/hack/test-issue-716-nonleafsub.sh
  incubator/hnc/test/e2e/issues_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#926 Add test for creating and clearing unpropagatable object
  incubator/hnc/hack/test-issue-771.sh
  incubator/hnc/test/e2e/issues_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#928 Rename the package name from 'test' to 'e2e'
  incubator/hnc/test/e2e/delete_crd_test.go
  incubator/hnc/test/e2e/e2e_test.go
  incubator/hnc/test/e2e/issues_test.go
  incubator/hnc/test/e2e/namespace_test.go
  incubator/hnc/test/e2e/subnamespace_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#927 Add test for propagating admin rolebindings
  incubator/hnc/hack/test-issue-772.sh
  incubator/hnc/test/e2e/issues_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#931 Add test for deleting good and bad parent namespaces under race condition
  incubator/hnc/hack/test-issue-797-leaf.sh
  incubator/hnc/test/e2e/delete_crd_test.go
  incubator/hnc/test/e2e/e2e_test.go
  incubator/hnc/test/e2e/issues_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#933 [MTB] Added minor tweaks and skip flag
  benchmarks/kubectl-mtb/go.sum
  benchmarks/kubectl-mtb/internal/kubectl-mtb/test.go
  benchmarks/kubectl-mtb/internal/reporter/default_reporter.go
  benchmarks/kubectl-mtb/internal/reporter/policy_reporter.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#940 [MTB] Added Policies
  benchmarks/kubectl-mtb/docs/main.go
  benchmarks/kubectl-mtb/test/benchmarks/block_access_to_cluster_resources/README.md
  benchmarks/kubectl-mtb/test/benchmarks/block_add_capabilities/README.md
  benchmarks/kubectl-mtb/test/benchmarks/block_add_capabilities/config.yaml
  benchmarks/kubectl-mtb/test/benchmarks/block_ns_quota/README.md
  benchmarks/kubectl-mtb/test/benchmarks/block_privilege_escalation/README.md
  benchmarks/kubectl-mtb/test/benchmarks/block_privilege_escalation/config.yaml
  benchmarks/kubectl-mtb/test/benchmarks/block_privileged_containers/README.md
  benchmarks/kubectl-mtb/test/benchmarks/block_privileged_containers/config.yaml
  benchmarks/kubectl-mtb/test/benchmarks/block_use_of_bind_mounts/README.md
  benchmarks/kubectl-mtb/test/benchmarks/block_use_of_bind_mounts/config.yaml
  benchmarks/kubectl-mtb/test/benchmarks/block_use_of_host_ipc/README.md
  benchmarks/kubectl-mtb/test/benchmarks/block_use_of_host_ipc/config.yaml
  benchmarks/kubectl-mtb/test/benchmarks/block_use_of_host_networking_and_ports/README.md
  benchmarks/kubectl-mtb/test/benchmarks/block_use_of_host_pid/README.md
  benchmarks/kubectl-mtb/test/benchmarks/block_use_of_host_pid/config.yaml
  benchmarks/kubectl-mtb/test/benchmarks/block_use_of_nodeport_services/README.md
  benchmarks/kubectl-mtb/test/benchmarks/block_use_of_nodeport_services/config.yaml
  benchmarks/kubectl-mtb/test/benchmarks/configure_ns_object_quota/README.md
  benchmarks/kubectl-mtb/test/benchmarks/configure_ns_quotas/README.md
  benchmarks/kubectl-mtb/test/benchmarks/create_network_policies/README.md
  benchmarks/kubectl-mtb/test/benchmarks/require_run_as_non_root_user/README.md
  benchmarks/kubectl-mtb/test/benchmarks/require_run_as_non_root_user/config.yaml
  benchmarks/kubectl-mtb/test/policies/block_add_capabilities/gatekeeper/constraint.yaml
  benchmarks/kubectl-mtb/test/policies/block_add_capabilities/gatekeeper/template.yaml
  benchmarks/kubectl-mtb/test/policies/block_add_capabilities/kyverno/block_add_capabilities.yaml
  benchmarks/kubectl-mtb/test/policies/block_privilege_escalation/gatekeeper/constraint.yaml
  benchmarks/kubectl-mtb/test/policies/block_privilege_escalation/gatekeeper/template.yaml
  benchmarks/kubectl-mtb/test/policies/block_privilege_escalation/kyverno/block_privilege_escalation.yaml
  benchmarks/kubectl-mtb/test/policies/block_privileged_containers/gatekeeper/constraint.yaml
  benchmarks/kubectl-mtb/test/policies/block_privileged_containers/gatekeeper/template.yaml
  benchmarks/kubectl-mtb/test/policies/block_privileged_containers/kyverno/block_privileged_containers.yaml
  benchmarks/kubectl-mtb/test/policies/block_use_of_bind_mounts/gatekeeper/constraint.yaml
  benchmarks/kubectl-mtb/test/policies/block_use_of_bind_mounts/gatekeeper/template.yaml
  benchmarks/kubectl-mtb/test/policies/block_use_of_bind_mounts/kyverno/block_use_of_bind_mounts.yaml
  benchmarks/kubectl-mtb/test/policies/block_use_of_host_ipc_pid/gatekeeper/constraint.yaml
  benchmarks/kubectl-mtb/test/policies/block_use_of_host_ipc_pid/gatekeeper/template.yaml
  benchmarks/kubectl-mtb/test/policies/block_use_of_host_ipc_pid/kyverno/block_use_of_host_ipc_pid.yaml
  benchmarks/kubectl-mtb/test/policies/block_use_of_nodeport_services/gatekeeper/constraint.yaml
  benchmarks/kubectl-mtb/test/policies/block_use_of_nodeport_services/gatekeeper/template.yaml
  benchmarks/kubectl-mtb/test/policies/block_use_of_nodeport_services/kyverno/block_use_of_nodeport_service.yaml
  benchmarks/kubectl-mtb/test/policies/require_run_as_non_root_user/gatekeeper/constraint.yaml
  benchmarks/kubectl-mtb/test/policies/require_run_as_non_root_user/gatekeeper/template.yaml
  benchmarks/kubectl-mtb/test/policies/require_run_as_non_root_user/kyverno/require_run_as_non_root_user.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XL

#938 [MTB] changed flag name -t to --as
  benchmarks/kubectl-mtb/internal/kubectl-mtb/test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#939 Test optimization
  benchmarks/kubectl-mtb/Makefile
  benchmarks/kubectl-mtb/go.mod
  benchmarks/kubectl-mtb/go.sum
  benchmarks/kubectl-mtb/internal/mtb_builder/tpl.go
  benchmarks/kubectl-mtb/test/benchmarks/block_add_capabilities/block_add_capabilities_test.go
  benchmarks/kubectl-mtb/test/benchmarks/block_privilege_escalation/block_privilege_escalation_test.go
  benchmarks/kubectl-mtb/test/benchmarks/block_privileged_containers/block_privileged_containers_test.go
  benchmarks/kubectl-mtb/test/benchmarks/block_use_of_bind_mounts/block_use_of_bind_mounts_test.go
  benchmarks/kubectl-mtb/test/benchmarks/block_use_of_host_ipc/block_use_of_host_ipc_test.go
  benchmarks/kubectl-mtb/test/benchmarks/block_use_of_host_networking_and_ports/block_use_of_host_networking_and_ports_test.go
  benchmarks/kubectl-mtb/test/benchmarks/block_use_of_host_pid/block_use_of_host_pid_test.go
  benchmarks/kubectl-mtb/test/benchmarks/block_use_of_nodeport_services/block_use_of_nodeport_services_test.go
  benchmarks/kubectl-mtb/test/benchmarks/require_run_as_non_root_user/require_run_as_non_root_user_test.go
  benchmarks/kubectl-mtb/test/utils/unittestutils/client.go
  benchmarks/kubectl-mtb/test/utils/unittestutils/manifests.go
  benchmarks/kubectl-mtb/test/utils/unittestutils/rbac_create.go
  benchmarks/kubectl-mtb/test/utils/unittestutils/tenants_test_util.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XXL

#932 Add test for deleting a non-leaf child namespace under race condition
  incubator/hnc/hack/test-issue-797-non-leaf.sh
  incubator/hnc/test/e2e/issues_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#944 [MTB] Bugs removal and ux enhancement
  benchmarks/kubectl-mtb/internal/kubectl-mtb/get.go
  benchmarks/kubectl-mtb/internal/kubectl-mtb/root.go
  benchmarks/kubectl-mtb/internal/kubectl-mtb/run.go
  benchmarks/kubectl-mtb/test/benchmarks/block_add_capabilities/README.md
  benchmarks/kubectl-mtb/test/benchmarks/block_add_capabilities/config.yaml
  benchmarks/kubectl-mtb/test/benchmarks/block_privilege_escalation/README.md
  benchmarks/kubectl-mtb/test/benchmarks/block_privilege_escalation/config.yaml
  benchmarks/kubectl-mtb/test/benchmarks/block_privileged_containers/README.md
  benchmarks/kubectl-mtb/test/benchmarks/block_privileged_containers/config.yaml
  benchmarks/kubectl-mtb/test/benchmarks/block_use_of_bind_mounts/README.md
  benchmarks/kubectl-mtb/test/benchmarks/block_use_of_bind_mounts/config.yaml
  benchmarks/kubectl-mtb/test/benchmarks/block_use_of_host_ipc/README.md
  benchmarks/kubectl-mtb/test/benchmarks/block_use_of_host_ipc/config.yaml
  benchmarks/kubectl-mtb/test/benchmarks/block_use_of_host_pid/README.md
  benchmarks/kubectl-mtb/test/benchmarks/block_use_of_host_pid/config.yaml
  benchmarks/kubectl-mtb/test/benchmarks/block_use_of_nodeport_services/README.md
  benchmarks/kubectl-mtb/test/benchmarks/block_use_of_nodeport_services/config.yaml
  benchmarks/kubectl-mtb/test/benchmarks/require_run_as_non_root_user/README.md
  benchmarks/kubectl-mtb/test/benchmarks/require_run_as_non_root_user/config.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#949 [MTB] changed validation check for tenantnamespaces
  benchmarks/kubectl-mtb/internal/kubectl-mtb/run.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#945 [MTB] Update Docs
  benchmarks/kubectl-mtb/README.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#948 Add links to testinfra
  incubator/hnc/README.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#952 [MTB] Remove typos
  benchmarks/kubectl-mtb/README.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#947 Add e2e tests to release instructions
  incubator/hnc/Makefile
  incubator/hnc/docs/releasing.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#946 Fix the flaky test for #716
  incubator/hnc/test/e2e/e2e_test.go
  incubator/hnc/test/e2e/issues_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#956 Add testutils package
  incubator/hnc/pkg/testutils.go
  incubator/hnc/test/e2e/delete_crd_test.go
  incubator/hnc/test/e2e/e2e_test.go
  incubator/hnc/test/e2e/issues_test.go
  incubator/hnc/test/e2e/namespace_test.go
  incubator/hnc/test/e2e/subnamespace_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#951 add vcname to metadata
  incubator/virtualcluster/pkg/syncer/conversion/helper.go
  incubator/virtualcluster/pkg/syncer/resources/configmap/dws.go
  incubator/virtualcluster/pkg/syncer/resources/endpoints/dws.go
  incubator/virtualcluster/pkg/syncer/resources/persistentvolume/uws.go
  incubator/virtualcluster/pkg/syncer/resources/persistentvolumeclaim/dws.go
  incubator/virtualcluster/pkg/syncer/resources/pod/dws.go
  incubator/virtualcluster/pkg/syncer/resources/pod/dws_test.go
  incubator/virtualcluster/pkg/syncer/resources/secret/checker_test.go
  incubator/virtualcluster/pkg/syncer/resources/secret/dws.go
  incubator/virtualcluster/pkg/syncer/resources/secret/dws_test.go
  incubator/virtualcluster/pkg/syncer/resources/service/dws.go
  incubator/virtualcluster/pkg/syncer/resources/serviceaccount/dws.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#957 Backport all e2e tests to HNC v0.5
  incubator/hnc/Makefile
  incubator/hnc/e2e/tests/namespace_test.go
  incubator/hnc/e2e/tests/subnamespace_test.go
  incubator/hnc/hack/test-delete-anchor-crd.sh
  incubator/hnc/hack/test-delete-hc-and-anchor-crd.sh
  incubator/hnc/hack/test-delete-hc-crd.sh
  incubator/hnc/hack/test-issue-328.sh
  incubator/hnc/hack/test-issue-501.sh
  incubator/hnc/hack/test-issue-605.sh
  incubator/hnc/hack/test-issue-716-full.sh
  incubator/hnc/hack/test-issue-716-leafsub.sh
  incubator/hnc/hack/test-issue-716-nonleafsub.sh
  incubator/hnc/hack/test-issue-771.sh
  incubator/hnc/hack/test-issue-772.sh
  incubator/hnc/hack/test-issue-797-leaf.sh
  incubator/hnc/hack/test-issue-797-non-leaf.sh
  incubator/hnc/pkg/testutils.go
  incubator/hnc/test/e2e/delete_crd_test.go
  incubator/hnc/test/e2e/e2e_test.go
  incubator/hnc/test/e2e/issues_test.go
  incubator/hnc/test/e2e/namespace_test.go
  incubator/hnc/test/e2e/subnamespace_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#960 Add e2e test for 'Basic functionality' part in demo
  incubator/hnc/test/e2e/demo_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#965 Move testutils to its own directory
  incubator/hnc/pkg/testutils/testutils.go
  incubator/hnc/test/e2e/delete_crd_test.go
  incubator/hnc/test/e2e/demo_test.go
  incubator/hnc/test/e2e/issues_test.go
  incubator/hnc/test/e2e/namespace_test.go
  incubator/hnc/test/e2e/subnamespace_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#970 Support args with spaces in them
  incubator/hnc/pkg/testutils/testutils.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#964 Add e2e test for 'Propagating different types' in demo
  incubator/hnc/test/e2e/demo_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#967 Changed policies directory structure
  benchmarks/kubectl-mtb/README.md
  benchmarks/kubectl-mtb/test/policies/block_add_capabilities/kyverno/block_add_capabilities.yaml
  benchmarks/kubectl-mtb/test/policies/block_privilege_escalation/kyverno/block_privilege_escalation.yaml
  benchmarks/kubectl-mtb/test/policies/block_privileged_containers/kyverno/block_privileged_containers.yaml
  benchmarks/kubectl-mtb/test/policies/block_use_of_bind_mounts/kyverno/block_use_of_bind_mounts.yaml
  benchmarks/kubectl-mtb/test/policies/block_use_of_host_ipc_pid/kyverno/block_use_of_host_ipc_pid.yaml
  benchmarks/kubectl-mtb/test/policies/block_use_of_nodeport_services/kyverno/block_use_of_nodeport_service.yaml
  benchmarks/kubectl-mtb/test/policies/gatekeeper/block_add_capabilities/gatekeeper/constraint.yaml
  benchmarks/kubectl-mtb/test/policies/gatekeeper/block_add_capabilities/gatekeeper/template.yaml
  benchmarks/kubectl-mtb/test/policies/gatekeeper/block_privilege_escalation/gatekeeper/constraint.yaml
  benchmarks/kubectl-mtb/test/policies/gatekeeper/block_privilege_escalation/gatekeeper/template.yaml
  benchmarks/kubectl-mtb/test/policies/gatekeeper/block_privileged_containers/gatekeeper/constraint.yaml
  benchmarks/kubectl-mtb/test/policies/gatekeeper/block_privileged_containers/gatekeeper/template.yaml
  benchmarks/kubectl-mtb/test/policies/gatekeeper/block_use_of_bind_mounts/gatekeeper/constraint.yaml
  benchmarks/kubectl-mtb/test/policies/gatekeeper/block_use_of_bind_mounts/gatekeeper/template.yaml
  benchmarks/kubectl-mtb/test/policies/gatekeeper/block_use_of_host_ipc_pid/gatekeeper/constraint.yaml
  benchmarks/kubectl-mtb/test/policies/gatekeeper/block_use_of_host_ipc_pid/gatekeeper/template.yaml
  benchmarks/kubectl-mtb/test/policies/gatekeeper/block_use_of_nodeport_services/gatekeeper/constraint.yaml
  benchmarks/kubectl-mtb/test/policies/gatekeeper/block_use_of_nodeport_services/gatekeeper/template.yaml
  benchmarks/kubectl-mtb/test/policies/gatekeeper/require_run_as_non_root_user/gatekeeper/constraint.yaml
  benchmarks/kubectl-mtb/test/policies/gatekeeper/require_run_as_non_root_user/gatekeeper/template.yaml
  benchmarks/kubectl-mtb/test/policies/kyverno/all_policies.yaml
  benchmarks/kubectl-mtb/test/policies/require_run_as_non_root_user/kyverno/require_run_as_non_root_user.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#966 changed unittest template
  benchmarks/kubectl-mtb/Makefile
  benchmarks/kubectl-mtb/go.mod
  benchmarks/kubectl-mtb/internal/mtb_builder/tpl.go
  benchmarks/kubectl-mtb/test/benchmarks/block_add_capabilities/block_add_capabilities_test.go
  benchmarks/kubectl-mtb/test/benchmarks/block_privilege_escalation/block_privilege_escalation_test.go
  benchmarks/kubectl-mtb/test/benchmarks/block_privileged_containers/block_privileged_containers_test.go
  benchmarks/kubectl-mtb/test/benchmarks/block_use_of_bind_mounts/block_use_of_bind_mounts_test.go
  benchmarks/kubectl-mtb/test/benchmarks/block_use_of_host_ipc/block_use_of_host_ipc_test.go
  benchmarks/kubectl-mtb/test/benchmarks/block_use_of_host_networking_and_ports/block_use_of_host_networking_and_ports_test.go
  benchmarks/kubectl-mtb/test/benchmarks/block_use_of_host_pid/block_use_of_host_pid_test.go
  benchmarks/kubectl-mtb/test/benchmarks/block_use_of_nodeport_services/block_use_of_nodeport_services_test.go
  benchmarks/kubectl-mtb/test/benchmarks/create_network_policies/create_network_policies_test.go
  benchmarks/kubectl-mtb/test/benchmarks/require_run_as_non_root_user/require_run_as_non_root_user_test.go
  benchmarks/kubectl-mtb/test/utils/unittestutils/manifests.go
  benchmarks/kubectl-mtb/test/utils/unittestutils/tenants_test_util.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XXL

#971 Add e2e test for subnamespaces in hnc demo
  incubator/hnc/test/e2e/demo_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#976 Make it work with Go 1.15
  incubator/hnc/internal/reconcilers/hierarchy_config_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#963 Resource quota Benchmark Bug
  benchmarks/kubectl-mtb/Makefile
  benchmarks/kubectl-mtb/test/benchmarks/configure_ns_object_quota/configure_ns_object_quota.go
  benchmarks/kubectl-mtb/test/benchmarks/configure_ns_quotas/configure_ns_quotas.go
  benchmarks/kubectl-mtb/test/quotas/ns_quota.yaml
  benchmarks/kubectl-mtb/test/utils/resources/pod/pod.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#978 Run gofmt on all tests
  incubator/hnc/pkg/testutils/testutils.go
  incubator/hnc/test/e2e/delete_crd_test.go
  incubator/hnc/test/e2e/demo_test.go
  incubator/hnc/test/e2e/issues_test.go
  incubator/hnc/test/e2e/namespace_test.go
  incubator/hnc/test/e2e/subnamespace_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L
