Repository kubernetes-sigs/multi-tenancy, pull requests merged in 2020-12, with the labels that each got.

#1294 [VC] syncer: support readiness gate condition
  incubator/virtualcluster/pkg/syncer/conversion/equality.go
  incubator/virtualcluster/pkg/syncer/conversion/equality_test.go
  incubator/virtualcluster/pkg/syncer/resources/pod/checker.go
  incubator/virtualcluster/pkg/syncer/resources/pod/dws.go
  incubator/virtualcluster/pkg/syncer/resources/pod/uws.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#1299 Exclude kube-node-lease from HNC
  incubator/hnc/internal/config/default_config.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1296 Don't delete the managedBy annotation
  incubator/hnc/internal/reconcilers/hierarchy_config.go
  incubator/hnc/test/conversion/conversion_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#1297 Remove v1alpha1
  incubator/hnc/Makefile
  incubator/hnc/api/v1alpha1/groupversion_info.go
  incubator/hnc/api/v1alpha1/hierarchy_types.go
  incubator/hnc/api/v1alpha1/hierarchy_types_conversion.go
  incubator/hnc/api/v1alpha1/hnc_config.go
  incubator/hnc/api/v1alpha1/hnc_config_conversion.go
  incubator/hnc/api/v1alpha1/subnamespace_anchor.go
  incubator/hnc/api/v1alpha1/subnamespace_anchor_conversion.go
  incubator/hnc/api/v1alpha1/zz_generated.deepcopy.go
  incubator/hnc/api/v1alpha2/hierarchy_types.go
  incubator/hnc/api/v1alpha2/hierarchy_types_conversion.go
  incubator/hnc/api/v1alpha2/hnc_config_conversion.go
  incubator/hnc/api/v1alpha2/subnamespace_anchor.go
  incubator/hnc/api/v1alpha2/subnamespace_anchor_conversion.go
  incubator/hnc/cmd/manager/main.go
  incubator/hnc/config/crd/bases/hnc.x-k8s.io_hierarchyconfigurations.yaml
  incubator/hnc/config/crd/bases/hnc.x-k8s.io_hncconfigurations.yaml
  incubator/hnc/config/crd/bases/hnc.x-k8s.io_subnamespaceanchors.yaml
  incubator/hnc/docs/user-guide/how-to.md
  incubator/hnc/hack/crd_patches/config_singleton_enum.yaml
  incubator/hnc/hack/crd_patches/hierarchy_singleton_enum.yaml
  incubator/hnc/hack/crd_patches/singleton-enum-patch.sh
  incubator/hnc/internal/reconcilers/anchor_test.go
  incubator/hnc/internal/reconcilers/crd_removeversion.go
  incubator/hnc/internal/reconcilers/hierarchy_config.go
  incubator/hnc/internal/reconcilers/hierarchy_config_test.go
  incubator/hnc/internal/reconcilers/setup.go
  incubator/hnc/internal/reconcilers/suite_test.go
  incubator/hnc/internal/validators/namespace_test.go
  incubator/hnc/internal/validators/setup.go
  incubator/hnc/pkg/testutils/testutils.go
  incubator/hnc/test/conversion/conversion_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#1298 Ensure consistent logging for all validators
  incubator/hnc/internal/validators/anchor.go
  incubator/hnc/internal/validators/hierarchy.go
  incubator/hnc/internal/validators/hncconfig.go
  incubator/hnc/internal/validators/namespace.go
  incubator/hnc/internal/validators/object.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#1300 Support unpropagated annotations
  incubator/hnc/api/v1alpha2/hierarchy_types.go
  incubator/hnc/api/v1alpha2/hnc_config.go
  incubator/hnc/api/v1alpha2/zz_generated.deepcopy.go
  incubator/hnc/config/crd/bases/hnc.x-k8s.io_hncconfigurations.yaml
  incubator/hnc/internal/config/default_config.go
  incubator/hnc/internal/config/gvk.go
  incubator/hnc/internal/forest/forest.go
  incubator/hnc/internal/reconcilers/hnc_config.go
  incubator/hnc/internal/reconcilers/hnc_config_test.go
  incubator/hnc/internal/reconcilers/object.go
  incubator/hnc/internal/reconcilers/test_helpers_test.go
  incubator/hnc/pkg/testutils/testutils.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1303 [VC] fix: vn-agent socket fd leak
  incubator/virtualcluster/pkg/vn-agent/server/route.go
  incubator/virtualcluster/pkg/vn-agent/server/server.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1302 Document HNC labels and annotations
  incubator/hnc/docs/user-guide/concepts.md
Labels: approved, cncf-cla: yes, lgtm, size/L

#1306 Increase memory limits and requests and update docs
  incubator/hnc/config/manager/manager.yaml
  incubator/hnc/docs/user-guide/faq.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#1304 Update performance test and add README
  incubator/hnc/scripts/performance/README.md
  incubator/hnc/scripts/performance/clean-up-topologies.sh
  incubator/hnc/scripts/performance/load-topology-full.sh
  incubator/hnc/scripts/performance/load-topology-skewer.sh
  incubator/hnc/scripts/performance/load-topology-wide.sh
  incubator/hnc/scripts/performance/start-controllers.sh
  incubator/hnc/scripts/performance/test.sh
Labels: approved, cncf-cla: yes, lgtm, size/L

#1308 Tool: map abstract to hierarchical namespaces
  incubator/hnc/tools/ans2hns/Dockerfile
  incubator/hnc/tools/ans2hns/README.md
  incubator/hnc/tools/ans2hns/examples/simple-1/README.md
  incubator/hnc/tools/ans2hns/examples/simple-1/namespaces/acme-org/eng/eng-sre-rolebinding.yaml
  incubator/hnc/tools/ans2hns/examples/simple-1/namespaces/acme-org/eng/np-allow-eng.yaml
  incubator/hnc/tools/ans2hns/examples/simple-1/namespaces/acme-org/eng/team-a/namespace.yaml
  incubator/hnc/tools/ans2hns/examples/simple-1/namespaces/acme-org/eng/team-a/team-a-rolebinding.yaml
  incubator/hnc/tools/ans2hns/examples/simple-1/namespaces/acme-org/eng/team-b/namespace.yaml
  incubator/hnc/tools/ans2hns/examples/simple-1/namespaces/acme-org/eng/team-b/team-b-rolebinding.yaml
  incubator/hnc/tools/ans2hns/examples/simple-1/namespaces/acme-org/np-deny.yaml
  incubator/hnc/tools/ans2hns/examples/simple-1/namespaces/acme-org/sre-rolebinding.yaml
  incubator/hnc/tools/ans2hns/examples/simple-1/namespaces/acme-org/team-c/namespace.yaml
  incubator/hnc/tools/ans2hns/examples/simple-1/namespaces/acme-org/team-c/team-c-rolebinding.yaml
  incubator/hnc/tools/ans2hns/go.mod
  incubator/hnc/tools/ans2hns/go.sum
  incubator/hnc/tools/ans2hns/main.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#1309 Generate event for exceptions
  incubator/hnc/api/v1alpha2/hierarchy_types.go
  incubator/hnc/internal/reconcilers/object.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1305 Create client for checking CRD deletion
  incubator/hnc/cmd/manager/main.go
  incubator/hnc/internal/reconcilers/anchor.go
  incubator/hnc/internal/reconcilers/hierarchy_config.go
  incubator/hnc/internal/reconcilers/hnc_config.go
  incubator/hnc/internal/reconcilers/setup.go
  incubator/hnc/internal/reconcilers/suite_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1310 Set unpropagated annotations via command line args
  incubator/hnc/api/v1alpha2/hnc_config.go
  incubator/hnc/api/v1alpha2/zz_generated.deepcopy.go
  incubator/hnc/cmd/manager/main.go
  incubator/hnc/config/crd/bases/hnc.x-k8s.io_hncconfigurations.yaml
  incubator/hnc/docs/user-guide/how-to.md
  incubator/hnc/internal/config/default_config.go
  incubator/hnc/internal/forest/forest.go
  incubator/hnc/internal/reconcilers/hnc_config.go
  incubator/hnc/internal/reconcilers/hnc_config_test.go
  incubator/hnc/internal/reconcilers/object.go
  incubator/hnc/internal/reconcilers/object_test.go
  incubator/hnc/internal/reconcilers/test_helpers_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1313 [VC] Revise README.md
  incubator/virtualcluster/README.md
Labels: approved, cncf-cla: yes, lgtm, size/L

#1314 Generate full manifest last
  incubator/hnc/Makefile
Labels: approved, cncf-cla: yes, lgtm, size/S

#1312 Add user documentation for exceptions
  incubator/hnc/docs/user-guide/concepts.md
  incubator/hnc/docs/user-guide/how-to.md
  incubator/hnc/docs/user-guide/quickstart.md
Labels: approved, cncf-cla: yes, lgtm, size/L

#1316 Validate HNC selector annotation
  incubator/hnc/internal/validators/object.go
  incubator/hnc/internal/validators/object_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1217 [MTB] Added image pull policy benchmark
  benchmarks/kubectl-mtb/test/benchmarks/require_always_pull_image/require_always_pull_image.go
  benchmarks/kubectl-mtb/test/utils/resources/pod/pod.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1251 [MTB] refactored code and added other ns flag
  benchmarks/kubectl-mtb/internal/kubectl-mtb/run.go
  benchmarks/kubectl-mtb/pkg/benchmark/benchmark.go
  benchmarks/kubectl-mtb/test/benchmarks/block_access_to_cluster_resources/README.md
  benchmarks/kubectl-mtb/test/benchmarks/block_access_to_cluster_resources/config.yaml
  benchmarks/kubectl-mtb/test/benchmarks/block_add_capabilities/README.md
  benchmarks/kubectl-mtb/test/benchmarks/block_add_capabilities/config.yaml
  benchmarks/kubectl-mtb/test/benchmarks/block_multitenant_resources/README.md
  benchmarks/kubectl-mtb/test/benchmarks/block_multitenant_resources/config.yaml
  benchmarks/kubectl-mtb/test/benchmarks/block_ns_quota/README.md
  benchmarks/kubectl-mtb/test/benchmarks/block_ns_quota/config.yaml
  benchmarks/kubectl-mtb/test/benchmarks/block_privilege_escalation/README.md
  benchmarks/kubectl-mtb/test/benchmarks/block_privilege_escalation/config.yaml
  benchmarks/kubectl-mtb/test/benchmarks/block_privileged_containers/README.md
  benchmarks/kubectl-mtb/test/benchmarks/block_privileged_containers/config.yaml
  benchmarks/kubectl-mtb/test/benchmarks/block_use_of_host_ipc/README.md
  benchmarks/kubectl-mtb/test/benchmarks/block_use_of_host_ipc/config.yaml
  benchmarks/kubectl-mtb/test/benchmarks/block_use_of_host_networking_and_ports/README.md
  benchmarks/kubectl-mtb/test/benchmarks/block_use_of_host_networking_and_ports/config.yaml
  benchmarks/kubectl-mtb/test/benchmarks/block_use_of_host_path/README.md
  benchmarks/kubectl-mtb/test/benchmarks/block_use_of_host_path/config.yaml
  benchmarks/kubectl-mtb/test/benchmarks/block_use_of_host_pid/README.md
  benchmarks/kubectl-mtb/test/benchmarks/block_use_of_host_pid/config.yaml
  benchmarks/kubectl-mtb/test/benchmarks/block_use_of_nodeport_services/README.md
  benchmarks/kubectl-mtb/test/benchmarks/block_use_of_nodeport_services/config.yaml
  benchmarks/kubectl-mtb/test/benchmarks/configure_ns_object_quota/README.md
  benchmarks/kubectl-mtb/test/benchmarks/configure_ns_object_quota/config.yaml
  benchmarks/kubectl-mtb/test/benchmarks/configure_ns_quotas/README.md
  benchmarks/kubectl-mtb/test/benchmarks/configure_ns_quotas/config.yaml
  benchmarks/kubectl-mtb/test/benchmarks/create_network_policies/README.md
  benchmarks/kubectl-mtb/test/benchmarks/create_network_policies/config.yaml
  benchmarks/kubectl-mtb/test/benchmarks/require_always_pull_image/README.md
  benchmarks/kubectl-mtb/test/benchmarks/require_always_pull_image/config.yaml
  benchmarks/kubectl-mtb/test/benchmarks/require_run_as_non_root_user/README.md
  benchmarks/kubectl-mtb/test/benchmarks/require_run_as_non_root_user/config.yaml
  benchmarks/kubectl-mtb/types/types.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1319 Update Krew docs for HNC v0.7
  incubator/hnc/hack/krew-kubectl-hns.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#1321 Update Krew docs for HNC v0.7
  incubator/hnc/hack/krew-kubectl-hns.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#1322 Update docs for v0.7
  incubator/hnc/README.md
  incubator/hnc/docs/user-guide/README.md
  incubator/hnc/docs/user-guide/concepts.md
  incubator/hnc/docs/user-guide/how-to.md
  incubator/hnc/docs/user-guide/quickstart.md
Labels: approved, cncf-cla: yes, lgtm, size/L

#1323 Update docs for v0.7 (cherrypick from master)
  incubator/hnc/README.md
  incubator/hnc/docs/user-guide/README.md
  incubator/hnc/docs/user-guide/concepts.md
  incubator/hnc/docs/user-guide/how-to.md
  incubator/hnc/docs/user-guide/quickstart.md
Labels: approved, cncf-cla: yes, lgtm, size/L

#1326 Update how-to to use v1alpha2
  incubator/hnc/docs/user-guide/how-to.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1330 VC: syncer: update node address upward to tenant
  incubator/virtualcluster/pkg/syncer/resources/node/controller.go
  incubator/virtualcluster/pkg/syncer/resources/node/uws.go
  incubator/virtualcluster/pkg/syncer/vnode/vnode.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1331 [VC] Add featuregates cmdline support in syncer
  incubator/virtualcluster/cmd/syncer/app/options/options.go
  incubator/virtualcluster/cmd/syncer/app/server.go
  incubator/virtualcluster/pkg/syncer/apis/config/types.go
  incubator/virtualcluster/pkg/syncer/util/feature.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1333 [VC] Add framework code for an experimental vc scheduler
  incubator/virtualcluster/experiment/.gitignore
  incubator/virtualcluster/experiment/Makefile
  incubator/virtualcluster/experiment/OWNERS
  incubator/virtualcluster/experiment/cmd/scheduler/app/config/config.go
  incubator/virtualcluster/experiment/cmd/scheduler/app/options/options.go
  incubator/virtualcluster/experiment/cmd/scheduler/app/server.go
  incubator/virtualcluster/experiment/cmd/scheduler/main.go
  incubator/virtualcluster/experiment/hack/lib/build.sh
  incubator/virtualcluster/experiment/hack/lib/docker-image.sh
  incubator/virtualcluster/experiment/hack/lib/init.sh
  incubator/virtualcluster/experiment/hack/lib/util.sh
  incubator/virtualcluster/experiment/hack/make-rules/build.sh
  incubator/virtualcluster/experiment/hack/make-rules/release-images.sh
  incubator/virtualcluster/experiment/pkg/scheduler/apis/config/types.go
  incubator/virtualcluster/experiment/pkg/scheduler/constants/constants.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#1332 [VC] Identify supercluster via configmap
  incubator/virtualcluster/cmd/syncer/app/config/config.go
  incubator/virtualcluster/cmd/syncer/app/options/options.go
  incubator/virtualcluster/cmd/syncer/app/server.go
  incubator/virtualcluster/pkg/syncer/conversion/helper.go
  incubator/virtualcluster/pkg/syncer/syncer.go
  incubator/virtualcluster/pkg/syncer/util/feature.go
Labels: approved, cncf-cla: yes, lgtm, size/M
