Repository kubernetes-sigs/multi-tenancy, pull requests merged in 2020-10, with the labels that each got.

#1163 Ensure all objects are reconciled at least once
  incubator/hnc/internal/reconcilers/hierarchy_config.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1164 Make e2e test repairs more robust
  incubator/hnc/pkg/testutils/testutils.go
  incubator/hnc/test/e2e/rolebinding_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1151 Don't delete subns if anchor has conflict (master)
  incubator/hnc/internal/reconcilers/anchor.go
  incubator/hnc/test/e2e/issues_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1157 Update "subnamespace-of" sub-namespace annotation
  incubator/hnc/api/v1alpha2/subnamespace_anchor.go
  incubator/hnc/config/crd/bases/hnc.x-k8s.io_subnamespaceanchors.yaml
  incubator/hnc/internal/reconcilers/hierarchy_config.go
  incubator/hnc/internal/reconcilers/hierarchy_config_test.go
  incubator/hnc/pkg/testutils/testutils.go
  incubator/hnc/test/conversion/conversion_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1161 Implement selector feature using 'select' annotation
  incubator/hnc/api/v1alpha2/hierarchy_types.go
  incubator/hnc/internal/forest/namespace.go
  incubator/hnc/internal/reconcilers/hierarchy_config.go
  incubator/hnc/internal/reconcilers/object.go
  incubator/hnc/internal/reconcilers/object_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1169 Add '--force' flag when switching from 'Ignore' to 'Propagate' mode
  incubator/hnc/internal/kubectl/configset.go
  incubator/hnc/test/e2e/kubectl_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#1171 Replace object conditions with events
  incubator/hnc/api/v1alpha2/hierarchy_types.go
  incubator/hnc/config/crd/bases/hnc.x-k8s.io_hierarchyconfigurations.yaml
  incubator/hnc/internal/reconcilers/hnc_config.go
  incubator/hnc/internal/reconcilers/object.go
  incubator/hnc/internal/reconcilers/object_test.go
  incubator/hnc/test/e2e/issues_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1174 Improve test failure messages; fix some tests
  incubator/hnc/pkg/testutils/testutils.go
  incubator/hnc/test/e2e/issues_test.go
  incubator/hnc/test/e2e/subnamespace_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1173 Switch to managed-by annotation
  incubator/hnc/api/v1alpha2/hierarchy_types.go
  incubator/hnc/api/v1alpha2/subnamespace_anchor.go
  incubator/hnc/internal/reconcilers/hierarchy_config.go
  incubator/hnc/pkg/testutils/testutils.go
  incubator/hnc/test/conversion/conversion_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1179 Improve HNC Config test diagnosis/stability
  incubator/hnc/internal/reconcilers/hierarchy_config_test.go
  incubator/hnc/internal/reconcilers/hnc_config_test.go
  incubator/hnc/internal/reconcilers/object_test.go
  incubator/hnc/internal/reconcilers/suite_test.go
  incubator/hnc/internal/reconcilers/test_helpers_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1182 VC: do idle queue gc in fair queue
  incubator/virtualcluster/pkg/syncer/fairqueue/fair.go
  incubator/virtualcluster/pkg/syncer/fairqueue/fair_test.go
  incubator/virtualcluster/pkg/syncer/fairqueue/fifo.go
  incubator/virtualcluster/pkg/syncer/fairqueue/option.go
  incubator/virtualcluster/pkg/syncer/mccontroller/mccontroller.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1176 Implement selector when using treeSelect annotation
  incubator/hnc/api/v1alpha2/hierarchy_types.go
  incubator/hnc/internal/reconcilers/object.go
  incubator/hnc/internal/reconcilers/object_test.go
  incubator/hnc/internal/reconcilers/test_helpers_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1191 Delete bad anchors and fix e2e tests
  incubator/hnc/internal/validators/anchor.go
  incubator/hnc/internal/validators/anchor_test.go
  incubator/hnc/test/e2e/delete_crd_test.go
  incubator/hnc/test/e2e/demo_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1189 VC: kubectl vc exec: switch workspace among virtualclusters
  incubator/virtualcluster/cmd/kubectl-vc/create.go
  incubator/virtualcluster/cmd/kubectl-vc/exec.go
  incubator/virtualcluster/cmd/kubectl-vc/root.go
  incubator/virtualcluster/cmd/kubectl-vc/util.go
  incubator/virtualcluster/go.mod
  incubator/virtualcluster/go.sum
Labels: approved, cncf-cla: yes, lgtm, size/L

#1190 Implement noneSelector and add test cases
  incubator/hnc/api/v1alpha2/hierarchy_types.go
  incubator/hnc/internal/reconcilers/object.go
  incubator/hnc/internal/reconcilers/object_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1192 Add events to `kubectl hns describe`
  incubator/hnc/internal/kubectl/describe.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1178 [MTB] update kyverno policy - disallow root user
  benchmarks/README.md
  benchmarks/kubectl-mtb/test/benchmarks/require_run_as_non_root_user/README.md
  benchmarks/kubectl-mtb/test/benchmarks/require_run_as_non_root_user/config.yaml
  benchmarks/kubectl-mtb/test/policies/kyverno/all_policies.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#1204 Update benchmark tests and definitions
  benchmarks/README.md
  benchmarks/documentation/definitions.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#1184 Update conditions to use standard schema
  incubator/hnc/api/v1alpha2/hierarchy_types.go
  incubator/hnc/api/v1alpha2/hnc_config.go
  incubator/hnc/api/v1alpha2/zz_generated.deepcopy.go
  incubator/hnc/config/crd/bases/hnc.x-k8s.io_hierarchyconfigurations.yaml
  incubator/hnc/config/crd/bases/hnc.x-k8s.io_hncconfigurations.yaml
  incubator/hnc/internal/forest/forest.go
  incubator/hnc/internal/forest/namespace.go
  incubator/hnc/internal/forest/namespaceconditions.go
  incubator/hnc/internal/foresttest/foresttest.go
  incubator/hnc/internal/kubectl/describe.go
  incubator/hnc/internal/kubectl/tree.go
  incubator/hnc/internal/reconcilers/hierarchy_config.go
  incubator/hnc/internal/reconcilers/hierarchy_config_test.go
  incubator/hnc/internal/reconcilers/hnc_config.go
  incubator/hnc/internal/reconcilers/object_test.go
  incubator/hnc/internal/stats/metrics.go
  incubator/hnc/test/conversion/conversion_test.go
  incubator/hnc/test/e2e/demo_test.go
  incubator/hnc/test/e2e/issues_test.go
  incubator/hnc/test/e2e/namespace_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#1194 Update HNCConfig API with GR for restmapper lookup
  incubator/hnc/api/v1alpha1/hnc_config_conversion.go
  incubator/hnc/api/v1alpha2/hnc_config.go
  incubator/hnc/config/crd/bases/hnc.x-k8s.io_hncconfigurations.yaml
  incubator/hnc/internal/config/default_config.go
  incubator/hnc/internal/kubectl/configdelete.go
  incubator/hnc/internal/kubectl/configdescribe.go
  incubator/hnc/internal/kubectl/configset.go
  incubator/hnc/internal/reconcilers/hnc_config.go
  incubator/hnc/internal/reconcilers/hnc_config_test.go
  incubator/hnc/internal/reconcilers/object_test.go
  incubator/hnc/internal/reconcilers/test_helpers_test.go
  incubator/hnc/internal/validators/hncconfig.go
  incubator/hnc/internal/validators/hncconfig_test.go
  incubator/hnc/test/conversion/conversion_test.go
  incubator/hnc/test/e2e/demo_test.go
  incubator/hnc/test/e2e/kubectl_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#1209 Update "inheritedFrom" label to "inherited-from"
  incubator/hnc/api/v1alpha2/hierarchy_types.go
  incubator/hnc/internal/reconcilers/test_helpers_test.go
  incubator/hnc/test/conversion/conversion_test.go
  incubator/hnc/test/e2e/demo_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1205 Add validator check for 'select' annotation
  incubator/hnc/internal/pkg/selectors/selectors.go
  incubator/hnc/internal/reconcilers/object.go
  incubator/hnc/internal/validators/object.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1215 Fix e2e tests after conditions updates
  incubator/hnc/pkg/testutils/testutils.go
  incubator/hnc/test/e2e/demo_test.go
  incubator/hnc/test/e2e/issues_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#1212 Update HNCConfig conditions into standard schema
  incubator/hnc/api/v1alpha2/hnc_config.go
  incubator/hnc/api/v1alpha2/zz_generated.deepcopy.go
  incubator/hnc/config/crd/bases/hnc.x-k8s.io_hncconfigurations.yaml
  incubator/hnc/internal/kubectl/configdescribe.go
  incubator/hnc/internal/reconcilers/hnc_config.go
  incubator/hnc/internal/reconcilers/hnc_config_test.go
  incubator/hnc/internal/validators/hncconfig.go
  incubator/hnc/test/conversion/conversion_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1219 Change HNC Config "types" to "resources"
  incubator/hnc/api/v1alpha1/hnc_config_conversion.go
  incubator/hnc/api/v1alpha2/hnc_config.go
  incubator/hnc/api/v1alpha2/zz_generated.deepcopy.go
  incubator/hnc/config/crd/bases/hnc.x-k8s.io_hncconfigurations.yaml
  incubator/hnc/internal/config/default_config.go
  incubator/hnc/internal/kubectl/config.go
  incubator/hnc/internal/kubectl/configdelete.go
  incubator/hnc/internal/kubectl/configdescribe.go
  incubator/hnc/internal/kubectl/configset.go
  incubator/hnc/internal/reconcilers/hnc_config.go
  incubator/hnc/internal/reconcilers/hnc_config_test.go
  incubator/hnc/internal/reconcilers/test_helpers_test.go
  incubator/hnc/internal/validators/hncconfig.go
  incubator/hnc/internal/validators/hncconfig_test.go
  incubator/hnc/test/conversion/conversion_test.go
  incubator/hnc/test/e2e/demo_test.go
  incubator/hnc/test/e2e/kubectl_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1221 Add test for invalid selector
  incubator/hnc/internal/validators/object_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#1230 Reenable test for #1155
  incubator/hnc/internal/forest/namespace.go
  incubator/hnc/internal/reconcilers/hierarchy_config.go
  incubator/hnc/test/e2e/issues_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#1223 Omit enforced RBAC resources in the HNCConfig spec
  incubator/hnc/api/v1alpha1/hnc_config_conversion.go
  incubator/hnc/api/v1alpha2/hnc_config.go
  incubator/hnc/config/crd/bases/hnc.x-k8s.io_hncconfigurations.yaml
  incubator/hnc/internal/config/default_config.go
  incubator/hnc/internal/reconcilers/hnc_config.go
  incubator/hnc/internal/reconcilers/hnc_config_test.go
  incubator/hnc/internal/reconcilers/test_helpers_test.go
  incubator/hnc/internal/validators/hncconfig.go
  incubator/hnc/internal/validators/hncconfig_test.go
  incubator/hnc/test/conversion/conversion_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1227 Convert HNCConfig namespaceConditions into conditions
  incubator/hnc/api/v1alpha2/hnc_config.go
  incubator/hnc/api/v1alpha2/zz_generated.deepcopy.go
  incubator/hnc/config/crd/bases/hnc.x-k8s.io_hncconfigurations.yaml
  incubator/hnc/internal/reconcilers/hnc_config.go
  incubator/hnc/test/conversion/conversion_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1216 Add validator check for `treeSelect`
  incubator/hnc/internal/pkg/selectors/selectors.go
  incubator/hnc/internal/validators/object.go
  incubator/hnc/internal/validators/object_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1224 Improve log messages
  incubator/hnc/internal/reconcilers/anchor.go
  incubator/hnc/internal/reconcilers/crd_removeversion.go
  incubator/hnc/internal/reconcilers/hierarchy_config.go
  incubator/hnc/internal/reconcilers/hnc_config.go
  incubator/hnc/internal/reconcilers/hnc_config_test.go
  incubator/hnc/internal/reconcilers/object.go
  incubator/hnc/internal/validators/anchor.go
  incubator/hnc/internal/validators/hierarchy.go
  incubator/hnc/internal/validators/hncconfig.go
  incubator/hnc/internal/validators/hncconfig_test.go
  incubator/hnc/internal/validators/namespace.go
  incubator/hnc/internal/validators/object.go
  incubator/hnc/test/e2e/delete_crd_test.go
  incubator/hnc/test/e2e/demo_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1185 add metric numbers of overwritten object
  incubator/hnc/internal/reconcilers/object.go
  incubator/hnc/internal/stats/metrics.go
  incubator/hnc/internal/stats/stats.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#1233 kubectl: enclose non-printing escape sequences with '\[' '\]'
  incubator/virtualcluster/cmd/kubectl-vc/exec.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1231 correct ipv6 domain name format
  incubator/virtualcluster/pkg/controller/kubeconfig/kubeconfig.go
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/S

#1228 Add quickstart to docs and remove HNC v0.4
  incubator/hnc/docs/user-guide/README.md
  incubator/hnc/docs/user-guide/how-to.md
  incubator/hnc/docs/user-guide/quickstart.md
  incubator/hnc/test/e2e/quickstart_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#1240 Update how-to.md for HNCConfig schema change
  incubator/hnc/docs/user-guide/how-to.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#1235 Add newline before subns footnote
  incubator/hnc/internal/kubectl/tree.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1236 Don't block object deletion in dying namespaces
  incubator/hnc/internal/forest/namespace.go
  incubator/hnc/internal/reconcilers/hierarchy_config.go
  incubator/hnc/internal/validators/object.go
  incubator/hnc/test/e2e/issues_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1225 Add validator for none selector
  incubator/hnc/internal/pkg/selectors/selectors.go
  incubator/hnc/internal/reconcilers/object.go
  incubator/hnc/internal/reconcilers/object_test.go
  incubator/hnc/internal/validators/object.go
  incubator/hnc/internal/validators/object_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1234 Cap the backoff for the object reconciler to 10s
  incubator/hnc/internal/reconcilers/object.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#1237 Add an FAQ with requirements and scaling info
  incubator/hnc/docs/user-guide/README.md
  incubator/hnc/docs/user-guide/faq.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#1239 HNC v0.6 docs: conditions and configuration
  incubator/hnc/docs/user-guide/concepts.md
  incubator/hnc/docs/user-guide/how-to.md
Labels: approved, cncf-cla: yes, lgtm, size/L

#1244 Fix netpol e2e test
  incubator/hnc/pkg/testutils/testutils.go
  incubator/hnc/test/e2e/quickstart_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1245 Fix netpol e2e test (cherry-pick to master)
  incubator/hnc/pkg/testutils/testutils.go
  incubator/hnc/test/e2e/quickstart_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1247 Update latest version to v0.6.0 (cherrypick)
  incubator/hnc/README.md
  incubator/hnc/docs/user-guide/how-to.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1246 Update latest version to v0.6.0
  incubator/hnc/README.md
  incubator/hnc/docs/user-guide/how-to.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1248 Update release and Krew instructions
  incubator/hnc/docs/releasing.md
  incubator/hnc/hack/krew-kubectl-hns.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#1242 Check conflict with the selectors
  incubator/hnc/internal/pkg/selectors/selectors.go
  incubator/hnc/internal/reconcilers/object.go
  incubator/hnc/internal/validators/object.go
  incubator/hnc/internal/validators/object_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M
