Repository kubernetes-sigs/multi-tenancy, pull requests merged in 2020-04, with the labels that each got.

#580 Use API objects to store conditions
  incubator/hnc/api/v1alpha1/hierarchy_types.go
  incubator/hnc/pkg/forest/forest.go
  incubator/hnc/pkg/reconcilers/hierarchy_config.go
  incubator/hnc/pkg/reconcilers/object.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#564 Implement HNS cascading delete
  incubator/hnc/api/v1alpha1/hierarchy_types.go
  incubator/hnc/hack/test-issue-501.sh
  incubator/hnc/pkg/forest/forest.go
  incubator/hnc/pkg/reconcilers/hierarchical_namespace.go
  incubator/hnc/pkg/reconcilers/hierarchical_namespace_test.go
  incubator/hnc/pkg/reconcilers/hierarchy_config.go
  incubator/hnc/pkg/reconcilers/setup.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#590 Capitalize help usage and make more clear
  incubator/hnc/pkg/kubectl/create.go
  incubator/hnc/pkg/kubectl/describe.go
  incubator/hnc/pkg/kubectl/set.go
  incubator/hnc/pkg/kubectl/tree.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#582 [incubator][VC] recreate a strict rbac role to syncer
  incubator/virtualcluster/config/setup/all_in_one.yaml
  incubator/virtualcluster/config/setup/all_in_one_aliyun.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#588 [Incubator][VC]Revise README.md
  incubator/virtualcluster/README.md
  incubator/virtualcluster/doc/demo.md
Labels: approved, cncf-cla: yes, lgtm, size/L

#591 [incubator][VC] drop pv uws delete event
  incubator/virtualcluster/pkg/syncer/resources/persistentvolume/uws.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#589 Address #281. Add comment to GVK object map in forest
  incubator/hnc/pkg/forest/forest.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#584 Compute NumSourceObjects in HNCConfiguration status
  incubator/hnc/api/v1alpha1/hnc_config.go
  incubator/hnc/api/v1alpha1/zz_generated.deepcopy.go
  incubator/hnc/config/crd/bases/hnc.x-k8s.io_hncconfigurations.yaml
  incubator/hnc/pkg/forest/forest.go
  incubator/hnc/pkg/reconcilers/hnc_config.go
  incubator/hnc/pkg/reconcilers/hnc_config_test.go
  incubator/hnc/pkg/reconcilers/object.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#585 Set object conditions atomically (#326)
  incubator/hnc/pkg/reconcilers/hierarchy_config.go
  incubator/hnc/pkg/reconcilers/object.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#600 [Incubator][VC] fixes for the first release
  incubator/virtualcluster/cmd/vcctl/subcmd/create.go
  incubator/virtualcluster/cmd/vcctl/util/util.go
  incubator/virtualcluster/cmd/vn-agent/app/options/options.go
  incubator/virtualcluster/config/setup/all_in_one.yaml
  incubator/virtualcluster/pkg/controller/virtualcluster/virtualcluster_controller.go
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/L

#598 [Incubator][VC]Add uid check for pv update and periodic check
  incubator/virtualcluster/config/setup/all_in_one.yaml
  incubator/virtualcluster/config/setup/all_in_one_aliyun.yaml
  incubator/virtualcluster/pkg/syncer/conversion/helper.go
  incubator/virtualcluster/pkg/syncer/resources/persistentvolume/checker.go
  incubator/virtualcluster/pkg/syncer/resources/persistentvolume/uws.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#593 HNC: Change condition codes to CamelCase strings.
  incubator/hnc/api/v1alpha1/hierarchy_types.go
  incubator/hnc/api/v1alpha1/hnc_config.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#603 Fix dereference of a possibly nil pointer
  incubator/hnc/pkg/validators/hierarchy.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#597 Flush obsolete conditions when tree changes (#328)
  incubator/hnc/hack/test-issue-328.sh
  incubator/hnc/pkg/forest/forest.go
  incubator/hnc/pkg/reconcilers/hierarchy_config.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#604 [Incubator][VC]Revise demo.md
  incubator/virtualcluster/README.md
  incubator/virtualcluster/doc/demo.md
Labels: approved, cncf-cla: yes, lgtm, size/L

#609 Rename kubectl-hierarchical_namespaces to kubectl-hns
  incubator/hnc/Makefile
  incubator/hnc/README.md
  incubator/hnc/cloudbuild.yaml
  incubator/hnc/hack/krew-hierarchical-namespaces.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#611 [Incubator][VC]Fix a few checker bugs.
  incubator/virtualcluster/pkg/syncer/resources/persistentvolume/checker.go
  incubator/virtualcluster/pkg/syncer/resources/pod/checker.go
  incubator/virtualcluster/pkg/syncer/resources/service/checker.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#615 Change the Use field of the root command to "kubectl-hns" for kubectl plugin
  incubator/hnc/pkg/kubectl/root.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#599 Clean up created objects in tests
  incubator/hnc/pkg/reconcilers/hnc_config_test.go
  incubator/hnc/pkg/reconcilers/object_test.go
  incubator/hnc/pkg/reconcilers/test_helpers_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#606 Add a kubectl command to delete the HNC configuration of a specific type
  incubator/hnc/pkg/kubectl/config.go
  incubator/hnc/pkg/kubectl/configdelete.go
  incubator/hnc/pkg/kubectl/root.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#618 [Incubator][VC]Restructure syncer namespace mock test
  incubator/virtualcluster/pkg/syncer/manager/manager.go
  incubator/virtualcluster/pkg/syncer/mccontroller/mccontroller.go
  incubator/virtualcluster/pkg/syncer/resources/namespace/controller.go
  incubator/virtualcluster/pkg/syncer/resources/namespace/dws.go
  incubator/virtualcluster/pkg/syncer/resources/namespace/dws_test.go
  incubator/virtualcluster/pkg/syncer/resources/register.go
  incubator/virtualcluster/pkg/syncer/util/test/runDWS.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#619 Update validators to respect excluded namespaces
  incubator/hnc/Makefile
  incubator/hnc/pkg/config/default_config.go
  incubator/hnc/pkg/reconcilers/hierarchical_namespace.go
  incubator/hnc/pkg/reconcilers/hierarchy_config.go
  incubator/hnc/pkg/reconcilers/object.go
  incubator/hnc/pkg/reconcilers/setup.go
  incubator/hnc/pkg/validators/hierarchical_namespace.go
  incubator/hnc/pkg/validators/hierarchy.go
  incubator/hnc/pkg/validators/hierarchy_test.go
  incubator/hnc/pkg/validators/object.go
  incubator/hnc/pkg/validators/object_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#625 Fewer log messages about finalizers
  incubator/hnc/pkg/reconcilers/hierarchy_config.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#628 Enhance README.md to show developer workflow
  incubator/hnc/README.md
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/S

#627 Fix tenantnamespace UTs
  tenant/pkg/controller/tenantnamespace/tenantnamespace_controller.go
  tenant/pkg/controller/tenantnamespace/tenantnamespace_controller_suite_test.go
  tenant/pkg/controller/tenantnamespace/tenantnamespace_controller_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#595 Add a kubectl command to set the HNC configuration of a specific type
  incubator/hnc/pkg/kubectl/config.go
  incubator/hnc/pkg/kubectl/configset.go
  incubator/hnc/pkg/validators/hierarchy.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#629 [Incubator][VC]Add service DWS mock tests
  incubator/virtualcluster/pkg/syncer/resources/service/controller.go
  incubator/virtualcluster/pkg/syncer/resources/service/dws_test.go
  incubator/virtualcluster/pkg/syncer/util/test/runDWS.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#626 Better flags, output and examples for hns-set
  incubator/hnc/pkg/kubectl/set.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#631 Break cyclical dependency when tenant CR is deleted
  tenant/pkg/controller/tenantnamespace/tenantnamespace_controller.go
  tenant/pkg/controller/tenantnamespace/tenantnamespace_controller_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#617 Test if obsolete CannotUpdate condition gets cleared in descendants
  incubator/hnc/hack/test-issue-605.sh
Labels: approved, cncf-cla: yes, lgtm, size/M

#624 Don't create HC in namespaces being deleted
  incubator/hnc/pkg/reconcilers/hierarchy_config.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#639 [incubator][VC] makefile: build unit-test coverage analyze report
  incubator/virtualcluster/.gitignore
  incubator/virtualcluster/Makefile
  incubator/virtualcluster/go.mod
  incubator/virtualcluster/go.sum
  incubator/virtualcluster/hack/install/install_ci_related.sh
Labels: approved, cncf-cla: yes, lgtm, size/M

#636 Fix a flaky test on changing namespace annotation
  incubator/hnc/pkg/reconcilers/hierarchical_namespace_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#638 Add HierarchicalNamespace Reconciler doc to README
  incubator/hnc/README.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#632 Flush obsolete conditions on descendants
  incubator/hnc/pkg/reconcilers/hierarchy_config.go
  incubator/hnc/pkg/reconcilers/object.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#637 Update condition code documentation
  incubator/hnc/api/v1alpha1/hierarchy_types.go
  incubator/hnc/config/crd/bases/hnc.x-k8s.io_hierarchyconfigurations.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#641 [Incubator][VC] Refactor manager.Controller interface
  incubator/virtualcluster/pkg/syncer/manager/manager.go
  incubator/virtualcluster/pkg/syncer/mccontroller/mccontroller.go
  incubator/virtualcluster/pkg/syncer/reconciler/reconciler.go
  incubator/virtualcluster/pkg/syncer/resources/configmap/controller.go
  incubator/virtualcluster/pkg/syncer/resources/endpoints/controller.go
  incubator/virtualcluster/pkg/syncer/resources/event/controller.go
  incubator/virtualcluster/pkg/syncer/resources/event/uws.go
  incubator/virtualcluster/pkg/syncer/resources/namespace/controller.go
  incubator/virtualcluster/pkg/syncer/resources/node/controller.go
  incubator/virtualcluster/pkg/syncer/resources/node/uws.go
  incubator/virtualcluster/pkg/syncer/resources/persistentvolume/controller.go
  incubator/virtualcluster/pkg/syncer/resources/persistentvolume/uws.go
  incubator/virtualcluster/pkg/syncer/resources/persistentvolumeclaim/controller.go
  incubator/virtualcluster/pkg/syncer/resources/pod/controller.go
  incubator/virtualcluster/pkg/syncer/resources/pod/uws.go
  incubator/virtualcluster/pkg/syncer/resources/secret/controller.go
  incubator/virtualcluster/pkg/syncer/resources/service/controller.go
  incubator/virtualcluster/pkg/syncer/resources/service/uws.go
  incubator/virtualcluster/pkg/syncer/resources/serviceaccount/controller.go
  incubator/virtualcluster/pkg/syncer/resources/storageclass/controller.go
  incubator/virtualcluster/pkg/syncer/resources/storageclass/uws.go
  incubator/virtualcluster/pkg/syncer/util/test/runDWS.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#633 [Incubator][VC] update the cluster status to ClusterError on fail
  incubator/virtualcluster/pkg/controller/util/kube/util.go
  incubator/virtualcluster/pkg/controller/virtualcluster/virtualcluster_controller.go
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/L

#642 [Incubator][VC]Introduce UpwardController to unify resource uws controller
  incubator/virtualcluster/pkg/syncer/mccontroller/mccontroller.go
  incubator/virtualcluster/pkg/syncer/reconciler/reconciler.go
  incubator/virtualcluster/pkg/syncer/resources/event/controller.go
  incubator/virtualcluster/pkg/syncer/resources/event/uws.go
  incubator/virtualcluster/pkg/syncer/resources/node/controller.go
  incubator/virtualcluster/pkg/syncer/resources/node/uws.go
  incubator/virtualcluster/pkg/syncer/resources/persistentvolume/checker.go
  incubator/virtualcluster/pkg/syncer/resources/persistentvolume/controller.go
  incubator/virtualcluster/pkg/syncer/resources/persistentvolume/uws.go
  incubator/virtualcluster/pkg/syncer/resources/pod/controller.go
  incubator/virtualcluster/pkg/syncer/resources/pod/uws.go
  incubator/virtualcluster/pkg/syncer/resources/service/controller.go
  incubator/virtualcluster/pkg/syncer/resources/service/uws.go
  incubator/virtualcluster/pkg/syncer/resources/storageclass/checker.go
  incubator/virtualcluster/pkg/syncer/resources/storageclass/controller.go
  incubator/virtualcluster/pkg/syncer/resources/storageclass/uws.go
  incubator/virtualcluster/pkg/syncer/uwcontroller/uwcontroller.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#644 [Incubator][VC] Ensure ClusterVNodePodMap is consistent in Pod checker.
  incubator/virtualcluster/pkg/syncer/resources/pod/checker.go
  incubator/virtualcluster/pkg/syncer/resources/pod/controller.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#645 [incubator][VC] add more test case to pod dws test
  incubator/virtualcluster/pkg/syncer/resources/pod/dws_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#646 [Incubator][VC]Introduce Patroller to abstract periodic checker
  incubator/virtualcluster/pkg/syncer/manager/manager.go
  incubator/virtualcluster/pkg/syncer/patrol/patroller.go
  incubator/virtualcluster/pkg/syncer/reconciler/reconciler.go
  incubator/virtualcluster/pkg/syncer/resources/configmap/checker.go
  incubator/virtualcluster/pkg/syncer/resources/configmap/controller.go
  incubator/virtualcluster/pkg/syncer/resources/endpoints/checker.go
  incubator/virtualcluster/pkg/syncer/resources/endpoints/controller.go
  incubator/virtualcluster/pkg/syncer/resources/event/controller.go
  incubator/virtualcluster/pkg/syncer/resources/namespace/checker.go
  incubator/virtualcluster/pkg/syncer/resources/namespace/controller.go
  incubator/virtualcluster/pkg/syncer/resources/node/controller.go
  incubator/virtualcluster/pkg/syncer/resources/persistentvolume/checker.go
  incubator/virtualcluster/pkg/syncer/resources/persistentvolume/controller.go
  incubator/virtualcluster/pkg/syncer/resources/persistentvolumeclaim/checker.go
  incubator/virtualcluster/pkg/syncer/resources/persistentvolumeclaim/controller.go
  incubator/virtualcluster/pkg/syncer/resources/pod/checker.go
  incubator/virtualcluster/pkg/syncer/resources/pod/controller.go
  incubator/virtualcluster/pkg/syncer/resources/secret/checker.go
  incubator/virtualcluster/pkg/syncer/resources/secret/controller.go
  incubator/virtualcluster/pkg/syncer/resources/service/checker.go
  incubator/virtualcluster/pkg/syncer/resources/service/controller.go
  incubator/virtualcluster/pkg/syncer/resources/serviceaccount/checker.go
  incubator/virtualcluster/pkg/syncer/resources/serviceaccount/controller.go
  incubator/virtualcluster/pkg/syncer/resources/storageclass/checker.go
  incubator/virtualcluster/pkg/syncer/resources/storageclass/controller.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#640 Update readme for v0.3.0-rc1
  incubator/hnc/README.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#649 [Incubator][VC]Add Pod patrol mock tests
  incubator/virtualcluster/pkg/syncer/conversion/equality.go
  incubator/virtualcluster/pkg/syncer/mccontroller/mccontroller.go
  incubator/virtualcluster/pkg/syncer/resources/pod/checker_test.go
  incubator/virtualcluster/pkg/syncer/resources/pod/dws.go
  incubator/virtualcluster/pkg/syncer/resources/pod/uws_test.go
  incubator/virtualcluster/pkg/syncer/util/test/runPatrol.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#648 [Incubator][VC] Check the existence of aliyun accesskey secret and VPC configmap
  incubator/virtualcluster/go.mod
  incubator/virtualcluster/go.sum
  incubator/virtualcluster/pkg/controller/util/kube/util.go
  incubator/virtualcluster/pkg/controller/virtualcluster/master_provisioner_aliyun.go
  incubator/virtualcluster/pkg/controller/virtualcluster/master_provisioner_native.go
  incubator/virtualcluster/pkg/controller/virtualcluster/virtualcluster_controller.go
  incubator/virtualcluster/pkg/controller/virtualcluster/virtualcluster_controller_test.go
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/M

#647 [incubator][VC] syncer: add health check port
  incubator/virtualcluster/cmd/syncer/app/server.go
  incubator/virtualcluster/config/setup/all_in_one.yaml
  incubator/virtualcluster/config/setup/all_in_one_aliyun.yaml
  incubator/virtualcluster/pkg/syncer/patrol/patroller.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#651 [incubator][VC] syncer: make leader election the default config
  incubator/virtualcluster/cmd/syncer/app/options/options.go
  incubator/virtualcluster/pkg/syncer/cluster/cluster.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#650 [incubator][VC] add more pod uws test case
  incubator/virtualcluster/pkg/syncer/resources/pod/checker.go
  incubator/virtualcluster/pkg/syncer/resources/pod/checker_test.go
  incubator/virtualcluster/pkg/syncer/resources/pod/dws_test.go
  incubator/virtualcluster/pkg/syncer/resources/pod/uws.go
  incubator/virtualcluster/pkg/syncer/resources/pod/uws_test.go
  incubator/virtualcluster/pkg/syncer/util/test/runDWS.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#652 [Incubator][VC]Add vNode GC mock tests
  incubator/virtualcluster/pkg/syncer/resources/pod/checker.go
  incubator/virtualcluster/pkg/syncer/resources/pod/checker_test.go
  incubator/virtualcluster/pkg/syncer/resources/pod/controller.go
  incubator/virtualcluster/pkg/syncer/resources/pod/uws_test.go
  incubator/virtualcluster/pkg/syncer/util/test/runDWS.go
  incubator/virtualcluster/pkg/syncer/util/test/runPatrol.go
  incubator/virtualcluster/pkg/syncer/util/test/runUWS.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#654 [incubator][VC] test: add pvc related unit test
  incubator/virtualcluster/pkg/syncer/resources/persistentvolumeclaim/checker_test.go
  incubator/virtualcluster/pkg/syncer/resources/persistentvolumeclaim/controller.go
  incubator/virtualcluster/pkg/syncer/resources/persistentvolumeclaim/dws_test.go
  incubator/virtualcluster/pkg/syncer/util/test/runDWS.go
  incubator/virtualcluster/pkg/syncer/util/test/runPatrol.go
  incubator/virtualcluster/pkg/syncer/util/test/runUWS.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#656 [incubator][VC] test: add pv related test
  incubator/virtualcluster/pkg/syncer/resources/persistentvolume/check_test.go
  incubator/virtualcluster/pkg/syncer/resources/persistentvolume/checker.go
  incubator/virtualcluster/pkg/syncer/resources/persistentvolume/controller.go
  incubator/virtualcluster/pkg/syncer/resources/persistentvolume/uws_test.go
  incubator/virtualcluster/pkg/syncer/util/test/runDWS.go
  incubator/virtualcluster/pkg/syncer/util/test/runPatrol.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#515 #397 added block other tenant resources test
  benchmarks/e2e/config/config.go
  benchmarks/e2e/tests/block_other_tenant_resources/block_other_tenant_resources.go
  benchmarks/e2e/tests/e2e.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#657 Update readme for hnc-v0.3.0
  incubator/hnc/README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#663 [incubator][VC] fix register compile error
  incubator/virtualcluster/pkg/syncer/resources/register.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#662 [Incubator][VC] allow user to specify a log file for vc-manager
  incubator/virtualcluster/cmd/manager/main.go
  incubator/virtualcluster/go.mod
  incubator/virtualcluster/pkg/controller/util/logr/util.go
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/M

#668 [Incubator][VC] fix syncer command line option bug
  incubator/virtualcluster/cmd/syncer/app/options/options.go
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/S

#669 [Incubator][VC]Implement super master namespace GC
  incubator/virtualcluster/cmd/syncer/app/config/config.go
  incubator/virtualcluster/cmd/syncer/app/options/options.go
  incubator/virtualcluster/cmd/syncer/app/server.go
  incubator/virtualcluster/pkg/controller/util/kube/util.go
  incubator/virtualcluster/pkg/controller/virtualcluster/master_provisioner_aliyun.go
  incubator/virtualcluster/pkg/controller/virtualcluster/master_provisioner_native.go
  incubator/virtualcluster/pkg/syncer/cluster/cluster.go
  incubator/virtualcluster/pkg/syncer/cluster/fake_cluster.go
  incubator/virtualcluster/pkg/syncer/constants/constants.go
  incubator/virtualcluster/pkg/syncer/conversion/helper.go
  incubator/virtualcluster/pkg/syncer/mccontroller/mccontroller.go
  incubator/virtualcluster/pkg/syncer/resources/namespace/checker.go
  incubator/virtualcluster/pkg/syncer/resources/namespace/checker_test.go
  incubator/virtualcluster/pkg/syncer/resources/namespace/controller.go
  incubator/virtualcluster/pkg/syncer/resources/namespace/dws.go
  incubator/virtualcluster/pkg/syncer/resources/namespace/dws_test.go
  incubator/virtualcluster/pkg/syncer/resources/register.go
  incubator/virtualcluster/pkg/syncer/syncer.go
  incubator/virtualcluster/pkg/syncer/util/test/runDWS.go
  incubator/virtualcluster/pkg/syncer/util/test/runPatrol.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#673 [incubator][VC] test: add secret test
  incubator/virtualcluster/pkg/syncer/conversion/helper.go
  incubator/virtualcluster/pkg/syncer/resources/persistentvolumeclaim/dws_test.go
  incubator/virtualcluster/pkg/syncer/resources/pod/dws_test.go
  incubator/virtualcluster/pkg/syncer/resources/register.go
  incubator/virtualcluster/pkg/syncer/resources/secret/controller.go
  incubator/virtualcluster/pkg/syncer/resources/secret/dws.go
  incubator/virtualcluster/pkg/syncer/resources/secret/dws_test.go
  incubator/virtualcluster/pkg/syncer/resources/service/dws_test.go
  incubator/virtualcluster/pkg/syncer/util/test/runDWS.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#672 [incubator][VC] syncer: DefaultOpaqueMetaDomains config for each vc
  incubator/virtualcluster/cmd/syncer/app/options/options.go
  incubator/virtualcluster/pkg/syncer/apis/config/types.go
  incubator/virtualcluster/pkg/syncer/conversion/equality.go
  incubator/virtualcluster/pkg/syncer/conversion/equality_test.go
  incubator/virtualcluster/pkg/syncer/resources/configmap/checker.go
  incubator/virtualcluster/pkg/syncer/resources/configmap/controller.go
  incubator/virtualcluster/pkg/syncer/resources/configmap/dws.go
  incubator/virtualcluster/pkg/syncer/resources/endpoints/checker.go
  incubator/virtualcluster/pkg/syncer/resources/endpoints/controller.go
  incubator/virtualcluster/pkg/syncer/resources/endpoints/dws.go
  incubator/virtualcluster/pkg/syncer/resources/persistentvolume/checker.go
  incubator/virtualcluster/pkg/syncer/resources/persistentvolume/controller.go
  incubator/virtualcluster/pkg/syncer/resources/persistentvolume/uws.go
  incubator/virtualcluster/pkg/syncer/resources/persistentvolumeclaim/checker.go
  incubator/virtualcluster/pkg/syncer/resources/persistentvolumeclaim/controller.go
  incubator/virtualcluster/pkg/syncer/resources/persistentvolumeclaim/dws.go
  incubator/virtualcluster/pkg/syncer/resources/pod/checker.go
  incubator/virtualcluster/pkg/syncer/resources/pod/dws.go
  incubator/virtualcluster/pkg/syncer/resources/pod/uws.go
  incubator/virtualcluster/pkg/syncer/resources/secret/checker.go
  incubator/virtualcluster/pkg/syncer/resources/secret/controller.go
  incubator/virtualcluster/pkg/syncer/resources/secret/dws.go
  incubator/virtualcluster/pkg/syncer/resources/service/checker.go
  incubator/virtualcluster/pkg/syncer/resources/service/controller.go
  incubator/virtualcluster/pkg/syncer/resources/service/dws.go
  incubator/virtualcluster/pkg/syncer/resources/storageclass/checker.go
  incubator/virtualcluster/pkg/syncer/resources/storageclass/controller.go
  incubator/virtualcluster/pkg/syncer/resources/storageclass/uws.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#670 [MTB] defined merging strategy for e2e.go
  benchmarks/.gitattributes
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#553 added test for [MTB-PL2-BC-OPS-3]
  benchmarks/e2e/tests/create_role_bindings/README.md
  benchmarks/e2e/tests/create_role_bindings/create_role_bindings.go
  benchmarks/e2e/tests/e2e.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#559 #259 added test for (MTB-PL1-BC-CPI-2)
  benchmarks/e2e/tests/block_multitenant_resources/README.md
  benchmarks/e2e/tests/block_multitenant_resources/block_multitenant_resources.go
  benchmarks/e2e/tests/e2e.go
  benchmarks/go.mod
  benchmarks/go.sum
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#572 Makes some corrects for test: block_privileged_contaiker
  benchmarks/e2e/tests/block_privileged_containers/block_privilege_container.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#658 Enables the path to the config to be passed in as a flag
  benchmarks/documentation/run.md
  benchmarks/e2e/config/config.go
  benchmarks/e2e/config/utils.go
  benchmarks/e2e/tests/e2e_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#661 Document the HNC User Guide
  incubator/hnc/README.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#674 [incubator][VC] add secret checker test
  incubator/virtualcluster/pkg/syncer/resources/secret/checker.go
  incubator/virtualcluster/pkg/syncer/resources/secret/checker_test.go
  incubator/virtualcluster/pkg/syncer/resources/secret/dws_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#675 [incubator][VC] add configmap test
  incubator/virtualcluster/pkg/syncer/resources/configmap/checker_test.go
  incubator/virtualcluster/pkg/syncer/resources/configmap/controller.go
  incubator/virtualcluster/pkg/syncer/resources/configmap/dws_test.go
  incubator/virtualcluster/pkg/syncer/resources/register.go
  incubator/virtualcluster/pkg/syncer/util/test/runDWS.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#677 [incubator][VC] add service account test
  incubator/virtualcluster/pkg/syncer/resources/register.go
  incubator/virtualcluster/pkg/syncer/resources/serviceaccount/checker_test.go
  incubator/virtualcluster/pkg/syncer/resources/serviceaccount/controller.go
  incubator/virtualcluster/pkg/syncer/resources/serviceaccount/dws.go
  incubator/virtualcluster/pkg/syncer/resources/serviceaccount/dws_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#678 [Incubator][VC] retry delete virtualcluster on failure
  incubator/virtualcluster/pkg/controller/virtualcluster/virtualcluster_controller.go
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/XS

#681 [incubator][VC] add service test
  incubator/virtualcluster/pkg/syncer/resources/service/checker_test.go
  incubator/virtualcluster/pkg/syncer/resources/service/dws_test.go
  incubator/virtualcluster/pkg/syncer/resources/service/uws_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L
