Repository kubernetes-sigs/multi-tenancy, pull requests merged in 2020-06, with the labels that each got.

#779 [HNC v0.4] Make Stackdriver optional and fix startup logs
  incubator/hnc/cmd/manager/main.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#781 [VC] add version to binary
  incubator/virtualcluster/cmd/syncer/app/server.go
  incubator/virtualcluster/cmd/vn-agent/app/server.go
  incubator/virtualcluster/hack/lib/build.sh
  incubator/virtualcluster/pkg/syncer/constants/constants.go
  incubator/virtualcluster/pkg/version/base.go
  incubator/virtualcluster/pkg/version/verflag/verflag.go
  incubator/virtualcluster/pkg/version/version.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#780 Make Stackdriver optional and fix startup logs
  incubator/hnc/cmd/manager/main.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#782 Update subnamespace tests
  incubator/hnc/hack/test-issue-501.sh
Labels: approved, cncf-cla: yes, lgtm, size/S

#786 [VC] add version option for vc-manager
  incubator/virtualcluster/cmd/manager/main.go
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/S

#676 #401 [MTB] Added test for privilege escalation
  benchmarks/e2e/tests/block_privilege_escalation/block_privilege_escalation.go
  benchmarks/e2e/tests/e2e.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#706 added test for block_nodeports
  benchmarks/e2e/tests/block_nodeports/block_nodeports.go
  benchmarks/e2e/tests/e2e.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#705 added Profile level selectors
  benchmarks/e2e/tests/block_add_capabilities/block_add_capabilities.go
  benchmarks/e2e/tests/block_host_ipc/block_host_ipc.go
  benchmarks/e2e/tests/configure_ns_object_quotas/configure_ns_object_quotas.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#614 Added test for [MTB-PL2-BC-OPS-4]
  benchmarks/e2e/tests/create_network_policies/README.md
  benchmarks/e2e/tests/create_network_policies/create_network_policies.go
  benchmarks/e2e/tests/e2e.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#659 Added test definition for [MTB-PL3-BC-CPV-1]
  benchmarks/documentation/categories.md
  benchmarks/e2e/tests/create_tenant_crds/README.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#787 Allow cascadingDelete if any ancestor allows
  incubator/hnc/internal/forest/namespace.go
  incubator/hnc/internal/validators/anchor_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#620 #404 added test for block use of bind mounts
  benchmarks/e2e/tests/block_bind_mounts/block_bind_mounts.go
  benchmarks/e2e/tests/e2e.go
  benchmarks/go.sum
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/M

#612 #403 added test for default deny network conn
  benchmarks/e2e/config/config.go
  benchmarks/e2e/tests/default_deny_net_conn/default_deny_net_conn.go
  benchmarks/e2e/tests/e2e.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#587 #406 added test for block_host_net_ports
  benchmarks/e2e/tests/block_host_net_ports/block_host_net_ports.go
  benchmarks/e2e/tests/e2e.go
  benchmarks/go.mod
  benchmarks/go.sum
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#570 Adds test for require_as_non_root
  benchmarks/e2e/tests/e2e.go
  benchmarks/e2e/tests/require_run_as_non_root/require_run_as_non_root.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#788 Make leaf subnamespace deletion easier
  incubator/hnc/hack/test-issue-716-full.sh
  incubator/hnc/hack/test-issue-716-leafsub.sh
  incubator/hnc/hack/test-issue-716-nonleafsub.sh
  incubator/hnc/internal/forest/namespacestructure.go
  incubator/hnc/internal/reconcilers/anchor.go
  incubator/hnc/internal/validators/anchor.go
  incubator/hnc/internal/validators/anchor_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#790 Enable object webhooks dynamically based on hncconfig
  incubator/hnc/config/webhook/manifests.yaml
  incubator/hnc/internal/forest/forest.go
  incubator/hnc/internal/validators/object.go
  incubator/hnc/internal/validators/object_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#795 Update docs for HNC v0.4
  incubator/hnc/README.md
  incubator/hnc/docs/user-guide/README.md
  incubator/hnc/docs/user-guide/how-to.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#794 [Kubectl-MTB] Added packages, cli structure and one benchmark
  benchmarks/kubectl-mtb/.gitignore
  benchmarks/kubectl-mtb/LICENSE
  benchmarks/kubectl-mtb/Makefile
  benchmarks/kubectl-mtb/cmd/kubectl/main.go
  benchmarks/kubectl-mtb/go.mod
  benchmarks/kubectl-mtb/go.sum
  benchmarks/kubectl-mtb/internal/kubectl/get.go
  benchmarks/kubectl-mtb/internal/kubectl/root.go
  benchmarks/kubectl-mtb/internal/kubectl/test.go
  benchmarks/kubectl-mtb/pkg/benchmark/benchmark.go
  benchmarks/kubectl-mtb/pkg/benchmark/benchmark_test.go
  benchmarks/kubectl-mtb/pkg/benchmark_suite/benchmarks_suite.go
  benchmarks/kubectl-mtb/pkg/benchmark_suite/benchmarks_suite_test.go
  benchmarks/kubectl-mtb/test/benchmarks/block_privileged_containers/block_privileged_containers.go
  benchmarks/kubectl-mtb/test/benchmarks/block_privileged_containers/blockprivilegedcontainers-packr.go
  benchmarks/kubectl-mtb/test/benchmarks/block_privileged_containers/config.yaml
  benchmarks/kubectl-mtb/test/benchmarks/block_privileged_containers/packrd/packed-packr.go
  benchmarks/kubectl-mtb/test/test.go
  benchmarks/kubectl-mtb/test/util/resources/pod/pod.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XXL

#801 [VC] Back populate super master clusterIP to tenant service object
  incubator/virtualcluster/pkg/syncer/cluster/cluster.go
  incubator/virtualcluster/pkg/syncer/constants/constants.go
  incubator/virtualcluster/pkg/syncer/resources/service/checker.go
  incubator/virtualcluster/pkg/syncer/resources/service/controller.go
  incubator/virtualcluster/pkg/syncer/resources/service/uws.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#804 [VC] Add document for tenant dns support
  incubator/virtualcluster/README.md
  incubator/virtualcluster/config/sampleswithspec/coredns.yaml
  incubator/virtualcluster/doc/tenant-dns.md
  incubator/virtualcluster/pkg/syncer/conversion/mutate.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#803 [VC] vc health checker, output in metric and event
  incubator/virtualcluster/cmd/syncer/app/config/config.go
  incubator/virtualcluster/cmd/syncer/app/options/options.go
  incubator/virtualcluster/cmd/syncer/app/server.go
  incubator/virtualcluster/config/setup/all_in_one.yaml
  incubator/virtualcluster/config/setup/all_in_one_aliyun.yaml
  incubator/virtualcluster/pkg/syncer/metrics/metrics.go
  incubator/virtualcluster/pkg/syncer/syncer.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#808 Imports for all Auth providers
  incubator/virtualcluster/cmd/vcctl/subcmd/create.go
  incubator/virtualcluster/cmd/vcctl/subcmd/delete.go
  incubator/virtualcluster/go.sum
Labels: approved, cncf-cla: yes, lgtm, size/XS

#807 [VC] update tenant master component to v1.16.x
  incubator/virtualcluster/config/sampleswithspec/clusterversion_v1_loadbalancer.yaml
  incubator/virtualcluster/config/sampleswithspec/clusterversion_v1_nodeport.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#805 [MTB] added error handler
  benchmarks/kubectl-mtb/go.mod
  benchmarks/kubectl-mtb/go.sum
  benchmarks/kubectl-mtb/internal/kubectl/get.go
  benchmarks/kubectl-mtb/internal/kubectl/root.go
  benchmarks/kubectl-mtb/internal/kubectl/test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#806 Added config files as static asset
  benchmarks/kubectl-mtb/Makefile
  benchmarks/kubectl-mtb/bundle/box/blob.go
  benchmarks/kubectl-mtb/bundle/box/box.go
  benchmarks/kubectl-mtb/bundle/box/generator.go
  benchmarks/kubectl-mtb/cmd/kubectl/main.go
  benchmarks/kubectl-mtb/go.sum
  benchmarks/kubectl-mtb/test/benchmarks/block_privileged_containers/block_privileged_containers.go
  benchmarks/kubectl-mtb/test/benchmarks/block_privileged_containers/blockprivilegedcontainers-packr.go
  benchmarks/kubectl-mtb/test/benchmarks/block_privileged_containers/packrd/packed-packr.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#809 Added README generator
  benchmarks/kubectl-mtb/Makefile
  benchmarks/kubectl-mtb/docs/main.go
  benchmarks/kubectl-mtb/go.mod
  benchmarks/kubectl-mtb/go.sum
  benchmarks/kubectl-mtb/pkg/benchmark/benchmark.go
  benchmarks/kubectl-mtb/test/benchmarks/block_privileged_containers/README.md
  benchmarks/kubectl-mtb/test/util/util.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#811 Lifecycle
  benchmarks/kubectl-mtb/go.sum
  benchmarks/kubectl-mtb/internal/kubectl/test.go
  benchmarks/kubectl-mtb/pkg/benchmark/benchmark.go
  benchmarks/kubectl-mtb/test/benchmarks/block_privileged_containers/block_privileged_containers.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#814 Fix one-char typo
  incubator/hnc/docs/user-guide/how-to.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#800 Spelling corrections
  docs/profiles/profile-soft-multitenancy-s1.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#799 Enable removing bad subns anchors safely
  incubator/hnc/hack/test-issue-797-leaf.sh
  incubator/hnc/hack/test-issue-797-non-leaf.sh
  incubator/hnc/internal/reconcilers/anchor.go
  incubator/hnc/internal/validators/anchor.go
  incubator/hnc/internal/validators/anchor_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#816 [VC] add generic metric for syncer operations
  incubator/virtualcluster/cmd/syncer/app/options/options.go
  incubator/virtualcluster/pkg/syncer/constants/constants.go
  incubator/virtualcluster/pkg/syncer/mccontroller/mccontroller.go
  incubator/virtualcluster/pkg/syncer/metrics/metrics.go
  incubator/virtualcluster/pkg/syncer/resources/node/uws.go
  incubator/virtualcluster/pkg/syncer/resources/pod/dws.go
  incubator/virtualcluster/pkg/syncer/resources/pod/uws.go
  incubator/virtualcluster/pkg/syncer/uwcontroller/uwcontroller.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#817 [VC] syncer: set timeout to client so request to apiserver don't hang forever
  incubator/virtualcluster/cmd/syncer/app/options/options.go
  incubator/virtualcluster/pkg/syncer/cluster/cluster.go
  incubator/virtualcluster/pkg/syncer/constants/constants.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#818 [VC] cleanup: unify checker metric collection
  incubator/virtualcluster/pkg/syncer/metrics/metrics.go
  incubator/virtualcluster/pkg/syncer/patrol/patroller.go
  incubator/virtualcluster/pkg/syncer/resources/configmap/checker.go
  incubator/virtualcluster/pkg/syncer/resources/configmap/controller.go
  incubator/virtualcluster/pkg/syncer/resources/endpoints/checker.go
  incubator/virtualcluster/pkg/syncer/resources/endpoints/controller.go
  incubator/virtualcluster/pkg/syncer/resources/namespace/checker.go
  incubator/virtualcluster/pkg/syncer/resources/namespace/controller.go
  incubator/virtualcluster/pkg/syncer/resources/persistentvolume/checker.go
  incubator/virtualcluster/pkg/syncer/resources/persistentvolume/controller.go
  incubator/virtualcluster/pkg/syncer/resources/persistentvolumeclaim/checker.go
  incubator/virtualcluster/pkg/syncer/resources/persistentvolumeclaim/controller.go
  incubator/virtualcluster/pkg/syncer/resources/pod/checker.go
  incubator/virtualcluster/pkg/syncer/resources/pod/controller.go
  incubator/virtualcluster/pkg/syncer/resources/secret/checker.go
  incubator/virtualcluster/pkg/syncer/resources/secret/controller.go
  incubator/virtualcluster/pkg/syncer/resources/service/checker.go
  incubator/virtualcluster/pkg/syncer/resources/service/controller.go
  incubator/virtualcluster/pkg/syncer/resources/serviceaccount/checker.go
  incubator/virtualcluster/pkg/syncer/resources/serviceaccount/controller.go
  incubator/virtualcluster/pkg/syncer/resources/storageclass/checker.go
  incubator/virtualcluster/pkg/syncer/resources/storageclass/controller.go
  incubator/virtualcluster/pkg/syncer/syncer.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#819 [VC] fix: respect vc status when reconciling
  incubator/virtualcluster/pkg/syncer/syncer.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#822 Set apiVersion and kind as required fields in hncconfig.spec.types
  incubator/hnc/api/v1alpha1/hnc_config.go
  incubator/hnc/config/crd/bases/hnc.x-k8s.io_hncconfigurations.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#738 [VC]: Update Controller Runtime to 2.9
  incubator/virtualcluster/Makefile
  incubator/virtualcluster/config/crds/tenancy.x-k8s.io_clusterversions.yaml
  incubator/virtualcluster/config/crds/tenancy.x-k8s.io_virtualclusters.yaml
  incubator/virtualcluster/config/crds/tenancy_v1alpha1_clusterversion.yaml
  incubator/virtualcluster/doc/demo.md
  incubator/virtualcluster/pkg/apis/apis.go
  incubator/virtualcluster/pkg/apis/tenancy/v1alpha1/clusterversion_types.go
  incubator/virtualcluster/pkg/apis/tenancy/v1alpha1/doc.go
  incubator/virtualcluster/pkg/apis/tenancy/v1alpha1/virtualcluster_types.go
  incubator/virtualcluster/pkg/apis/tenancy/v1alpha1/zz_generated.deepcopy.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#827 [VC] Remove tenant-controller from the demo, and use default NS
  incubator/virtualcluster/config/sampleswithspec/virtualcluster_1_loadbalancer.yaml
  incubator/virtualcluster/config/sampleswithspec/virtualcluster_1_nodeport.yaml
  incubator/virtualcluster/doc/demo.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#829 [VC] replace GOBIN with GOPATH/bin
  incubator/virtualcluster/Makefile
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/XS

#830 [VC]: Adding ClusterNamespace to VC.Status
  incubator/virtualcluster/config/crds/tenancy.x-k8s.io_virtualclusters.yaml
  incubator/virtualcluster/pkg/apis/tenancy/v1alpha1/virtualcluster_types.go
  incubator/virtualcluster/pkg/controller/util/kube/util.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#820 Update HC finalizer from hasOwnedNamespace to hasSubnamespace
  incubator/hnc/api/v1alpha1/hierarchy_types.go
  incubator/hnc/internal/reconcilers/hierarchy_config.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#832 Fix the error in e2e test due to the prefix change
  incubator/hnc/e2e/tests/namespace_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS
