Repository kubernetes-sigs/multi-tenancy, pull requests merged in 2020-05, with the labels that each got.

#682 [Incubator][VC] create a package for aliyun related functions
  incubator/virtualcluster/pkg/controller/add_clusterversion.go
  incubator/virtualcluster/pkg/controller/add_virtualcluster.go
  incubator/virtualcluster/pkg/controller/controller.go
  incubator/virtualcluster/pkg/controller/util/aliyun/util.go
  incubator/virtualcluster/pkg/controller/virtualcluster/master_provisioner_aliyun.go
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/XL

#684 [incubator][VC] add endpoints test
  incubator/virtualcluster/pkg/syncer/resources/endpoints/controller.go
  incubator/virtualcluster/pkg/syncer/resources/endpoints/dws_test.go
  incubator/virtualcluster/pkg/syncer/resources/register.go
  incubator/virtualcluster/pkg/syncer/util/test/runDWS.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#687 [Incubator][VC] Add a demo link in README.md
  incubator/virtualcluster/README.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#679 Integrate GK cert as the default internal cert
  incubator/hnc/Dockerfile
  incubator/hnc/Makefile
  incubator/hnc/cmd/manager/main.go
  incubator/hnc/config/default/kustomization.yaml
  incubator/hnc/config/default/manager_auth_proxy_patch.yaml
  incubator/hnc/config/internalcert/kustomization.yaml
  incubator/hnc/config/internalcert/manifests.yaml
  incubator/hnc/go.mod
  incubator/hnc/go.sum
  incubator/hnc/pkg/validators/setup.go
  incubator/hnc/third_party/open-policy-agent/gatekeeper/LICENSE
  incubator/hnc/third_party/open-policy-agent/gatekeeper/README.md
  incubator/hnc/third_party/open-policy-agent/gatekeeper/pkg/webhook/certs.go
  incubator/hnc/third_party/open-policy-agent/gatekeeper/pkg/webhook/certs_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#686 Reduce default cardinality of metrics
  incubator/hnc/cmd/manager/main.go
  incubator/hnc/pkg/stats/metrics.go
  incubator/hnc/pkg/stats/stats.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#689 Make HNC container run as non root
  incubator/hnc/Dockerfile
  incubator/hnc/cmd/manager/main.go
  incubator/hnc/config/default/manager_auth_proxy_patch.yaml
  incubator/hnc/config/default/manager_webhook_patch.yaml
  incubator/hnc/config/webhook/service.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#655 Block add capabilities
  benchmarks/config.yaml
  benchmarks/e2e/tests/block_add_capabilities/block_add_capabilities.go
  benchmarks/e2e/tests/e2e.go
  benchmarks/go.mod
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#697 Remove the term "self-serve (sub)namespace"
  incubator/hnc/api/v1alpha1/hierarchy_types.go
  incubator/hnc/pkg/kubectl/create.go
  incubator/hnc/pkg/kubectl/set.go
  incubator/hnc/pkg/reconcilers/hierarchical_namespace.go
  incubator/hnc/pkg/reconcilers/hierarchical_namespace_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#555 Adds block_host_ipc test
  benchmarks/e2e/tests/block_host_ipc/block_host_ipc.go
  benchmarks/e2e/tests/e2e.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#698 Change "owned" namespaces to subnamespaces
  incubator/hnc/api/v1alpha1/hierarchical_namespace.go
  incubator/hnc/api/v1alpha1/hierarchy_types.go
  incubator/hnc/config/crd/bases/hnc.x-k8s.io_hierarchyconfigurations.yaml
  incubator/hnc/hack/test-issue-501.sh
  incubator/hnc/pkg/forest/forest.go
  incubator/hnc/pkg/reconcilers/hierarchical_namespace.go
  incubator/hnc/pkg/reconcilers/hierarchical_namespace_test.go
  incubator/hnc/pkg/reconcilers/hierarchy_config.go
  incubator/hnc/pkg/validators/hierarchical_namespace_test.go
  incubator/hnc/pkg/validators/hierarchy.go
  incubator/hnc/pkg/validators/namespace.go
  incubator/hnc/pkg/validators/namespace_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#701 chore: fixed typos in README
  incubator/virtualcluster/README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#683 Added test for Configure namespace object limits
  benchmarks/e2e/tests/configure_ns_object_quotas/configure_ns_object_quotas.go
  benchmarks/e2e/tests/e2e.go
  benchmarks/go.mod
  benchmarks/go.sum
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#700 classified tests in PLs
  benchmarks/documentation/run.md
  benchmarks/e2e/tests/block_cluster_resources/block_cluster_resources.go
  benchmarks/e2e/tests/block_host_pid/block_host_pid.go
  benchmarks/e2e/tests/block_multitenant_resources/block_multitenant_resources.go
  benchmarks/e2e/tests/block_ns_quotas/block_ns_quotas.go
  benchmarks/e2e/tests/block_other_tenant_resources/block_other_tenant_resources.go
  benchmarks/e2e/tests/block_privileged_containers/block_privilege_container.go
  benchmarks/e2e/tests/configure_ns_quotas/configure_ns_quotas.go
  benchmarks/e2e/tests/create_role_bindings/create_role_bindings.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#704 Change subnamespace object to SubnamespaceAnchor
  incubator/hnc/README.md
  incubator/hnc/api/v1alpha1/hierarchical_namespace.go
  incubator/hnc/api/v1alpha1/hierarchy_types.go
  incubator/hnc/api/v1alpha1/subnamespace_anchor.go
  incubator/hnc/api/v1alpha1/zz_generated.deepcopy.go
  incubator/hnc/config/crd/bases/hnc.x-k8s.io_hierarchyconfigurations.yaml
  incubator/hnc/config/crd/bases/hnc.x-k8s.io_subnamespaceanchors.yaml
  incubator/hnc/config/crd/kustomization.yaml
  incubator/hnc/config/samples/hnc_v1_hns.yaml
  incubator/hnc/config/webhook/manifests.yaml
  incubator/hnc/pkg/forest/forest.go
  incubator/hnc/pkg/kubectl/create.go
  incubator/hnc/pkg/kubectl/describe.go
  incubator/hnc/pkg/kubectl/root.go
  incubator/hnc/pkg/reconcilers/anchor.go
  incubator/hnc/pkg/reconcilers/anchor_test.go
  incubator/hnc/pkg/reconcilers/hierarchical_namespace_test.go
  incubator/hnc/pkg/reconcilers/hierarchy_config.go
  incubator/hnc/pkg/reconcilers/setup.go
  incubator/hnc/pkg/validators/anchor.go
  incubator/hnc/pkg/validators/anchor_test.go
  incubator/hnc/pkg/validators/namespace.go
  incubator/hnc/pkg/validators/setup.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#702 More flexible way to create and test forests
  incubator/hnc/pkg/foresttest/foresttest.go
  incubator/hnc/pkg/validators/anchor_test.go
  incubator/hnc/pkg/validators/hierarchy_test.go
  incubator/hnc/pkg/validators/namespace_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#708 [incubator][VC] add event test
  incubator/virtualcluster/pkg/syncer/resources/endpoints/checker_test.go
  incubator/virtualcluster/pkg/syncer/resources/endpoints/dws_test.go
  incubator/virtualcluster/pkg/syncer/resources/event/controller.go
  incubator/virtualcluster/pkg/syncer/resources/event/uws_test.go
  incubator/virtualcluster/pkg/syncer/util/test/runDWS.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#709 [VC]: Fixing up spelling & grammar in the readme
  incubator/virtualcluster/README.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#712 Go mod cleanup to fix canonical SHAs
  incubator/virtualcluster/go.mod
  incubator/virtualcluster/go.sum
Labels: approved, cncf-cla: yes, lgtm, size/M

#710 Fix a test flake
  incubator/hnc/pkg/reconcilers/anchor_test.go
  incubator/hnc/pkg/reconcilers/hierarchy_config_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#703 More robust server checks
  incubator/hnc/pkg/forest/forest.go
  incubator/hnc/pkg/reconcilers/hierarchy_config.go
  incubator/hnc/pkg/reconcilers/object.go
  incubator/hnc/pkg/validators/hierarchy.go
  incubator/hnc/pkg/validators/hierarchy_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#699 Stable removal of obsolete conditions
  incubator/hnc/api/v1alpha1/hierarchy_types.go
  incubator/hnc/pkg/forest/forest.go
  incubator/hnc/pkg/reconcilers/hierarchy_config.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#720 [incubator][VC] add max retry rate about dws
  incubator/virtualcluster/go.mod
  incubator/virtualcluster/go.sum
  incubator/virtualcluster/pkg/syncer/constants/constants.go
  incubator/virtualcluster/pkg/syncer/mccontroller/mccontroller.go
  incubator/virtualcluster/pkg/syncer/uwcontroller/uwcontroller.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#721 [incubator][VC] fix: container diff if webhook add to super pod
  incubator/virtualcluster/pkg/syncer/conversion/equality.go
  incubator/virtualcluster/pkg/syncer/conversion/equality_test.go
  incubator/virtualcluster/pkg/syncer/resources/pod/dws_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#719 Better handle namespace cycles
  incubator/hnc/api/v1alpha1/hierarchy_types.go
  incubator/hnc/config/crd/bases/hnc.x-k8s.io_hierarchyconfigurations.yaml
  incubator/hnc/pkg/forest/forest.go
  incubator/hnc/pkg/forest/forest_test.go
  incubator/hnc/pkg/foresttest/foresttest.go
  incubator/hnc/pkg/kubectl/tree.go
  incubator/hnc/pkg/reconcilers/hierarchy_config.go
  incubator/hnc/pkg/reconcilers/hierarchy_config_test.go
  incubator/hnc/pkg/validators/hierarchy.go
  incubator/hnc/pkg/validators/hierarchy_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#726 [VC]: Adding container name in the logs vn-agent passthrough
  incubator/virtualcluster/pkg/vn-agent/server/server_test.go
  incubator/virtualcluster/pkg/vn-agent/server/translate.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#723 Move user guide to markdown
  incubator/hnc/README.md
  incubator/hnc/docs/links.md
  incubator/hnc/docs/metrics/stackdriver-gke.md
  incubator/hnc/docs/user-guide/README.md
  incubator/hnc/docs/user-guide/best-practices.md
  incubator/hnc/docs/user-guide/concepts.md
  incubator/hnc/docs/user-guide/how-to.md
Labels: approved, cncf-cla: yes, lgtm, size/XL

#724 Update tree labels even with critical conditions
  incubator/hnc/pkg/reconcilers/hierarchy_config.go
  incubator/hnc/pkg/reconcilers/hierarchy_config_test.go
  incubator/hnc/pkg/reconcilers/test_helpers_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#732 Add Apache license from root to HNC
  incubator/hnc/LICENSE
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/L

#725 Break up forest.go
  incubator/hnc/pkg/forest/forest.go
  incubator/hnc/pkg/forest/namespace.go
  incubator/hnc/pkg/forest/namespaceconditions.go
  incubator/hnc/pkg/forest/namespaceobjects.go
  incubator/hnc/pkg/forest/namespacestructure.go
  incubator/hnc/pkg/forest/namespacestructure_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#733 Stop using the contraction 'K8s'
  incubator/hnc/docs/user-guide/concepts.md
  incubator/hnc/docs/user-guide/how-to.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#735 Better formatting for definitions
  incubator/hnc/docs/user-guide/concepts.md
Labels: approved, cncf-cla: yes, lgtm, size/L

#729 [VC]: Switch to distroless image
  incubator/virtualcluster/hack/lib/docker-image.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#737 Fix typo
  incubator/hnc/docs/user-guide/README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#731 Add footnotes
  incubator/hnc/docs/user-guide/README.md
  incubator/hnc/docs/user-guide/concepts.md
  incubator/hnc/docs/user-guide/how-to.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#734 Change all local golang imports to sigs.k8s.io
  incubator/hnc/cmd/kubectl/main.go
  incubator/hnc/cmd/manager/main.go
  incubator/hnc/go.mod
  incubator/hnc/pkg/config/default_config.go
  incubator/hnc/pkg/forest/forest.go
  incubator/hnc/pkg/forest/namespace.go
  incubator/hnc/pkg/forest/namespaceconditions.go
  incubator/hnc/pkg/foresttest/foresttest.go
  incubator/hnc/pkg/kubectl/configdelete.go
  incubator/hnc/pkg/kubectl/configdescribe.go
  incubator/hnc/pkg/kubectl/configset.go
  incubator/hnc/pkg/kubectl/root.go
  incubator/hnc/pkg/kubectl/set.go
  incubator/hnc/pkg/kubectl/tree.go
  incubator/hnc/pkg/object/object.go
  incubator/hnc/pkg/object/object_test.go
  incubator/hnc/pkg/reconcilers/anchor.go
  incubator/hnc/pkg/reconcilers/anchor_test.go
  incubator/hnc/pkg/reconcilers/hierarchy_config.go
  incubator/hnc/pkg/reconcilers/hierarchy_config_test.go
  incubator/hnc/pkg/reconcilers/hnc_config.go
  incubator/hnc/pkg/reconcilers/hnc_config_test.go
  incubator/hnc/pkg/reconcilers/object.go
  incubator/hnc/pkg/reconcilers/object_test.go
  incubator/hnc/pkg/reconcilers/setup.go
  incubator/hnc/pkg/reconcilers/suite_test.go
  incubator/hnc/pkg/reconcilers/test_helpers_test.go
  incubator/hnc/pkg/validators/anchor.go
  incubator/hnc/pkg/validators/anchor_test.go
  incubator/hnc/pkg/validators/hierarchy.go
  incubator/hnc/pkg/validators/hierarchy_test.go
  incubator/hnc/pkg/validators/hncconfig.go
  incubator/hnc/pkg/validators/hncconfig_test.go
  incubator/hnc/pkg/validators/namespace.go
  incubator/hnc/pkg/validators/namespace_test.go
  incubator/hnc/pkg/validators/object.go
  incubator/hnc/pkg/validators/object_test.go
  incubator/hnc/pkg/validators/setup.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#740 Fix the namespace validating admission name
  incubator/hnc/config/webhook/manifests.yaml
  incubator/hnc/pkg/validators/namespace.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#739 Prevent anyone from importing HNC internals
  incubator/hnc/Dockerfile
  incubator/hnc/Makefile
  incubator/hnc/cmd/kubectl/main.go
  incubator/hnc/cmd/manager/main.go
  incubator/hnc/internal/config/default_config.go
  incubator/hnc/internal/config/gvk.go
  incubator/hnc/internal/forest/forest.go
  incubator/hnc/internal/forest/namespace.go
  incubator/hnc/internal/forest/namespaceconditions.go
  incubator/hnc/internal/forest/namespaceobjects.go
  incubator/hnc/internal/forest/namespacestructure.go
  incubator/hnc/internal/forest/namespacestructure_test.go
  incubator/hnc/internal/foresttest/foresttest.go
  incubator/hnc/internal/kubectl/config.go
  incubator/hnc/internal/kubectl/configdelete.go
  incubator/hnc/internal/kubectl/configdescribe.go
  incubator/hnc/internal/kubectl/configset.go
  incubator/hnc/internal/kubectl/create.go
  incubator/hnc/internal/kubectl/describe.go
  incubator/hnc/internal/kubectl/root.go
  incubator/hnc/internal/kubectl/set.go
  incubator/hnc/internal/kubectl/tree.go
  incubator/hnc/internal/metadata/metav1.go
  incubator/hnc/internal/object/object.go
  incubator/hnc/internal/object/object_test.go
  incubator/hnc/internal/reconcilers/anchor.go
  incubator/hnc/internal/reconcilers/anchor_test.go
  incubator/hnc/internal/reconcilers/hierarchy_config.go
  incubator/hnc/internal/reconcilers/hierarchy_config_test.go
  incubator/hnc/internal/reconcilers/hnc_config.go
  incubator/hnc/internal/reconcilers/hnc_config_test.go
  incubator/hnc/internal/reconcilers/object.go
  incubator/hnc/internal/reconcilers/object_test.go
  incubator/hnc/internal/reconcilers/setup.go
  incubator/hnc/internal/reconcilers/suite_test.go
  incubator/hnc/internal/reconcilers/test_helpers_test.go
  incubator/hnc/internal/stats/counter.go
  incubator/hnc/internal/stats/metrics.go
  incubator/hnc/internal/stats/stats.go
  incubator/hnc/internal/validators/anchor.go
  incubator/hnc/internal/validators/anchor_test.go
  incubator/hnc/internal/validators/hierarchy.go
  incubator/hnc/internal/validators/hierarchy_test.go
  incubator/hnc/internal/validators/hncconfig.go
  incubator/hnc/internal/validators/hncconfig_test.go
  incubator/hnc/internal/validators/namespace.go
  incubator/hnc/internal/validators/namespace_test.go
  incubator/hnc/internal/validators/object.go
  incubator/hnc/internal/validators/object_test.go
  incubator/hnc/internal/validators/setup.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#743 Simpler HNCConfig reconciler triggers
  incubator/hnc/internal/forest/forest.go
  incubator/hnc/internal/reconcilers/hierarchy_config.go
  incubator/hnc/internal/reconcilers/hnc_config.go
  incubator/hnc/internal/reconcilers/object.go
  incubator/hnc/internal/reconcilers/setup.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#745 [VC] add node test
  incubator/virtualcluster/pkg/syncer/resources/event/uws_test.go
  incubator/virtualcluster/pkg/syncer/resources/node/controller.go
  incubator/virtualcluster/pkg/syncer/resources/node/uws.go
  incubator/virtualcluster/pkg/syncer/resources/node/uws_test.go
  incubator/virtualcluster/pkg/syncer/resources/persistentvolume/uws_test.go
  incubator/virtualcluster/pkg/syncer/resources/pod/uws_test.go
  incubator/virtualcluster/pkg/syncer/resources/register.go
  incubator/virtualcluster/pkg/syncer/resources/service/uws_test.go
  incubator/virtualcluster/pkg/syncer/util/test/runUWS.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#751 [VC] add request queue test
  incubator/virtualcluster/pkg/syncer/handler/enqueue_object_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#750 [VC] add storageclass test
  incubator/virtualcluster/pkg/syncer/manager/manager.go
  incubator/virtualcluster/pkg/syncer/resources/configmap/checker_test.go
  incubator/virtualcluster/pkg/syncer/resources/configmap/controller.go
  incubator/virtualcluster/pkg/syncer/resources/endpoints/checker_test.go
  incubator/virtualcluster/pkg/syncer/resources/endpoints/controller.go
  incubator/virtualcluster/pkg/syncer/resources/event/controller.go
  incubator/virtualcluster/pkg/syncer/resources/namespace/checker_test.go
  incubator/virtualcluster/pkg/syncer/resources/namespace/controller.go
  incubator/virtualcluster/pkg/syncer/resources/namespace/dws_test.go
  incubator/virtualcluster/pkg/syncer/resources/node/controller.go
  incubator/virtualcluster/pkg/syncer/resources/persistentvolume/checker_test.go
  incubator/virtualcluster/pkg/syncer/resources/persistentvolume/controller.go
  incubator/virtualcluster/pkg/syncer/resources/persistentvolumeclaim/checker_test.go
  incubator/virtualcluster/pkg/syncer/resources/persistentvolumeclaim/controller.go
  incubator/virtualcluster/pkg/syncer/resources/pod/checker_test.go
  incubator/virtualcluster/pkg/syncer/resources/pod/controller.go
  incubator/virtualcluster/pkg/syncer/resources/register.go
  incubator/virtualcluster/pkg/syncer/resources/secret/checker_test.go
  incubator/virtualcluster/pkg/syncer/resources/secret/controller.go
  incubator/virtualcluster/pkg/syncer/resources/service/checker_test.go
  incubator/virtualcluster/pkg/syncer/resources/service/controller.go
  incubator/virtualcluster/pkg/syncer/resources/serviceaccount/checker_test.go
  incubator/virtualcluster/pkg/syncer/resources/serviceaccount/controller.go
  incubator/virtualcluster/pkg/syncer/resources/storageclass/checker_test.go
  incubator/virtualcluster/pkg/syncer/resources/storageclass/controller.go
  incubator/virtualcluster/pkg/syncer/resources/storageclass/uws_test.go
  incubator/virtualcluster/pkg/syncer/util/test/runDWS.go
  incubator/virtualcluster/pkg/syncer/util/test/runPatrol.go
  incubator/virtualcluster/pkg/syncer/util/test/runUWS.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#742 enable workqueue prometheus metrics
  incubator/virtualcluster/pkg/syncer/mccontroller/mccontroller.go
  incubator/virtualcluster/pkg/syncer/metrics/metrics.go
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/XS

#754 Don't add empty AffectedObject entries
  incubator/hnc/internal/forest/namespaceconditions.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#747 Allow namespace deletion in K8s 1.14
  incubator/hnc/internal/validators/anchor.go
  incubator/hnc/internal/validators/namespace.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#744 Add namespace conditions to HNCConfig and metrics
  incubator/hnc/README.md
  incubator/hnc/api/v1alpha1/hierarchy_types.go
  incubator/hnc/api/v1alpha1/hnc_config.go
  incubator/hnc/api/v1alpha1/zz_generated.deepcopy.go
  incubator/hnc/config/crd/bases/hnc.x-k8s.io_hncconfigurations.yaml
  incubator/hnc/docs/user-guide/concepts.md
  incubator/hnc/internal/reconcilers/hierarchy_config.go
  incubator/hnc/internal/reconcilers/hnc_config.go
  incubator/hnc/internal/stats/metrics.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#756 [VC] Fix a nulltpr crash
  incubator/virtualcluster/pkg/syncer/resources/node/controller.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#757 [VC] unify reconciler interface
  incubator/virtualcluster/pkg/syncer/manager/manager.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#758 [VC] support service type event
  incubator/virtualcluster/pkg/syncer/conversion/helper.go
  incubator/virtualcluster/pkg/syncer/resources/event/controller.go
  incubator/virtualcluster/pkg/syncer/resources/event/uws.go
  incubator/virtualcluster/pkg/syncer/resources/event/uws_test.go
  incubator/virtualcluster/pkg/syncer/resources/pod/dws.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#755 Consolidate docs into the user guide
  incubator/hnc/README.md
  incubator/hnc/docs/metrics/stackdriver-gke.md
  incubator/hnc/docs/user-guide/how-to.md
Labels: approved, cncf-cla: yes, lgtm, size/L

#759 [VC] Remove the use of "Virtualcluster" term in code
  incubator/virtualcluster/cmd/vcctl/subcmd/create.go
  incubator/virtualcluster/pkg/controller/add_virtualcluster.go
  incubator/virtualcluster/pkg/controller/clusterversion/clusterversion_controller.go
  incubator/virtualcluster/pkg/controller/controller.go
  incubator/virtualcluster/pkg/controller/vcmanager/vcmanager.go
  incubator/virtualcluster/pkg/controller/virtualcluster/virtualcluster_controller.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#760 Add best practices for HNC health
  incubator/hnc/docs/user-guide/best-practices.md
  incubator/hnc/docs/user-guide/how-to.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#766 Allow recreation of missing subns anchors
  incubator/hnc/internal/validators/anchor.go
  incubator/hnc/internal/validators/anchor_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#762 Don't delete subnses with the Anchor CRD
  incubator/hnc/hack/test-delete-anchor-crd.sh
  incubator/hnc/hack/test-issue-501.sh
  incubator/hnc/internal/reconcilers/anchor.go
  incubator/hnc/internal/reconcilers/hnc_config.go
  incubator/hnc/internal/reconcilers/hnc_config_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#767 Document uninstallation, backup and restore
  incubator/hnc/docs/user-guide/best-practices.md
  incubator/hnc/docs/user-guide/how-to.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#764 Reconcile external namespaces and update tree labels
  incubator/hnc/api/v1alpha1/hierarchy_types.go
  incubator/hnc/internal/forest/namespace.go
  incubator/hnc/internal/reconcilers/hierarchy_config.go
  incubator/hnc/internal/reconcilers/hierarchy_config_test.go
  incubator/hnc/internal/reconcilers/test_helpers_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#773 Disable leader election
  incubator/hnc/config/default/manager_auth_proxy_patch.yaml
  incubator/hnc/config/manager/manager.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#776 Let HNC propagate builtin admin rolebindings
  incubator/hnc/config/rbac/role.yaml
  incubator/hnc/hack/test-issue-772.sh
  incubator/hnc/internal/reconcilers/object.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#774 Removes CannotUpdate when source object deleted
  incubator/hnc/api/v1alpha1/hierarchy_types.go
  incubator/hnc/hack/test-issue-771.sh
  incubator/hnc/internal/reconcilers/object.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#775 Don't unpropagate objects after CRDs are deleted
  incubator/hnc/hack/test-delete-hc-crd.sh
  incubator/hnc/internal/reconcilers/hierarchy_config.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#769 Update admission controllers for external hierarchy
  incubator/hnc/config/webhook/manifests.yaml
  incubator/hnc/internal/forest/namespace.go
  incubator/hnc/internal/reconcilers/hierarchy_config.go
  incubator/hnc/internal/validators/hierarchy.go
  incubator/hnc/internal/validators/hierarchy_test.go
  incubator/hnc/internal/validators/namespace.go
  incubator/hnc/internal/validators/namespace_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L
