Repository kubernetes-sigs/multi-tenancy, pull requests merged in 2020-08, with the labels that each got.

#985 [VC] fix map data race in node uws
  incubator/virtualcluster/pkg/syncer/resources/node/uws.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#982 Update docs for HNC v0.5.1
  incubator/hnc/README.md
  incubator/hnc/docs/user-guide/how-to.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#991 [VC] Feature: implement the webhook framework for VC
  incubator/virtualcluster/cmd/manager/main.go
  incubator/virtualcluster/config/sampleswithspec/clusterversion_v1_nodeport.yaml
  incubator/virtualcluster/config/setup/all_in_one.yaml
  incubator/virtualcluster/go.sum
  incubator/virtualcluster/pkg/apis/tenancy/v1alpha1/virtualcluster_webhook.go
  incubator/virtualcluster/pkg/controller/constants/constants.go
  incubator/virtualcluster/pkg/webhook/add_virtualcluster.go
  incubator/virtualcluster/pkg/webhook/virtualcluster/virtualcluster_webhook.go
  incubator/virtualcluster/pkg/webhook/webhook.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#994 [VC] Bug: add timeout for apiserver to sign the vc webhook CSR
  incubator/virtualcluster/pkg/webhook/virtualcluster/virtualcluster_webhook.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#986 E2e test for hierarchical network policy
  incubator/hnc/pkg/testutils/testutils.go
  incubator/hnc/test/e2e/demo_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#995 [VC] Improvement: support legacy signer kubernetes.io/legacy-unknown
  incubator/virtualcluster/config/setup/all_in_one.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#997 Remove the focused test
  incubator/hnc/test/e2e/demo_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#996 Bump Kubernetes dependencies to 1.18
  incubator/virtualcluster/config/crds/tenancy.x-k8s.io_clusterversions.yaml
  incubator/virtualcluster/go.mod
  incubator/virtualcluster/go.sum
  incubator/virtualcluster/pkg/client/clientset/versioned/typed/tenancy/v1alpha1/clusterversion.go
  incubator/virtualcluster/pkg/client/clientset/versioned/typed/tenancy/v1alpha1/virtualcluster.go
  incubator/virtualcluster/pkg/controller/pki/pki.go
  incubator/virtualcluster/pkg/controller/virtualcluster/master_provisioner_aliyun.go
  incubator/virtualcluster/pkg/controller/virtualcluster/master_provisioner_native.go
  incubator/virtualcluster/pkg/syncer/cluster/cluster.go
  incubator/virtualcluster/pkg/syncer/conversion/helper.go
  incubator/virtualcluster/pkg/syncer/conversion/mutate.go
  incubator/virtualcluster/pkg/syncer/metrics/metrics.go
  incubator/virtualcluster/pkg/syncer/resources/configmap/checker.go
  incubator/virtualcluster/pkg/syncer/resources/configmap/dws.go
  incubator/virtualcluster/pkg/syncer/resources/endpoints/dws.go
  incubator/virtualcluster/pkg/syncer/resources/event/uws.go
  incubator/virtualcluster/pkg/syncer/resources/namespace/checker.go
  incubator/virtualcluster/pkg/syncer/resources/namespace/dws.go
  incubator/virtualcluster/pkg/syncer/resources/node/util.go
  incubator/virtualcluster/pkg/syncer/resources/persistentvolume/checker.go
  incubator/virtualcluster/pkg/syncer/resources/persistentvolume/uws.go
  incubator/virtualcluster/pkg/syncer/resources/persistentvolumeclaim/checker.go
  incubator/virtualcluster/pkg/syncer/resources/persistentvolumeclaim/dws.go
  incubator/virtualcluster/pkg/syncer/resources/pod/checker.go
  incubator/virtualcluster/pkg/syncer/resources/pod/dws.go
  incubator/virtualcluster/pkg/syncer/resources/pod/uws.go
  incubator/virtualcluster/pkg/syncer/resources/secret/checker.go
  incubator/virtualcluster/pkg/syncer/resources/secret/dws.go
  incubator/virtualcluster/pkg/syncer/resources/service/checker.go
  incubator/virtualcluster/pkg/syncer/resources/service/dws.go
  incubator/virtualcluster/pkg/syncer/resources/service/uws.go
  incubator/virtualcluster/pkg/syncer/resources/serviceaccount/checker.go
  incubator/virtualcluster/pkg/syncer/resources/serviceaccount/dws.go
  incubator/virtualcluster/pkg/syncer/resources/storageclass/checker.go
  incubator/virtualcluster/pkg/syncer/resources/storageclass/uws.go
  incubator/virtualcluster/pkg/vn-agent/server/server_test.go
  incubator/virtualcluster/test/e2e/framework/framework.go
  incubator/virtualcluster/test/e2e/framework/util.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#1000 [VC] Fix 1.18 dependency for vc webhook
  incubator/virtualcluster/pkg/webhook/virtualcluster/virtualcluster_webhook.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#1001 [VC] Fix vn-agent UT for Kubernetes 1.18 dependency
  incubator/virtualcluster/pkg/vn-agent/server/server_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#988 Remove v1alpha1 from CRD status.storedVersions
  incubator/hnc/cmd/manager/main.go
  incubator/hnc/internal/reconcilers/crd_removeversion.go
  incubator/hnc/internal/reconcilers/setup.go
  incubator/hnc/internal/reconcilers/suite_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#990 Try injecting certs to all webhooks before early exit
  incubator/hnc/third_party/open-policy-agent/gatekeeper/pkg/webhook/certs.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1004 Adding christopherhein to virtualcluster OWNERS/reviewers
  incubator/virtualcluster/OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1003 Fix flaky test
  incubator/hnc/internal/reconcilers/hnc_config_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#1005 update kubeconfig generation to use ClientConfig
  incubator/virtualcluster/cmd/vcctl/subcmd/create.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#999 Add e2e test suite for API conversion
  incubator/hnc/Makefile
  incubator/hnc/pkg/testutils/testutils.go
  incubator/hnc/test/conversion/conversion_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1013 Reworked landing and docs pages
  README.md
  RELEASE.md
  docs/links.md
Labels: approved, cncf-cla: yes, lgtm, size/L

#968 Added coverage tool
  benchmarks/kubectl-mtb/Makefile
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#977 added pl2 benchmark
  benchmarks/kubectl-mtb/go.mod
  benchmarks/kubectl-mtb/go.sum
  benchmarks/kubectl-mtb/internal/kubectl-mtb/run.go
  benchmarks/kubectl-mtb/internal/mtb_builder/tpl.go
  benchmarks/kubectl-mtb/pkg/benchmark/benchmark.go
  benchmarks/kubectl-mtb/test/benchmarks/block_access_to_cluster_resources/block_access_to_cluster_resources.go
  benchmarks/kubectl-mtb/test/benchmarks/block_access_to_cluster_resources/block_access_to_cluster_resources_test.go
  benchmarks/kubectl-mtb/test/benchmarks/block_add_capabilities/block_add_capabilities.go
  benchmarks/kubectl-mtb/test/benchmarks/block_add_capabilities/block_add_capabilities_test.go
  benchmarks/kubectl-mtb/test/benchmarks/block_multitenant_resources/README.md
  benchmarks/kubectl-mtb/test/benchmarks/block_multitenant_resources/block_multitenant_resources.go
  benchmarks/kubectl-mtb/test/benchmarks/block_multitenant_resources/block_multitenant_resources_test.go
  benchmarks/kubectl-mtb/test/benchmarks/block_multitenant_resources/config.yaml
  benchmarks/kubectl-mtb/test/benchmarks/block_ns_quota/block_ns_quota.go
  benchmarks/kubectl-mtb/test/benchmarks/block_ns_quota/block_ns_quota_test.go
  benchmarks/kubectl-mtb/test/benchmarks/block_privilege_escalation/block_privilege_escalation.go
  benchmarks/kubectl-mtb/test/benchmarks/block_privilege_escalation/block_privilege_escalation_test.go
  benchmarks/kubectl-mtb/test/benchmarks/block_privileged_containers/block_privileged_containers.go
  benchmarks/kubectl-mtb/test/benchmarks/block_privileged_containers/block_privileged_containers_test.go
  benchmarks/kubectl-mtb/test/benchmarks/block_use_of_bind_mounts/block_use_of_bind_mounts.go
  benchmarks/kubectl-mtb/test/benchmarks/block_use_of_bind_mounts/block_use_of_bind_mounts_test.go
  benchmarks/kubectl-mtb/test/benchmarks/block_use_of_host_ipc/block_use_of_host_ipc.go
  benchmarks/kubectl-mtb/test/benchmarks/block_use_of_host_ipc/block_use_of_host_ipc_test.go
  benchmarks/kubectl-mtb/test/benchmarks/block_use_of_host_networking_and_ports/block_use_of_host_networking_and_ports.go
  benchmarks/kubectl-mtb/test/benchmarks/block_use_of_host_networking_and_ports/block_use_of_host_networking_and_ports_test.go
  benchmarks/kubectl-mtb/test/benchmarks/block_use_of_host_pid/block_use_of_host_pid.go
  benchmarks/kubectl-mtb/test/benchmarks/block_use_of_host_pid/block_use_of_host_pid_test.go
  benchmarks/kubectl-mtb/test/benchmarks/block_use_of_nodeport_services/block_use_of_nodeport_services.go
  benchmarks/kubectl-mtb/test/benchmarks/block_use_of_nodeport_services/block_use_of_nodeport_services_test.go
  benchmarks/kubectl-mtb/test/benchmarks/configure_ns_object_quota/configure_ns_object_quota.go
  benchmarks/kubectl-mtb/test/benchmarks/configure_ns_quotas/configure_ns_quotas.go
  benchmarks/kubectl-mtb/test/benchmarks/create_network_policies/create_network_policies.go
  benchmarks/kubectl-mtb/test/benchmarks/create_role_bindings/README.md
  benchmarks/kubectl-mtb/test/benchmarks/create_role_bindings/config.yaml
  benchmarks/kubectl-mtb/test/benchmarks/create_role_bindings/create_role_bindings.go
  benchmarks/kubectl-mtb/test/benchmarks/create_role_bindings/create_role_bindings_test.go
  benchmarks/kubectl-mtb/test/benchmarks/require_run_as_non_root_user/require_run_as_non_root_user.go
  benchmarks/kubectl-mtb/test/benchmarks/require_run_as_non_root_user/require_run_as_non_root_user_test.go
  benchmarks/kubectl-mtb/types/types.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XL

#980 Config correction
  benchmarks/kubectl-mtb/docs/main.go
  benchmarks/kubectl-mtb/go.sum
  benchmarks/kubectl-mtb/pkg/benchmark/benchmark.go
  benchmarks/kubectl-mtb/test/benchmarks/block_access_to_cluster_resources/README.md
  benchmarks/kubectl-mtb/test/benchmarks/block_access_to_cluster_resources/config.yaml
  benchmarks/kubectl-mtb/test/benchmarks/block_add_capabilities/README.md
  benchmarks/kubectl-mtb/test/benchmarks/block_add_capabilities/config.yaml
  benchmarks/kubectl-mtb/test/benchmarks/block_ns_quota/README.md
  benchmarks/kubectl-mtb/test/benchmarks/block_ns_quota/config.yaml
  benchmarks/kubectl-mtb/test/benchmarks/block_privilege_escalation/README.md
  benchmarks/kubectl-mtb/test/benchmarks/block_privilege_escalation/config.yaml
  benchmarks/kubectl-mtb/test/benchmarks/block_privileged_containers/README.md
  benchmarks/kubectl-mtb/test/benchmarks/block_privileged_containers/config.yaml
  benchmarks/kubectl-mtb/test/benchmarks/block_use_of_bind_mounts/README.md
  benchmarks/kubectl-mtb/test/benchmarks/block_use_of_bind_mounts/config.yaml
  benchmarks/kubectl-mtb/test/benchmarks/block_use_of_host_ipc/README.md
  benchmarks/kubectl-mtb/test/benchmarks/block_use_of_host_ipc/config.yaml
  benchmarks/kubectl-mtb/test/benchmarks/block_use_of_host_networking_and_ports/README.md
  benchmarks/kubectl-mtb/test/benchmarks/block_use_of_host_networking_and_ports/config.yaml
  benchmarks/kubectl-mtb/test/benchmarks/block_use_of_host_pid/README.md
  benchmarks/kubectl-mtb/test/benchmarks/block_use_of_host_pid/config.yaml
  benchmarks/kubectl-mtb/test/benchmarks/block_use_of_nodeport_services/README.md
  benchmarks/kubectl-mtb/test/benchmarks/block_use_of_nodeport_services/config.yaml
  benchmarks/kubectl-mtb/test/benchmarks/configure_ns_object_quota/README.md
  benchmarks/kubectl-mtb/test/benchmarks/configure_ns_object_quota/config.yaml
  benchmarks/kubectl-mtb/test/benchmarks/configure_ns_quotas/README.md
  benchmarks/kubectl-mtb/test/benchmarks/configure_ns_quotas/config.yaml
  benchmarks/kubectl-mtb/test/benchmarks/create_network_policies/README.md
  benchmarks/kubectl-mtb/test/benchmarks/create_network_policies/config.yaml
  benchmarks/kubectl-mtb/test/benchmarks/require_run_as_non_root_user/README.md
  benchmarks/kubectl-mtb/test/benchmarks/require_run_as_non_root_user/config.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XL

#1011 Add priority class syncer
  incubator/virtualcluster/cmd/syncer/app/options/options.go
  incubator/virtualcluster/pkg/syncer/apis/config/types.go
  incubator/virtualcluster/pkg/syncer/conversion/equality.go
  incubator/virtualcluster/pkg/syncer/conversion/helper.go
  incubator/virtualcluster/pkg/syncer/mccontroller/mccontroller.go
  incubator/virtualcluster/pkg/syncer/resources/priorityclass/checker.go
  incubator/virtualcluster/pkg/syncer/resources/priorityclass/checker_test.go
  incubator/virtualcluster/pkg/syncer/resources/priorityclass/controller.go
  incubator/virtualcluster/pkg/syncer/resources/priorityclass/uws.go
  incubator/virtualcluster/pkg/syncer/resources/priorityclass/uws_test.go
  incubator/virtualcluster/pkg/syncer/resources/register.go
  incubator/virtualcluster/pkg/syncer/util/test/runDWS.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XL

#1016 Soften pre-GA warnings
  incubator/hnc/README.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#1014 fix sort bug
  incubator/hnc/internal/reconcilers/hnc_config.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1017 Add contributor list
  incubator/hnc/README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#993 [MTB] Sort benchmarks in scorecard
  benchmarks/kubectl-mtb/internal/kubectl-mtb/run.go
  benchmarks/kubectl-mtb/internal/reporter/default_reporter.go
  benchmarks/kubectl-mtb/pkg/benchmark/benchmark.go
  benchmarks/kubectl-mtb/pkg/benchmark_suite/benchmarks_suite.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#1015 Add annotation for subnamespace when print tree
  incubator/hnc/internal/kubectl/tree.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1021 Line up Cloud Build with makefile
  incubator/hnc/Makefile
  incubator/hnc/cloudbuild.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#981 [MTB] Added leveled logging
  benchmarks/kubectl-mtb/go.mod
  benchmarks/kubectl-mtb/go.sum
  benchmarks/kubectl-mtb/internal/kubectl-mtb/root.go
  benchmarks/kubectl-mtb/internal/kubectl-mtb/run.go
  benchmarks/kubectl-mtb/test/benchmarks/block_access_to_cluster_resources/block_access_to_cluster_resources.go
  benchmarks/kubectl-mtb/test/benchmarks/block_add_capabilities/block_add_capabilities.go
  benchmarks/kubectl-mtb/test/benchmarks/block_ns_quota/block_ns_quota.go
  benchmarks/kubectl-mtb/test/benchmarks/block_privilege_escalation/block_privilege_escalation.go
  benchmarks/kubectl-mtb/test/benchmarks/block_privileged_containers/block_privileged_containers.go
  benchmarks/kubectl-mtb/test/benchmarks/block_use_of_bind_mounts/block_use_of_bind_mounts.go
  benchmarks/kubectl-mtb/test/benchmarks/block_use_of_host_ipc/block_use_of_host_ipc.go
  benchmarks/kubectl-mtb/test/benchmarks/block_use_of_host_networking_and_ports/block_use_of_host_networking_and_ports.go
  benchmarks/kubectl-mtb/test/benchmarks/block_use_of_host_pid/block_use_of_host_pid.go
  benchmarks/kubectl-mtb/test/benchmarks/block_use_of_nodeport_services/block_use_of_nodeport_services.go
  benchmarks/kubectl-mtb/test/benchmarks/configure_ns_object_quota/configure_ns_object_quota.go
  benchmarks/kubectl-mtb/test/benchmarks/configure_ns_quotas/configure_ns_quotas.go
  benchmarks/kubectl-mtb/test/benchmarks/create_network_policies/create_network_policies.go
  benchmarks/kubectl-mtb/test/benchmarks/require_run_as_non_root_user/require_run_as_non_root_user.go
  benchmarks/kubectl-mtb/test/utils/log/log.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#987 [MTB] Updated Docs
  benchmarks/kubectl-mtb/README.md
  benchmarks/kubectl-mtb/test/quotas/ns_quota.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#1028 fix(test): no priotiry/v1 in k8s.io/api
  incubator/virtualcluster/pkg/syncer/resources/priorityclass/checker_test.go
  incubator/virtualcluster/pkg/syncer/resources/priorityclass/uws_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#1031 [VC] Feature: disable the logger caller and stacktrace field
  incubator/virtualcluster/cmd/manager/main.go
  incubator/virtualcluster/config/setup/all_in_one.yaml
  incubator/virtualcluster/config/setup/all_in_one_aliyun.yaml
  incubator/virtualcluster/pkg/controller/util/logr/util.go
  incubator/virtualcluster/pkg/controller/virtualcluster/virtualcluster_controller.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1032 HNC: Add support for plugin build for darwin amd64
  incubator/hnc/cloudbuild.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#1033 Update v1alpah2 SubnamespaceAnchor status to camel case
  incubator/hnc/api/v1alpha2/subnamespace_anchor.go
  incubator/hnc/config/crd/bases/hnc.x-k8s.io_subnamespaceanchors.yaml
  incubator/hnc/test/conversion/conversion_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#1039 Add timeoutSeconds patch for webhook configuration
  incubator/hnc/config/webhook/kustomization.yaml
  incubator/hnc/config/webhook/webhook_patch.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#1047 Cherrypick: Make it work with Go 1.15
  incubator/hnc/internal/reconcilers/hierarchy_config_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1049 Add support for plugin build for darwin amd64
  incubator/hnc/cloudbuild.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#1048 Add timeoutSeconds patch for webhook configuration
  incubator/hnc/config/webhook/kustomization.yaml
  incubator/hnc/config/webhook/webhook_patch.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#1051 [VC] Features: add webhook cmd option, add detailed error messages
  incubator/virtualcluster/cmd/manager/main.go
  incubator/virtualcluster/config/setup/all_in_one.yaml
  incubator/virtualcluster/pkg/webhook/virtualcluster/virtualcluster_webhook.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1040 Support --version option for hnc plugin
  incubator/hnc/Makefile
  incubator/hnc/cloudbuild.yaml
  incubator/hnc/internal/kubectl/root.go
  incubator/hnc/internal/kubectl/version.go
  incubator/hnc/internal/version/version.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#1053 [VC]: 🐜 Fix make test not catching and fix testsuite
  incubator/virtualcluster/Makefile
  incubator/virtualcluster/cmd/syncer/app/options/options.go
  incubator/virtualcluster/go.sum
  incubator/virtualcluster/pkg/apis/tenancy/v1alpha1/zz_generated.deepcopy.go
  incubator/virtualcluster/pkg/syncer/conversion/equality.go
  incubator/virtualcluster/pkg/syncer/conversion/helper.go
  incubator/virtualcluster/pkg/syncer/mccontroller/mccontroller.go
  incubator/virtualcluster/pkg/syncer/resources/priorityclass/checker.go
  incubator/virtualcluster/pkg/syncer/resources/priorityclass/checker_test.go
  incubator/virtualcluster/pkg/syncer/resources/priorityclass/controller.go
  incubator/virtualcluster/pkg/syncer/resources/priorityclass/uws.go
  incubator/virtualcluster/pkg/syncer/resources/priorityclass/uws_test.go
  incubator/virtualcluster/pkg/syncer/resources/register.go
  incubator/virtualcluster/pkg/syncer/resources/storageclass/controller.go
  incubator/virtualcluster/pkg/syncer/resources/storageclass/uws.go
  incubator/virtualcluster/pkg/syncer/util/test/runDWS.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1024 [VC] notify tenant about pod FailCreated event in super.
  incubator/virtualcluster/go.sum
  incubator/virtualcluster/pkg/syncer/constants/constants.go
  incubator/virtualcluster/pkg/syncer/mccontroller/mccontroller.go
  incubator/virtualcluster/pkg/syncer/resources/pod/dws.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1054 [MTB] resolved namespace bug
  benchmarks/kubectl-mtb/test/benchmarks/block_access_to_cluster_resources/block_access_to_cluster_resources.go
  benchmarks/kubectl-mtb/test/benchmarks/block_multitenant_resources/README.md
  benchmarks/kubectl-mtb/test/benchmarks/create_role_bindings/README.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#1038 Update guide to choose OS for the plugin
  incubator/hnc/docs/user-guide/how-to.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#1056 Support server-side dry run
  incubator/hnc/config/webhook/webhook_patch.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1057 Improve e2e test pass rate and infra
  incubator/hnc/internal/kubectl/tree.go
  incubator/hnc/pkg/testutils/testutils.go
  incubator/hnc/test/e2e/demo_test.go
  incubator/hnc/test/e2e/issues_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1060 Update 0.5 docs to 0.5.2
  incubator/hnc/README.md
  incubator/hnc/docs/user-guide/how-to.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1059 Support server-side dry run
  incubator/hnc/config/webhook/webhook_patch.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1061 Update master docs to 0.5.2
  incubator/hnc/README.md
  incubator/hnc/docs/user-guide/how-to.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1026 Update v1alpha2 HNCConfig modes to camel case
  incubator/hnc/api/v1alpha2/hnc_config.go
  incubator/hnc/config/crd/bases/hnc.x-k8s.io_hncconfigurations.yaml
  incubator/hnc/internal/validators/hncconfig_test.go
  incubator/hnc/test/conversion/conversion_test.go
  incubator/hnc/test/e2e/demo_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L
