Repository kubernetes-sigs/multi-tenancy, pull requests merged in 2020-03, with the labels that each got.

#475 [Incubator][VC]Use workqueue NumRequeues API to avoid infinite retry
  incubator/virtualcluster/pkg/syncer/constants/constants.go
  incubator/virtualcluster/pkg/syncer/reconciler/reconciler.go
  incubator/virtualcluster/pkg/syncer/resources/event/uws.go
  incubator/virtualcluster/pkg/syncer/resources/persistentvolume/checker.go
  incubator/virtualcluster/pkg/syncer/resources/persistentvolume/uws.go
  incubator/virtualcluster/pkg/syncer/resources/pod/checker.go
  incubator/virtualcluster/pkg/syncer/resources/pod/uws.go
  incubator/virtualcluster/pkg/syncer/resources/service/checker.go
  incubator/virtualcluster/pkg/syncer/resources/service/uws.go
  incubator/virtualcluster/pkg/syncer/resources/storageclass/checker.go
  incubator/virtualcluster/pkg/syncer/resources/storageclass/uws.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#474 [Incubator][VC]Update ClusterVNodePodMap when vPod is deleted
  incubator/virtualcluster/pkg/syncer/resources/pod/checker.go
  incubator/virtualcluster/pkg/syncer/resources/pod/dws.go
  incubator/virtualcluster/pkg/syncer/resources/pod/uws.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#462 Add Conditions in HNCConfiguration.Status to indicate error scenarios.
  incubator/hnc/api/v1alpha1/hnc_config.go
  incubator/hnc/api/v1alpha1/zz_generated.deepcopy.go
  incubator/hnc/config/crd/bases/hnc.x-k8s.io_hncconfigurations.yaml
  incubator/hnc/pkg/reconcilers/hnc_config.go
  incubator/hnc/pkg/reconcilers/hnc_config_test.go
  incubator/hnc/pkg/reconcilers/object_test.go
  incubator/hnc/pkg/reconcilers/setup.go
  incubator/hnc/pkg/reconcilers/suite_test.go
  incubator/hnc/pkg/reconcilers/test_helpers_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XL

#482 [incubator][VC] attach well known label to vNode
  incubator/virtualcluster/pkg/syncer/resources/node/util.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#481 [Incubator][VC]Add UID check for configMap/EP/PVC/Secret/SA resources
  incubator/virtualcluster/pkg/syncer/resources/configmap/checker.go
  incubator/virtualcluster/pkg/syncer/resources/configmap/dws.go
  incubator/virtualcluster/pkg/syncer/resources/endpoints/checker.go
  incubator/virtualcluster/pkg/syncer/resources/endpoints/dws.go
  incubator/virtualcluster/pkg/syncer/resources/persistentvolumeclaim/checker.go
  incubator/virtualcluster/pkg/syncer/resources/persistentvolumeclaim/dws.go
  incubator/virtualcluster/pkg/syncer/resources/secret/checker.go
  incubator/virtualcluster/pkg/syncer/resources/secret/dws.go
  incubator/virtualcluster/pkg/syncer/resources/serviceaccount/checker.go
  incubator/virtualcluster/pkg/syncer/resources/serviceaccount/dws.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#484 [incubator][VC] remove endpoints uid checker
  incubator/virtualcluster/pkg/syncer/resources/endpoints/checker.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#485 Enable hns reconciler to create namespace
  incubator/hnc/Makefile
  incubator/hnc/api/v1alpha1/hierarchical_namespace.go
  incubator/hnc/pkg/forest/forest.go
  incubator/hnc/pkg/reconcilers/hierarchical_namespace.go
  incubator/hnc/pkg/reconcilers/hierarchical_namespace_test.go
  incubator/hnc/pkg/reconcilers/hierarchy_config.go
  incubator/hnc/pkg/reconcilers/hierarchy_config_test.go
  incubator/hnc/pkg/reconcilers/setup.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#489 [incubator][VC] requeue pPod if status diff from vPod
  incubator/virtualcluster/pkg/syncer/resources/pod/checker.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#476 Support 'ignore' mode in ConfigReconciler.
  incubator/hnc/api/v1alpha1/hnc_config.go
  incubator/hnc/config/crd/bases/hnc.x-k8s.io_hncconfigurations.yaml
  incubator/hnc/pkg/forest/forest.go
  incubator/hnc/pkg/reconcilers/hnc_config.go
  incubator/hnc/pkg/reconcilers/hnc_config_test.go
  incubator/hnc/pkg/reconcilers/object.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#494 [Incubator][VC]Avoid using Secret/SA name in Labels
  incubator/virtualcluster/pkg/syncer/constants/constants.go
  incubator/virtualcluster/pkg/syncer/conversion/helper_test.go
  incubator/virtualcluster/pkg/syncer/conversion/mutate.go
  incubator/virtualcluster/pkg/syncer/resources/pod/dws.go
  incubator/virtualcluster/pkg/syncer/resources/secret/checker.go
  incubator/virtualcluster/pkg/syncer/resources/secret/dws.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#497 [Incubator][VC]Ensure Pod affinity rule is only applied within tenant scope
  incubator/virtualcluster/pkg/syncer/conversion/mutate.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#491 Remove duplicate code in reconcilers_test package
  incubator/hnc/pkg/reconcilers/hnc_config_test.go
  incubator/hnc/pkg/reconcilers/object_test.go
  incubator/hnc/pkg/reconcilers/test_helpers_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#486 Support 'remove' mode in ConfigReconciler.
  incubator/hnc/pkg/reconcilers/hnc_config_test.go
  incubator/hnc/pkg/reconcilers/object.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#502 Add `allowCascadingDelete` to HC.spec and enable `kubectl`
  incubator/hnc/api/v1alpha1/hierarchy_types.go
  incubator/hnc/config/crd/bases/hnc.x-k8s.io_hierarchyconfigurations.yaml
  incubator/hnc/pkg/kubectl/set.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#496 Update transient & report invalid HNS states
  incubator/hnc/api/v1alpha1/hierarchy_types.go
  incubator/hnc/pkg/reconcilers/hierarchical_namespace.go
  incubator/hnc/pkg/reconcilers/hierarchical_namespace_test.go
  incubator/hnc/pkg/reconcilers/hierarchy_config.go
  incubator/hnc/pkg/reconcilers/hierarchy_config_test.go
  incubator/hnc/pkg/reconcilers/object.go
  incubator/hnc/pkg/reconcilers/setup.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#503 Fix a flaky object controller test
  incubator/hnc/pkg/reconcilers/object_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#505 [Incubator][VC]Sync non-service eps
  incubator/virtualcluster/pkg/syncer/constants/constants.go
  incubator/virtualcluster/pkg/syncer/resources/endpoints/dws.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#504 Upgrade controller-runtime from v0.2.2 to v0.5.0 and its dependencies.
  incubator/hnc/Dockerfile
  incubator/hnc/Makefile
  incubator/hnc/api/v1alpha1/zz_generated.deepcopy.go
  incubator/hnc/cloudbuild.yaml
  incubator/hnc/cmd/manager/main.go
  incubator/hnc/config/crd/bases/hnc.x-k8s.io_hierarchicalnamespaces.yaml
  incubator/hnc/config/crd/bases/hnc.x-k8s.io_hierarchyconfigurations.yaml
  incubator/hnc/config/crd/bases/hnc.x-k8s.io_hncconfigurations.yaml
  incubator/hnc/config/default/manager_auth_proxy_patch.yaml
  incubator/hnc/go.mod
  incubator/hnc/go.sum
  incubator/hnc/hack/ci-test.sh
  incubator/hnc/pkg/kubectl/root.go
  incubator/hnc/pkg/reconcilers/hnc_config_test.go
  incubator/hnc/pkg/reconcilers/suite_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#508 Update `isModified()` to remove sleeps in tests
  incubator/hnc/pkg/reconcilers/object_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#509 Set an object reconciler to "ignore" mode if its corresponding type is removed from the HNCConfiguration Spec
  incubator/hnc/pkg/reconcilers/hnc_config.go
  incubator/hnc/pkg/reconcilers/hnc_config_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#510 Exclude "kube-public" namespace in HNC
  incubator/hnc/pkg/reconcilers/setup.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#512 Explicitly check if a GVK exists before creating corresponding object reconciler
  incubator/hnc/pkg/reconcilers/hnc_config.go
  incubator/hnc/pkg/reconcilers/hnc_config_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#517 [Incubator][VC] allow the user to specify max number of reconcilers
  incubator/virtualcluster/cmd/manager/main.go
  incubator/virtualcluster/pkg/controller/clusterversion/clusterversion_controller.go
  incubator/virtualcluster/pkg/controller/controller.go
  incubator/virtualcluster/pkg/controller/vcmanager/vcmanager.go
  incubator/virtualcluster/pkg/controller/virtualcluster/virtualcluster_controller.go
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/M

#516 [Incubator][VC]Add owner reference for all namespaces created by syncer and vcmanager
  incubator/virtualcluster/pkg/controller/util/kube/util.go
  incubator/virtualcluster/pkg/controller/virtualcluster/master_provisioner_aliyun.go
  incubator/virtualcluster/pkg/controller/virtualcluster/master_provisioner_native.go
  incubator/virtualcluster/pkg/syncer/cluster/cluster.go
  incubator/virtualcluster/pkg/syncer/conversion/helper.go
  incubator/virtualcluster/pkg/syncer/handler/enqueue_object.go
  incubator/virtualcluster/pkg/syncer/mccontroller/mccontroller.go
  incubator/virtualcluster/pkg/syncer/reconciler/reconciler.go
  incubator/virtualcluster/pkg/syncer/resources/namespace/dws.go
  incubator/virtualcluster/pkg/syncer/syncer.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#518 [incubator][VC] syncer: try to get tenant admin kubeconfig from vc object
  incubator/virtualcluster/pkg/syncer/constants/constants.go
  incubator/virtualcluster/pkg/syncer/syncer.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#514 Make ConfigReconciler watches for custom resources
  incubator/hnc/cmd/manager/main.go
  incubator/hnc/go.mod
  incubator/hnc/go.sum
  incubator/hnc/pkg/reconcilers/hnc_config.go
  incubator/hnc/pkg/reconcilers/hnc_config_test.go
  incubator/hnc/pkg/reconcilers/suite_test.go
  incubator/hnc/pkg/reconcilers/test_helpers_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#519 [incubator][VC] fix: decode kubeconfig base64 string
  incubator/virtualcluster/pkg/syncer/syncer.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#520 [incubator][VC ] add mock testing framework
  incubator/virtualcluster/pkg/syncer/cluster/cluster.go
  incubator/virtualcluster/pkg/syncer/cluster/fake_cluster.go
  incubator/virtualcluster/pkg/syncer/mccontroller/mccontroller.go
  incubator/virtualcluster/pkg/syncer/resources/configmap/checker.go
  incubator/virtualcluster/pkg/syncer/resources/namespace/checker.go
  incubator/virtualcluster/pkg/syncer/resources/namespace/controller.go
  incubator/virtualcluster/pkg/syncer/resources/namespace/dws.go
  incubator/virtualcluster/pkg/syncer/resources/namespace/dws_test.go
  incubator/virtualcluster/pkg/syncer/resources/persistentvolumeclaim/checker.go
  incubator/virtualcluster/pkg/syncer/resources/pod/checker.go
  incubator/virtualcluster/pkg/syncer/resources/secret/checker.go
  incubator/virtualcluster/pkg/syncer/resources/service/checker.go
  incubator/virtualcluster/pkg/syncer/resources/serviceaccount/checker.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#521 [Incubator][VC] fix vc test case
  incubator/virtualcluster/pkg/controller/virtualcluster/virtualcluster_controller.go
  incubator/virtualcluster/pkg/controller/virtualcluster/virtualcluster_controller_test.go
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/XS

#523 Rename ns.RequiredChildOf to ns.Owner in forest
  incubator/hnc/pkg/forest/forest.go
  incubator/hnc/pkg/reconcilers/hierarchical_namespace.go
  incubator/hnc/pkg/reconcilers/hierarchy_config.go
  incubator/hnc/pkg/validators/hierarchy.go
  incubator/hnc/pkg/validators/hierarchy_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#522 Implement a validation controller for hncconfigurations resource.
  incubator/hnc/cmd/manager/main.go
  incubator/hnc/config/webhook/manifests.yaml
  incubator/hnc/pkg/validators/hierarchy.go
  incubator/hnc/pkg/validators/hncconfig.go
  incubator/hnc/pkg/validators/hncconfig_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#525 Change StatusReasonInvalid to StatusReasonForbidden in hncconfig.go
  incubator/hnc/pkg/validators/hncconfig.go
  incubator/hnc/pkg/validators/hncconfig_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#526 [Incubator][VC]Increase the QPS and burst for syncer clients
  incubator/virtualcluster/cmd/syncer/app/options/options.go
  incubator/virtualcluster/pkg/syncer/cluster/cluster.go
  incubator/virtualcluster/pkg/syncer/constants/constants.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#524 Handle missing or non-default specs for Role and RoleBinding in ConfigReconciler.
  incubator/hnc/pkg/config/default_config.go
  incubator/hnc/pkg/reconcilers/hnc_config.go
  incubator/hnc/pkg/reconcilers/hnc_config_test.go
  incubator/hnc/pkg/reconcilers/test_helpers_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#528 Change from StatusReasonForbidden to StatusReasonInvalid for invalid requests
  incubator/hnc/pkg/validators/hierarchy.go
  incubator/hnc/pkg/validators/hncconfig.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#527 [Incubator][VC] not return error is rootca already exist
  incubator/virtualcluster/pkg/controller/virtualcluster/master_provisioner_native.go
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/S

#449 #445 - flag.Parse causes issue in go 1.13
  benchmarks/config.yaml
  benchmarks/e2e/tests/e2e.go
  benchmarks/e2e/tests/e2e_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#499 [MTB] corrected relative path of config.yaml
  benchmarks/e2e/config/config.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#530 Corrects the kubeconfig in Benchmarks Readme
  benchmarks/e2e/tests/block_multitenant_resources/README.md
  benchmarks/e2e/tests/block_other_tenant_resources/README.md
  benchmarks/e2e/tests/require_run_as_non_root/README.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#531 [MTB] refactor: use yaml unmarshal
  benchmarks/e2e/config/config.go
  benchmarks/e2e/config/utils.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#529 Handle multiple configurations of the same type in ConfigReconciler
  incubator/hnc/api/v1alpha1/hnc_config.go
  incubator/hnc/config/crd/bases/hnc.x-k8s.io_hncconfigurations.yaml
  incubator/hnc/pkg/reconcilers/hnc_config.go
  incubator/hnc/pkg/reconcilers/hnc_config_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#541 fix typo
  incubator/hnc/pkg/validators/hierarchy.go
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/XS

#556 Adds .gitignore file
  benchmarks/.gitignore
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#550 Update HCR & HNSR to move NS creation to HNSR
  incubator/hnc/Makefile
  incubator/hnc/api/v1alpha1/hierarchical_namespace.go
  incubator/hnc/api/v1alpha1/hierarchy_types.go
  incubator/hnc/api/v1alpha1/zz_generated.deepcopy.go
  incubator/hnc/cmd/manager/main.go
  incubator/hnc/config/crd/bases/hnc.x-k8s.io_hierarchyconfigurations.yaml
  incubator/hnc/pkg/forest/forest.go
  incubator/hnc/pkg/kubectl/create.go
  incubator/hnc/pkg/kubectl/describe.go
  incubator/hnc/pkg/kubectl/root.go
  incubator/hnc/pkg/kubectl/set.go
  incubator/hnc/pkg/reconcilers/hierarchical_namespace.go
  incubator/hnc/pkg/reconcilers/hierarchical_namespace_test.go
  incubator/hnc/pkg/reconcilers/hierarchy_config.go
  incubator/hnc/pkg/reconcilers/hierarchy_config_test.go
  incubator/hnc/pkg/reconcilers/setup.go
  incubator/hnc/pkg/reconcilers/suite_test.go
  incubator/hnc/pkg/reconcilers/test_helpers_test.go
  incubator/hnc/pkg/validators/hierarchy.go
  incubator/hnc/pkg/validators/hierarchy_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#542 Compute NumPropagatedObjects in HNCConfiguration status
  incubator/hnc/api/v1alpha1/hnc_config.go
  incubator/hnc/api/v1alpha1/zz_generated.deepcopy.go
  incubator/hnc/config/crd/bases/hnc.x-k8s.io_hncconfigurations.yaml
  incubator/hnc/pkg/forest/forest.go
  incubator/hnc/pkg/reconcilers/hnc_config.go
  incubator/hnc/pkg/reconcilers/hnc_config_test.go
  incubator/hnc/pkg/reconcilers/object.go
  incubator/hnc/pkg/reconcilers/setup.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#540 [Incubator][VC] allow vn-agent to forward request to super master if kubelet-client-crt is not available
  incubator/virtualcluster/README.md
  incubator/virtualcluster/cmd/vcctl/subcmd/create.go
  incubator/virtualcluster/cmd/vn-agent/app/options/options.go
  incubator/virtualcluster/config/setup/all_in_one.yaml
  incubator/virtualcluster/config/setup/all_in_one_aliyun.yaml
  incubator/virtualcluster/pkg/controller/util/kube/util.go
  incubator/virtualcluster/pkg/vn-agent/config/config.go
  incubator/virtualcluster/pkg/vn-agent/server/route.go
  incubator/virtualcluster/pkg/vn-agent/server/server_test.go
  incubator/virtualcluster/pkg/vn-agent/server/translate.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#562 [Incubator] [VC] fix vn-agent bug
  incubator/virtualcluster/go.mod
  incubator/virtualcluster/go.sum
  incubator/virtualcluster/pkg/controller/util/net/util.go
  incubator/virtualcluster/pkg/vn-agent/server/route.go
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/S

#563 [incubator][VC] fix panic: when pPV not been bound, claimRef is nil
  incubator/virtualcluster/pkg/syncer/resources/persistentvolume/uws.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#538 Renames github.com/realshuting to sigs.k8s.io for uniformity
  benchmarks/e2e/tests/block_cluster_resources/block_cluster_resources.go
  benchmarks/e2e/tests/configure_ns_quotas/configure_ns_quotas.go
  benchmarks/e2e/tests/e2e.go
  benchmarks/go.mod
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#539 Handles an empty config file
  benchmarks/e2e/config/config.go
  benchmarks/e2e/config/utils.go
  benchmarks/e2e/tests/block_cluster_resources/block_cluster_resources.go
  benchmarks/e2e/tests/configure_ns_quotas/configure_ns_quotas.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#554 corrected typo in README
  benchmarks/e2e/tests/block_ns_quotas/README.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#547 added test definition of configure ns object limits
  benchmarks/e2e/tests/configure_ns_object_quotas/README.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#558 Adds block_privileged_container test
  benchmarks/e2e/tests/block_privileged_containers/block_privilege_container.go
  benchmarks/e2e/tests/e2e.go
  incubator/hnc/go.mod
  poc/tenant-controller/go.mod
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#506 #258 MTB: Test for Block modification of resource quotas (MTB-PL1-CC-TI-1)
  benchmarks/e2e/tests/block_ns_quotas/block_ns_quotas.go
  benchmarks/e2e/tests/e2e.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#566 Updates the Readme
  benchmarks/documentation/run.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#569 Enable Tenant and Tenantnamespace reconcilers to check
  tenant/pkg/controller/tenant/tenant_controller_suite.go
  tenant/pkg/controller/tenant/tenant_controller_test.go
  tenant/pkg/controller/tenantnamespace/tenantnamespace_controller_suite_test.go
  tenant/pkg/controller/tenantnamespace/tenantnamespace_controller_test.go
  tenant/pkg/controller/tenantnamespace/tenantnamespace_helper.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#561 [Incubator][VC]Delete vPod if pPod is evicted
  incubator/virtualcluster/pkg/syncer/resources/pod/checker.go
  incubator/virtualcluster/pkg/syncer/resources/pod/dws.go
  incubator/virtualcluster/pkg/syncer/resources/pod/uws.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#573 Make allowCascadingDelete optional
  incubator/hnc/api/v1alpha1/hierarchy_types.go
  incubator/hnc/config/crd/bases/hnc.x-k8s.io_hierarchyconfigurations.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#565 Rename kubectl hns command 'create2' to 'create'
  incubator/hnc/pkg/kubectl/create.go
  incubator/hnc/pkg/kubectl/root.go
Labels: approved, cncf-cla: yes, lgtm

#576 Address #333. Fail a release on duplicate image and tag
  incubator/hnc/Makefile
  incubator/hnc/README.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#577 Run `go mod tidy` to have an accurate reflection of dependencies
  incubator/hnc/go.mod
  incubator/hnc/go.sum
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/L

#567 added /vendor in gitignore
  benchmarks/.gitignore
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#557 Adds block_host_pid test
  benchmarks/e2e/tests/block_host_pid/block_host_pid.go
  benchmarks/e2e/tests/e2e.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#571 Add better HNC Config observability and fix flaky test
  incubator/hnc/api/v1alpha1/hnc_config.go
  incubator/hnc/config/crd/bases/hnc.x-k8s.io_hncconfigurations.yaml
  incubator/hnc/pkg/reconcilers/hnc_config.go
  incubator/hnc/pkg/reconcilers/hnc_config_test.go
  incubator/hnc/pkg/reconcilers/object.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#578 Add links.md to list all HNC docs
  incubator/hnc/doc/links.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#579 Reduce default verbosity of validators
  incubator/hnc/pkg/validators/hierarchy.go
  incubator/hnc/pkg/validators/object.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#574 Always sync objects to forest, even in namespaces with critical conditions
  incubator/hnc/pkg/reconcilers/hnc_config_test.go
  incubator/hnc/pkg/reconcilers/object.go
  incubator/hnc/pkg/reconcilers/object_test.go
  incubator/hnc/pkg/reconcilers/test_helpers_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#581 Replace ns.Owner with ns.IsOwned in the forest
  incubator/hnc/pkg/forest/forest.go
  incubator/hnc/pkg/reconcilers/hierarchy_config.go
  incubator/hnc/pkg/validators/hierarchy.go
Labels: approved, cncf-cla: yes, lgtm, size/M
