Repository kubernetes-sigs/multi-tenancy, pull requests merged in 2020-02, with the labels that each got.

#368 Generate controller stats logs
  incubator/hnc/cmd/manager/main.go
  incubator/hnc/pkg/controllers/hierarchy_controller.go
  incubator/hnc/pkg/controllers/object_controller.go
  incubator/hnc/pkg/controllers/object_controller_new.go
  incubator/hnc/pkg/controllers/setup.go
  incubator/hnc/pkg/stats/counter.go
  incubator/hnc/pkg/stats/stats.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#375 [Incubator][VC]Add clusterIP of the default/kubernetes service to apiserver's certificate
  incubator/virtualcluster/Makefile
  incubator/virtualcluster/cmd/vcctl/subcmd/create.go
  incubator/virtualcluster/hack/lib/docker-image.sh
  incubator/virtualcluster/hack/make-rules/release-images.sh
  incubator/virtualcluster/pkg/controller/pki/pki.go
  incubator/virtualcluster/pkg/controller/util/kube/util.go
  incubator/virtualcluster/pkg/controller/virtualcluster/master_provisioner_native.go
  incubator/virtualcluster/pkg/controller/virtualcluster/virtualcluster_controller.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#376 [Incubator][VC]Add PVC syncer
  incubator/virtualcluster/pkg/syncer/conversion/equality.go
  incubator/virtualcluster/pkg/syncer/mccontroller/mccontroller.go
  incubator/virtualcluster/pkg/syncer/resources/persistentvolumeclaim/checker.go
  incubator/virtualcluster/pkg/syncer/resources/persistentvolumeclaim/controller.go
  incubator/virtualcluster/pkg/syncer/resources/persistentvolumeclaim/dws.go
  incubator/virtualcluster/pkg/syncer/resources/register.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#370 [Incubator][VC]Implement vNode Garbage Collection
  incubator/virtualcluster/pkg/syncer/constants/constants.go
  incubator/virtualcluster/pkg/syncer/resources/pod/checker.go
  incubator/virtualcluster/pkg/syncer/resources/pod/controller.go
  incubator/virtualcluster/pkg/syncer/resources/pod/dws.go
  incubator/virtualcluster/pkg/syncer/resources/pod/uws.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#378 [Incubator][VC]annotate slb id to vc cr
  incubator/virtualcluster/go.mod
  incubator/virtualcluster/pkg/controller/util/kube/util.go
  incubator/virtualcluster/pkg/controller/virtualcluster/master_provisioner_aliyun.go
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/L

#380 Remove old object controller and the flag
  incubator/hnc/Makefile
  incubator/hnc/cmd/manager/main.go
  incubator/hnc/config/default/manager_auth_proxy_patch.yaml
  incubator/hnc/pkg/controllers/object_controller.go
  incubator/hnc/pkg/controllers/object_controller_test.go
  incubator/hnc/pkg/controllers/setup.go
  incubator/hnc/pkg/controllers/suite_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#381 Rename ObjectReconcilerNew to ObjectReconciler
  incubator/hnc/pkg/controllers/object_controller.go
  incubator/hnc/pkg/controllers/setup.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#377 HNC: Make API server QPS throttle configurable with a default value.
  incubator/hnc/cmd/manager/main.go
  incubator/hnc/config/default/manager_auth_proxy_patch.yaml
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/S

#382 make docker-image.sh compatible to bash 3.2.57
  incubator/virtualcluster/hack/lib/docker-image.sh
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/XS

#384 [Incubator][VC]Add a go pprof server in syncer
  incubator/virtualcluster/cmd/syncer/app/server.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#385 [Incubator] [VC] delete node-controller serviceaccount to disable node periodic checkin in aliyun modeg
  incubator/virtualcluster/config/crds/tenancy_v1alpha1_clusterversion.yaml
  incubator/virtualcluster/config/crds/tenancy_v1alpha1_virtualcluster.yaml
  incubator/virtualcluster/pkg/controller/virtualcluster/master_provisioner_aliyun.go
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/S

#388 [Incubator][VC] add vc annotations to default namespace
  incubator/virtualcluster/pkg/controller/util/kube/util.go
  incubator/virtualcluster/pkg/controller/virtualcluster/master_provisioner_native.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#389 [Incubator][VC] ignore annotations that have specific prefixes
  incubator/virtualcluster/config/setup/all_in_one.yaml
  incubator/virtualcluster/pkg/syncer/conversion/equality.go
  incubator/virtualcluster/pkg/syncer/utils/string.go
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/M

#393 Revert "[Incubator][VC] ignore annotations that have specific prefixes "
  incubator/virtualcluster/config/setup/all_in_one.yaml
  incubator/virtualcluster/pkg/syncer/conversion/equality.go
  incubator/virtualcluster/pkg/syncer/utils/string.go
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/M

#392 [Incubator][VC] remove root ns after deleting the vc
  incubator/virtualcluster/pkg/controller/virtualcluster/master_provisioner_aliyun.go
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/S

#395 [incubator][VC] remove endpoints syncer
  incubator/virtualcluster/pkg/syncer/resources/endpoints/dws.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#387 Add performance tests on controller start/restart
  incubator/hnc/scripts/performance/clean-up-topologies.sh
  incubator/hnc/scripts/performance/load-topology-full.sh
  incubator/hnc/scripts/performance/load-topology-skewer.sh
  incubator/hnc/scripts/performance/load-topology-wide.sh
  incubator/hnc/scripts/performance/start-controllers.sh
  incubator/hnc/scripts/performance/test.sh
Labels: approved, cncf-cla: yes, lgtm, size/L

#396 Set stats.Init() as default
  incubator/hnc/pkg/stats/stats.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#394 [Incubator][VC]Add TransparentMetaPrefixes and OpaqueMetaPrefixes in VirtualCluster
  incubator/virtualcluster/config/crds/tenancy_v1alpha1_virtualcluster.yaml
  incubator/virtualcluster/config/sampleswithspec/virtualcluster_1_loadbalancer.yaml
  incubator/virtualcluster/config/sampleswithspec/virtualcluster_1_nodeport.yaml
  incubator/virtualcluster/pkg/apis/tenancy/v1alpha1/virtualcluster_types.go
  incubator/virtualcluster/pkg/apis/tenancy/v1alpha1/zz_generated.deepcopy.go
  incubator/virtualcluster/pkg/syncer/cluster/cluster.go
  incubator/virtualcluster/pkg/syncer/conversion/equality.go
  incubator/virtualcluster/pkg/syncer/conversion/equality_test.go
  incubator/virtualcluster/pkg/syncer/mccontroller/mccontroller.go
  incubator/virtualcluster/pkg/syncer/resources/configmap/dws.go
  incubator/virtualcluster/pkg/syncer/resources/endpoints/dws.go
  incubator/virtualcluster/pkg/syncer/resources/persistentvolumeclaim/checker.go
  incubator/virtualcluster/pkg/syncer/resources/persistentvolumeclaim/dws.go
  incubator/virtualcluster/pkg/syncer/resources/pod/checker.go
  incubator/virtualcluster/pkg/syncer/resources/pod/dws.go
  incubator/virtualcluster/pkg/syncer/resources/pod/uws.go
  incubator/virtualcluster/pkg/syncer/resources/secret/dws.go
  incubator/virtualcluster/pkg/syncer/resources/service/checker.go
  incubator/virtualcluster/pkg/syncer/resources/storageclass/checker.go
  incubator/virtualcluster/pkg/syncer/resources/storageclass/uws.go
  incubator/virtualcluster/pkg/syncer/syncer.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#383 [Incubator][VC]Add PersistentVolume syncer
  incubator/virtualcluster/pkg/syncer/conversion/equality.go
  incubator/virtualcluster/pkg/syncer/conversion/helper.go
  incubator/virtualcluster/pkg/syncer/mccontroller/mccontroller.go
  incubator/virtualcluster/pkg/syncer/resources/persistentvolume/checker.go
  incubator/virtualcluster/pkg/syncer/resources/persistentvolume/controller.go
  incubator/virtualcluster/pkg/syncer/resources/persistentvolume/uws.go
  incubator/virtualcluster/pkg/syncer/resources/persistentvolumeclaim/controller.go
  incubator/virtualcluster/pkg/syncer/resources/register.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#409 [Incubator][VC]Check mccontroller cache before upward syncing Events
  incubator/virtualcluster/pkg/syncer/mccontroller/mccontroller.go
  incubator/virtualcluster/pkg/syncer/resources/event/controller.go
  incubator/virtualcluster/pkg/syncer/resources/event/uws.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#414 Update the generated role.yaml
  incubator/hnc/config/rbac/role.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#410 Add OpenCencus metrics and export to Stackdriver
  incubator/hnc/cmd/manager/main.go
  incubator/hnc/pkg/stats/metrics.go
  incubator/hnc/pkg/stats/stats.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#412 Define HNCConfiguration CR and set up a reconciler for the CR
  incubator/hnc/api/v1alpha1/hnc_config.go
  incubator/hnc/api/v1alpha1/zz_generated.deepcopy.go
  incubator/hnc/config/crd/bases/hnc.x-k8s.io_hierarchyconfigurations.yaml
  incubator/hnc/config/crd/bases/hnc.x-k8s.io_hncconfigurations.yaml
  incubator/hnc/config/crd/kustomization.yaml
  incubator/hnc/config/samples/hnc_v1_config.yaml
  incubator/hnc/pkg/config/default_config.go
  incubator/hnc/pkg/controllers/config_controller.go
  incubator/hnc/pkg/controllers/setup.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#415 [incubator][VC] support kubernetes incluster config
  incubator/virtualcluster/cmd/syncer/app/options/options.go
  incubator/virtualcluster/config/setup/sample_foo_controller.yaml
  incubator/virtualcluster/pkg/syncer/apis/config/types.go
  incubator/virtualcluster/pkg/syncer/constants/constants.go
  incubator/virtualcluster/pkg/syncer/conversion/equality.go
  incubator/virtualcluster/pkg/syncer/conversion/helper.go
  incubator/virtualcluster/pkg/syncer/conversion/mutate.go
  incubator/virtualcluster/pkg/syncer/resources/pod/dws.go
  incubator/virtualcluster/pkg/syncer/resources/pod/uws.go
  incubator/virtualcluster/pkg/syncer/resources/secret/checker.go
  incubator/virtualcluster/pkg/syncer/resources/secret/controller.go
  incubator/virtualcluster/pkg/syncer/resources/secret/dws.go
  incubator/virtualcluster/pkg/syncer/utils/string.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#417 [Incubator][VC] Add checker for namespace and configmap resources
  incubator/virtualcluster/pkg/syncer/mccontroller/mccontroller.go
  incubator/virtualcluster/pkg/syncer/resources/configmap/checker.go
  incubator/virtualcluster/pkg/syncer/resources/configmap/controller.go
  incubator/virtualcluster/pkg/syncer/resources/namespace/checker.go
  incubator/virtualcluster/pkg/syncer/resources/namespace/controller.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#420 [incubator][VC] add default opaque prefix to vc spec
  incubator/virtualcluster/pkg/syncer/cluster/cluster.go
  incubator/virtualcluster/pkg/syncer/constants/constants.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#422 [Incubator][VC] add service cidr to vc crd
  incubator/virtualcluster/config/crds/tenancy_v1alpha1_virtualcluster.yaml
  incubator/virtualcluster/pkg/apis/tenancy/v1alpha1/virtualcluster_types.go
  incubator/virtualcluster/pkg/controller/virtualcluster/master_provisioner_aliyun.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#421 [Incubator][VC]Optimize Pod creation codepath
  incubator/virtualcluster/pkg/syncer/conversion/mutate.go
  incubator/virtualcluster/pkg/syncer/resources/pod/controller.go
  incubator/virtualcluster/pkg/syncer/resources/pod/dws.go
  incubator/virtualcluster/pkg/syncer/utils/client.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#419 [Incubator][VC]Add endpoints and serviceaccount periodic checker
  incubator/virtualcluster/pkg/syncer/conversion/equality.go
  incubator/virtualcluster/pkg/syncer/mccontroller/mccontroller.go
  incubator/virtualcluster/pkg/syncer/resources/endpoints/checker.go
  incubator/virtualcluster/pkg/syncer/resources/endpoints/controller.go
  incubator/virtualcluster/pkg/syncer/resources/serviceaccount/checker.go
  incubator/virtualcluster/pkg/syncer/resources/serviceaccount/controller.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#426 [incubator][VC] fix compile error and correct vc spec
  incubator/virtualcluster/pkg/syncer/cluster/cluster.go
  incubator/virtualcluster/pkg/syncer/resources/pod/dws.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#423 [Incubator][VC]Add Service UWS and DWS update functionality
  incubator/virtualcluster/pkg/syncer/conversion/equality.go
  incubator/virtualcluster/pkg/syncer/resources/register.go
  incubator/virtualcluster/pkg/syncer/resources/service/controller.go
  incubator/virtualcluster/pkg/syncer/resources/service/dws.go
  incubator/virtualcluster/pkg/syncer/resources/service/uws.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#427 [incubator][VC] complete secret syncer
  incubator/virtualcluster/pkg/syncer/resources/pod/dws.go
  incubator/virtualcluster/pkg/syncer/resources/secret/checker.go
  incubator/virtualcluster/pkg/syncer/resources/secret/dws.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#429 [incubator][VC] fix: ep equality checker panic
  incubator/virtualcluster/pkg/syncer/conversion/equality.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#430 [Incubator][VC] Misc. Cleanups
  incubator/virtualcluster/pkg/syncer/conversion/helper.go
  incubator/virtualcluster/pkg/syncer/conversion/helper_test.go
  incubator/virtualcluster/pkg/syncer/resources/namespace/checker.go
  incubator/virtualcluster/pkg/syncer/resources/pod/controller.go
  incubator/virtualcluster/pkg/syncer/resources/pod/dws.go
  incubator/virtualcluster/pkg/syncer/resources/pod/uws.go
  incubator/virtualcluster/pkg/syncer/resources/service/controller.go
  incubator/virtualcluster/pkg/syncer/resources/service/uws.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#431 [Incubator][VC]Avoid duplicated root namespace name for virtual cluster
  incubator/virtualcluster/pkg/syncer/cluster/cluster.go
  incubator/virtualcluster/pkg/syncer/conversion/helper.go
  incubator/virtualcluster/pkg/syncer/syncer.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#418 Add all controller metrics
  incubator/hnc/cmd/manager/main.go
  incubator/hnc/go.mod
  incubator/hnc/go.sum
  incubator/hnc/pkg/stats/metrics.go
  incubator/hnc/pkg/stats/stats.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#424 Dynamically create object reconcilers for new types.
  incubator/hnc/config/samples/hnc_v1_config.yaml
  incubator/hnc/pkg/controllers/config_controller.go
  incubator/hnc/pkg/controllers/hierarchy_controller.go
  incubator/hnc/pkg/controllers/object_controller.go
  incubator/hnc/pkg/controllers/object_controller_test.go
  incubator/hnc/pkg/controllers/setup.go
  incubator/hnc/pkg/forest/forest.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#437 [Incubator][VC]Set number of dws/uws workers differently for each resource
  incubator/virtualcluster/pkg/syncer/constants/constants.go
  incubator/virtualcluster/pkg/syncer/resources/configmap/controller.go
  incubator/virtualcluster/pkg/syncer/resources/event/controller.go
  incubator/virtualcluster/pkg/syncer/resources/namespace/controller.go
  incubator/virtualcluster/pkg/syncer/resources/node/controller.go
  incubator/virtualcluster/pkg/syncer/resources/persistentvolume/controller.go
  incubator/virtualcluster/pkg/syncer/resources/persistentvolumeclaim/controller.go
  incubator/virtualcluster/pkg/syncer/resources/pod/controller.go
  incubator/virtualcluster/pkg/syncer/resources/secret/controller.go
  incubator/virtualcluster/pkg/syncer/resources/service/controller.go
  incubator/virtualcluster/pkg/syncer/resources/serviceaccount/controller.go
  incubator/virtualcluster/pkg/syncer/resources/storageclass/controller.go
  incubator/virtualcluster/pkg/syncer/syncer.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#436 [Incubator][VC]Always read synced objects from cluster cache
  incubator/virtualcluster/pkg/syncer/mccontroller/mccontroller.go
  incubator/virtualcluster/pkg/syncer/resources/event/uws.go
  incubator/virtualcluster/pkg/syncer/resources/pod/checker.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#434 [Incubator][VC]Avoid infinite retries if virtual cluster is removed
  incubator/virtualcluster/pkg/syncer/constants/constants.go
  incubator/virtualcluster/pkg/syncer/conversion/helper_test.go
  incubator/virtualcluster/pkg/syncer/mccontroller/mccontroller.go
  incubator/virtualcluster/pkg/syncer/reconciler/reconciler.go
  incubator/virtualcluster/pkg/syncer/resources/event/controller.go
  incubator/virtualcluster/pkg/syncer/resources/event/uws.go
  incubator/virtualcluster/pkg/syncer/resources/persistentvolume/controller.go
  incubator/virtualcluster/pkg/syncer/resources/persistentvolume/uws.go
  incubator/virtualcluster/pkg/syncer/resources/pod/controller.go
  incubator/virtualcluster/pkg/syncer/resources/pod/uws.go
  incubator/virtualcluster/pkg/syncer/resources/service/controller.go
  incubator/virtualcluster/pkg/syncer/resources/service/uws.go
  incubator/virtualcluster/pkg/syncer/resources/storageclass/checker.go
  incubator/virtualcluster/pkg/syncer/resources/storageclass/controller.go
  incubator/virtualcluster/pkg/syncer/resources/storageclass/uws.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#440 [Incubator][VC]implement the DeleteVirtualcluster function
  incubator/virtualcluster/pkg/controller/util/kube/util.go
  incubator/virtualcluster/pkg/controller/virtualcluster/master_provisioner_aliyun.go
  incubator/virtualcluster/pkg/controller/virtualcluster/master_provisioner_native.go
  incubator/virtualcluster/pkg/controller/virtualcluster/virtualcluster_controller.go
  incubator/virtualcluster/pkg/syncer/resources/event/uws.go
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/L

#435 Add user guide on viewing metrics in Stackdriver
  incubator/hnc/README.md
  incubator/hnc/doc/metrics/stackdriver-gke.md
Labels: approved, cncf-cla: yes, lgtm, size/L

#438 Add a unit test for config_controller.go
  incubator/hnc/pkg/controllers/config_controller_test.go
  incubator/hnc/pkg/controllers/hierarchy_controller_test.go
  incubator/hnc/pkg/controllers/object_controller_test.go
  incubator/hnc/pkg/controllers/suite_test.go
  incubator/hnc/pkg/controllers/test_helpers_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XL

#432 Add prometheus exporter
  incubator/hnc/cmd/manager/main.go
  incubator/hnc/go.mod
  incubator/hnc/go.sum
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#442 Propagate empty source object to descendants if the descendants do not have not copy of the object.
  incubator/hnc/pkg/controllers/config_controller_test.go
  incubator/hnc/pkg/controllers/object_controller.go
  incubator/hnc/pkg/controllers/object_controller_test.go
  incubator/hnc/pkg/controllers/test_helpers_test.go
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/L

#443 [incubator][VC] put the cluster nameserver in front of the pod spec one
  incubator/virtualcluster/pkg/syncer/conversion/mutate.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#444 [incubator][VC] bump to kubernetes 1.16
  incubator/virtualcluster/go.mod
  incubator/virtualcluster/go.sum
  incubator/virtualcluster/pkg/syncer/conversion/helper.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#446 [Incubator][VC]Add checker metrics for resource mismatch counts and remediation counts
  incubator/virtualcluster/pkg/syncer/metrics/metrics.go
  incubator/virtualcluster/pkg/syncer/resources/configmap/checker.go
  incubator/virtualcluster/pkg/syncer/resources/endpoints/checker.go
  incubator/virtualcluster/pkg/syncer/resources/endpoints/dws.go
  incubator/virtualcluster/pkg/syncer/resources/namespace/checker.go
  incubator/virtualcluster/pkg/syncer/resources/persistentvolume/checker.go
  incubator/virtualcluster/pkg/syncer/resources/persistentvolumeclaim/checker.go
  incubator/virtualcluster/pkg/syncer/resources/pod/checker.go
  incubator/virtualcluster/pkg/syncer/resources/secret/checker.go
  incubator/virtualcluster/pkg/syncer/resources/service/checker.go
  incubator/virtualcluster/pkg/syncer/resources/serviceaccount/checker.go
  incubator/virtualcluster/pkg/syncer/resources/storageclass/checker.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#447 Replace "controller" with "reconciler" in hnc/pkg/controllers directory
  incubator/hnc/README.md
  incubator/hnc/cmd/manager/main.go
  incubator/hnc/pkg/reconcilers/hierarchy_config.go
  incubator/hnc/pkg/reconcilers/hierarchy_config_test.go
  incubator/hnc/pkg/reconcilers/hnc_config.go
  incubator/hnc/pkg/reconcilers/hnc_config_test.go
  incubator/hnc/pkg/reconcilers/object.go
  incubator/hnc/pkg/reconcilers/object_test.go
  incubator/hnc/pkg/reconcilers/setup.go
  incubator/hnc/pkg/reconcilers/suite_test.go
  incubator/hnc/pkg/reconcilers/test_helpers_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#452 [Incubatore][VC]encode admin-kubeconfig in base64 before adding it to the annotation
  incubator/virtualcluster/cmd/manager/main.go
  incubator/virtualcluster/pkg/controller/virtualcluster/master_provisioner_aliyun.go
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/XS

#448 Create HierarchicalNamespace CRD
  incubator/hnc/api/v1alpha1/hierarchical_namespace.go
  incubator/hnc/api/v1alpha1/zz_generated.deepcopy.go
  incubator/hnc/config/crd/bases/hnc.x-k8s.io_hierarchicalnamespaces.yaml
  incubator/hnc/config/crd/kustomization.yaml
  incubator/hnc/config/samples/hnc_v1_hns.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L, ¯\_(ツ)_/¯

#451 [Incubator][VC] Add metrics to measure checker scan duration
  incubator/virtualcluster/pkg/syncer/metrics/metrics.go
  incubator/virtualcluster/pkg/syncer/resources/configmap/checker.go
  incubator/virtualcluster/pkg/syncer/resources/endpoints/checker.go
  incubator/virtualcluster/pkg/syncer/resources/namespace/checker.go
  incubator/virtualcluster/pkg/syncer/resources/node/uws.go
  incubator/virtualcluster/pkg/syncer/resources/persistentvolume/checker.go
  incubator/virtualcluster/pkg/syncer/resources/persistentvolumeclaim/checker.go
  incubator/virtualcluster/pkg/syncer/resources/pod/checker.go
  incubator/virtualcluster/pkg/syncer/resources/secret/checker.go
  incubator/virtualcluster/pkg/syncer/resources/service/checker.go
  incubator/virtualcluster/pkg/syncer/resources/serviceaccount/checker.go
  incubator/virtualcluster/pkg/syncer/resources/storageclass/checker.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#456 [Incubator][VC]Downgrade log level for INFO logs
  incubator/virtualcluster/cmd/syncer/app/options/options.go
  incubator/virtualcluster/pkg/syncer/resources/configmap/checker.go
  incubator/virtualcluster/pkg/syncer/resources/configmap/dws.go
  incubator/virtualcluster/pkg/syncer/resources/endpoints/checker.go
  incubator/virtualcluster/pkg/syncer/resources/event/uws.go
  incubator/virtualcluster/pkg/syncer/resources/namespace/checker.go
  incubator/virtualcluster/pkg/syncer/resources/namespace/dws.go
  incubator/virtualcluster/pkg/syncer/resources/node/dws.go
  incubator/virtualcluster/pkg/syncer/resources/node/uws.go
  incubator/virtualcluster/pkg/syncer/resources/persistentvolume/checker.go
  incubator/virtualcluster/pkg/syncer/resources/persistentvolumeclaim/checker.go
  incubator/virtualcluster/pkg/syncer/resources/persistentvolumeclaim/dws.go
  incubator/virtualcluster/pkg/syncer/resources/pod/checker.go
  incubator/virtualcluster/pkg/syncer/resources/pod/dws.go
  incubator/virtualcluster/pkg/syncer/resources/pod/uws.go
  incubator/virtualcluster/pkg/syncer/resources/secret/checker.go
  incubator/virtualcluster/pkg/syncer/resources/secret/dws.go
  incubator/virtualcluster/pkg/syncer/resources/service/checker.go
  incubator/virtualcluster/pkg/syncer/resources/service/dws.go
  incubator/virtualcluster/pkg/syncer/resources/serviceaccount/checker.go
  incubator/virtualcluster/pkg/syncer/resources/serviceaccount/dws.go
  incubator/virtualcluster/pkg/syncer/resources/storageclass/checker.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#455 Create the empty HierarchicalNamespaceReconciler
  incubator/hnc/api/v1alpha1/hierarchical_namespace.go
  incubator/hnc/config/crd/bases/hnc.x-k8s.io_hierarchicalnamespaces.yaml
  incubator/hnc/pkg/reconcilers/hierarchical_namespace.go
  incubator/hnc/pkg/reconcilers/hierarchy_config.go
  incubator/hnc/pkg/reconcilers/hnc_config.go
  incubator/hnc/pkg/reconcilers/object.go
  incubator/hnc/pkg/reconcilers/setup.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#461 [Incubator][VC] don't create default ns on super for tenant
  incubator/virtualcluster/pkg/controller/virtualcluster/master_provisioner_native.go
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/M

#463 [Incubator][VC]Fix a small bug on handling WaitForCache failure.
  incubator/virtualcluster/pkg/syncer/syncer.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#460 Add `kubectl hns create2` to only create hns in parent namespace
  incubator/hnc/api/v1alpha1/hierarchical_namespace.go
  incubator/hnc/api/v1alpha1/hierarchy_types.go
  incubator/hnc/pkg/kubectl/create2.go
  incubator/hnc/pkg/kubectl/root.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#464 [Incubator][VC]Make DWS request only contain immutable fields
  incubator/virtualcluster/pkg/syncer/cluster/cluster.go
  incubator/virtualcluster/pkg/syncer/handler/enqueue_object.go
  incubator/virtualcluster/pkg/syncer/mccontroller/mccontroller.go
  incubator/virtualcluster/pkg/syncer/reconciler/reconciler.go
  incubator/virtualcluster/pkg/syncer/resources/configmap/dws.go
  incubator/virtualcluster/pkg/syncer/resources/endpoints/dws.go
  incubator/virtualcluster/pkg/syncer/resources/namespace/checker.go
  incubator/virtualcluster/pkg/syncer/resources/namespace/dws.go
  incubator/virtualcluster/pkg/syncer/resources/node/dws.go
  incubator/virtualcluster/pkg/syncer/resources/persistentvolumeclaim/dws.go
  incubator/virtualcluster/pkg/syncer/resources/pod/checker.go
  incubator/virtualcluster/pkg/syncer/resources/pod/controller.go
  incubator/virtualcluster/pkg/syncer/resources/pod/dws.go
  incubator/virtualcluster/pkg/syncer/resources/pod/uws.go
  incubator/virtualcluster/pkg/syncer/resources/secret/dws.go
  incubator/virtualcluster/pkg/syncer/resources/service/checker.go
  incubator/virtualcluster/pkg/syncer/resources/service/dws.go
  incubator/virtualcluster/pkg/syncer/resources/service/uws.go
  incubator/virtualcluster/pkg/syncer/resources/serviceaccount/dws.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#468 Create a flag to toggle HC and HNS Reconcilers
  incubator/hnc/cmd/manager/main.go
  incubator/hnc/pkg/reconcilers/hierarchy_config.go
  incubator/hnc/pkg/reconcilers/setup.go
  incubator/hnc/pkg/reconcilers/suite_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#470 [Incubator][VC] shorten the pod syncing latency
  incubator/virtualcluster/pkg/syncer/resources/pod/uws.go
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/S

#472 [Incubator][VC] apply leaderelection feature to vc-manager
  incubator/virtualcluster/cmd/manager/main.go
  incubator/virtualcluster/config/setup/all_in_one.yaml
  incubator/virtualcluster/config/setup/all_in_one_aliyun.yaml
  incubator/virtualcluster/pkg/controller/virtualcluster/master_provisioner_native.go
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/M
