Repository kubernetes-sigs/multi-tenancy, pull requests merged in 2021-03, with the labels that each got.

#1417 [VC] update vnode daemon port during heartbeats
  incubator/virtualcluster/pkg/syncer/resources/node/uws.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1418 [VC] fix: only check known cluster in differ
  incubator/virtualcluster/pkg/syncer/patrol/differ/handler.go
  incubator/virtualcluster/pkg/syncer/resources/configmap/checker.go
  incubator/virtualcluster/pkg/syncer/resources/endpoints/checker.go
  incubator/virtualcluster/pkg/syncer/resources/namespace/checker.go
  incubator/virtualcluster/pkg/syncer/resources/persistentvolumeclaim/checker.go
  incubator/virtualcluster/pkg/syncer/resources/pod/checker.go
  incubator/virtualcluster/pkg/syncer/resources/service/checker.go
  incubator/virtualcluster/pkg/syncer/resources/serviceaccount/checker.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1416 Adding CRD UW synchronization
  incubator/virtualcluster/cmd/syncer/app/options/options.go
  incubator/virtualcluster/cmd/syncer/builtins_extra.go
  incubator/virtualcluster/go.mod
  incubator/virtualcluster/go.sum
  incubator/virtualcluster/pkg/syncer/conversion/equality.go
  incubator/virtualcluster/pkg/syncer/conversion/helper.go
  incubator/virtualcluster/pkg/syncer/resources/crd/checker.go
  incubator/virtualcluster/pkg/syncer/resources/crd/controller.go
  incubator/virtualcluster/pkg/syncer/resources/crd/uws.go
  incubator/virtualcluster/pkg/syncer/resources/priorityclass/checker.go
  incubator/virtualcluster/pkg/syncer/resources/priorityclass/controller.go
  incubator/virtualcluster/pkg/util/cluster/cluster.go
  incubator/virtualcluster/pkg/util/mccontroller/mccontroller.go
  incubator/virtualcluster/pkg/vn-agent/server/test/go.sum
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/XXL

#1422 [VC] cleanup: code format
  incubator/virtualcluster/go.mod
  incubator/virtualcluster/go.sum
  incubator/virtualcluster/pkg/syncer/resources/crd/checker.go
  incubator/virtualcluster/pkg/syncer/resources/crd/controller.go
  incubator/virtualcluster/pkg/syncer/resources/crd/uws.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#1426 [VC] support command options `--tail` for `kubectl logs`
  incubator/virtualcluster/pkg/vn-agent/server/translate.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1425 HNC: redirect stdlib logger output through zap
  incubator/hnc/cmd/manager/main.go
  incubator/hnc/go.mod
  incubator/hnc/go.sum
  incubator/hnc/vendor/modules.txt
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#1428 [VC] Finishing superclusterpooling feature gate comment
  incubator/virtualcluster/pkg/syncer/util/featuregate/gate.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1423 Export checkDWObjectMetaEquality for custom resource syncer (Add an example custom resource syncer)
  incubator/virtualcluster/pkg/syncer/conversion/equality.go
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/S

#1429 [VC] Adding support for vn-agent to have featuregates via flags
  incubator/virtualcluster/cmd/syncer/app/options/options.go
  incubator/virtualcluster/cmd/syncer/builtins_extra.go
  incubator/virtualcluster/cmd/vn-agent/app/options/options.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#1431 [VC] Use event sinker in mccontroller
  incubator/virtualcluster/experiment/pkg/scheduler/resource/virtualcluster/namespace/controller.go
  incubator/virtualcluster/experiment/pkg/scheduler/resource/virtualcluster/pod/controller.go
  incubator/virtualcluster/pkg/syncer/resources/pod/dws.go
  incubator/virtualcluster/pkg/util/mccontroller/mccontroller.go
  incubator/virtualcluster/pkg/util/record/event.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1433 Restrict recreate-on-failed-update semantics to Rolebindings
  incubator/hnc/internal/reconcilers/object.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#1438 Update OWNERS to include yiqigao217
  OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1439 Add e2e test for quickstart exceptions
  incubator/hnc/docs/user-guide/quickstart.md
  incubator/hnc/test/e2e/quickstart_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1440 Add reinstall kubebuilder info in test and README
  incubator/hnc/Makefile
  incubator/hnc/README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1441 syncer: add option to disable service links
  incubator/virtualcluster/cmd/syncer/app/options/options.go
  incubator/virtualcluster/pkg/syncer/apis/config/types.go
  incubator/virtualcluster/pkg/syncer/conversion/mutate.go
  incubator/virtualcluster/pkg/syncer/resources/pod/dws.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#1442 [VC] add support for all kubectl logs options
  incubator/virtualcluster/pkg/vn-agent/server/translate.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#1445 [VC] fix the exec command missing bug
  incubator/virtualcluster/pkg/vn-agent/server/translate.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#1447 [VC] Add VC ICDCS paper link to README
  incubator/virtualcluster/README.md
  incubator/virtualcluster/doc/vc-icdcs.pdf
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1446 [VC] syncer: introduce meta cluster
  incubator/virtualcluster/cmd/syncer/app/config/config.go
  incubator/virtualcluster/cmd/syncer/app/options/options.go
  incubator/virtualcluster/cmd/syncer/app/server.go
  incubator/virtualcluster/pkg/syncer/apis/config/types.go
  incubator/virtualcluster/pkg/syncer/syncer.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1450 [VC] docs: add clusterpooling demo instruction
  incubator/virtualcluster/doc/clusterpooling-demo.md
  incubator/virtualcluster/experiment/config/setup/all_in_one.yaml
  incubator/virtualcluster/experiment/config/setup/cluster-id.yaml.sed
  incubator/virtualcluster/experiment/config/setup/create-cluster-minikube.sh
  incubator/virtualcluster/experiment/config/setup/deploy-cluster-id.sh
  incubator/virtualcluster/experiment/config/setup/deploy-syncer.sh
  incubator/virtualcluster/experiment/config/setup/syncer.yaml.sed
Labels: approved, cncf-cla: yes, lgtm, size/XL

#1452 [VC] Revise SuperClusterPooling demo
  incubator/virtualcluster/doc/clusterpooling-demo.md
  incubator/virtualcluster/doc/demo-arch.png
  incubator/virtualcluster/experiment/config/setup/setup-supercluster-minikube.sh
Labels: approved, cncf-cla: yes, lgtm, size/L

#1453 [VC] Sync cache when new Cluster or VC CR is created
  incubator/virtualcluster/experiment/config/setup/setup-supercluster-minikube.sh
  incubator/virtualcluster/experiment/config/setup/syncer.yaml.sed
  incubator/virtualcluster/experiment/pkg/scheduler/reconciler.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#1454 [VC] Using labels for super.public crds
  incubator/virtualcluster/pkg/syncer/resources/crd/controller.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1455 [vc] cleaning logging in extra syncers
  incubator/virtualcluster/pkg/syncer/resources/crd/checker.go
  incubator/virtualcluster/pkg/syncer/resources/priorityclass/checker.go
Labels: approved, cncf-cla: yes, lgtm, size/XS
