Repository kubernetes-sigs/multi-tenancy, pull requests merged in 2021-02, with the labels that each got.

#1369 Create e2e test image for Prow
  incubator/hnc/hack/prow-e2e/Dockerfile
  incubator/hnc/hack/prow-e2e/Makefile
  incubator/hnc/hack/prow-e2e/README.md
  incubator/hnc/hack/prow-e2e/run-e2e.sh
Labels: approved, cncf-cla: yes, lgtm, size/L

#1370 HNC: Add MustNotApplyYAML() func to testutils package
  incubator/hnc/pkg/testutils/testutils.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#1368 [VC] Initialize scheduler cache
  incubator/virtualcluster/experiment/cmd/scheduler/app/server.go
  incubator/virtualcluster/experiment/pkg/scheduler/cache/cluster.go
  incubator/virtualcluster/experiment/pkg/scheduler/constants/constants.go
  incubator/virtualcluster/experiment/pkg/scheduler/reconciler.go
  incubator/virtualcluster/experiment/pkg/scheduler/scheduler.go
  incubator/virtualcluster/experiment/pkg/scheduler/util/helper.go
  incubator/virtualcluster/experiment/pkg/scheduler/util/helper_test.go
  incubator/virtualcluster/pkg/util/constants/constants.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#1355 Changes detect namespace deletion into object validator
  incubator/hnc/internal/forest/namespace.go
  incubator/hnc/internal/reconcilers/hierarchy_config.go
  incubator/hnc/internal/validators/object.go
  incubator/hnc/internal/validators/object_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#1374 [VC] pluggable syncer
  incubator/virtualcluster/cmd/syncer/app/server.go
  incubator/virtualcluster/cmd/syncer/builtins.go
  incubator/virtualcluster/cmd/syncer/builtins_extra.go
  incubator/virtualcluster/pkg/syncer/manager/manager.go
  incubator/virtualcluster/pkg/syncer/patrol/patroller.go
  incubator/virtualcluster/pkg/syncer/resources/configmap/checker.go
  incubator/virtualcluster/pkg/syncer/resources/configmap/controller.go
  incubator/virtualcluster/pkg/syncer/resources/configmap/dws.go
  incubator/virtualcluster/pkg/syncer/resources/endpoints/checker.go
  incubator/virtualcluster/pkg/syncer/resources/endpoints/controller.go
  incubator/virtualcluster/pkg/syncer/resources/endpoints/dws.go
  incubator/virtualcluster/pkg/syncer/resources/event/controller.go
  incubator/virtualcluster/pkg/syncer/resources/event/uws.go
  incubator/virtualcluster/pkg/syncer/resources/ingress/checker.go
  incubator/virtualcluster/pkg/syncer/resources/ingress/controller.go
  incubator/virtualcluster/pkg/syncer/resources/ingress/dws.go
  incubator/virtualcluster/pkg/syncer/resources/ingress/uws.go
  incubator/virtualcluster/pkg/syncer/resources/namespace/checker.go
  incubator/virtualcluster/pkg/syncer/resources/namespace/controller.go
  incubator/virtualcluster/pkg/syncer/resources/namespace/dws.go
  incubator/virtualcluster/pkg/syncer/resources/node/controller.go
  incubator/virtualcluster/pkg/syncer/resources/node/dws.go
  incubator/virtualcluster/pkg/syncer/resources/node/uws.go
  incubator/virtualcluster/pkg/syncer/resources/persistentvolume/checker.go
  incubator/virtualcluster/pkg/syncer/resources/persistentvolume/controller.go
  incubator/virtualcluster/pkg/syncer/resources/persistentvolume/uws.go
  incubator/virtualcluster/pkg/syncer/resources/persistentvolumeclaim/checker.go
  incubator/virtualcluster/pkg/syncer/resources/persistentvolumeclaim/controller.go
  incubator/virtualcluster/pkg/syncer/resources/persistentvolumeclaim/dws.go
  incubator/virtualcluster/pkg/syncer/resources/pod/checker.go
  incubator/virtualcluster/pkg/syncer/resources/pod/controller.go
  incubator/virtualcluster/pkg/syncer/resources/pod/dws.go
  incubator/virtualcluster/pkg/syncer/resources/pod/uws.go
  incubator/virtualcluster/pkg/syncer/resources/priorityclass/checker.go
  incubator/virtualcluster/pkg/syncer/resources/priorityclass/controller.go
  incubator/virtualcluster/pkg/syncer/resources/priorityclass/uws.go
  incubator/virtualcluster/pkg/syncer/resources/register.go
  incubator/virtualcluster/pkg/syncer/resources/secret/checker.go
  incubator/virtualcluster/pkg/syncer/resources/secret/controller.go
  incubator/virtualcluster/pkg/syncer/resources/secret/dws.go
  incubator/virtualcluster/pkg/syncer/resources/service/checker.go
  incubator/virtualcluster/pkg/syncer/resources/service/controller.go
  incubator/virtualcluster/pkg/syncer/resources/service/dws.go
  incubator/virtualcluster/pkg/syncer/resources/service/uws.go
  incubator/virtualcluster/pkg/syncer/resources/serviceaccount/checker.go
  incubator/virtualcluster/pkg/syncer/resources/serviceaccount/controller.go
  incubator/virtualcluster/pkg/syncer/resources/serviceaccount/dws.go
  incubator/virtualcluster/pkg/syncer/resources/storageclass/checker.go
  incubator/virtualcluster/pkg/syncer/resources/storageclass/controller.go
  incubator/virtualcluster/pkg/syncer/resources/storageclass/uws.go
  incubator/virtualcluster/pkg/syncer/syncer.go
  incubator/virtualcluster/pkg/syncer/util/test/runDWS.go
  incubator/virtualcluster/pkg/syncer/util/test/runPatrol.go
  incubator/virtualcluster/pkg/syncer/util/test/runUWS.go
  incubator/virtualcluster/pkg/syncer/uwcontroller/uwcontroller.go
  incubator/virtualcluster/pkg/util/mccontroller/mccontroller.go
  incubator/virtualcluster/pkg/util/plugin/context.go
  incubator/virtualcluster/pkg/util/plugin/plugin.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#1375 [VC] Retry synchronizing cluster state and allow updating existing objects
  incubator/virtualcluster/experiment/pkg/scheduler/cache/cache.go
  incubator/virtualcluster/experiment/pkg/scheduler/cache/cache_test.go
  incubator/virtualcluster/experiment/pkg/scheduler/cache/cluster.go
  incubator/virtualcluster/experiment/pkg/scheduler/constants/constants.go
  incubator/virtualcluster/experiment/pkg/scheduler/reconciler.go
  incubator/virtualcluster/experiment/pkg/scheduler/scheduler.go
  incubator/virtualcluster/experiment/pkg/scheduler/util/helper.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1373 upgrade cert-controller and set restartOnSecretRefresh
  incubator/hnc/cmd/manager/main.go
  incubator/hnc/go.mod
  incubator/hnc/go.sum
  incubator/hnc/internal/validators/setup.go
  incubator/hnc/vendor/github.com/open-policy-agent/cert-controller/pkg/rotator/rotator.go
  incubator/hnc/vendor/modules.txt
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#1378 [VC] Add supercluster namespace resource reconciling framework
  incubator/virtualcluster/experiment/cmd/scheduler/app/server.go
  incubator/virtualcluster/experiment/cmd/scheduler/superclusterresources.go
  incubator/virtualcluster/experiment/pkg/scheduler/manager/manager.go
  incubator/virtualcluster/experiment/pkg/scheduler/resource/supercluster/namespace/controller.go
  incubator/virtualcluster/experiment/pkg/scheduler/resource/supercluster/register.go
  incubator/virtualcluster/experiment/pkg/scheduler/scheduler.go
  incubator/virtualcluster/pkg/syncer/resources/configmap/controller.go
  incubator/virtualcluster/pkg/syncer/resources/endpoints/controller.go
  incubator/virtualcluster/pkg/syncer/resources/event/controller.go
  incubator/virtualcluster/pkg/syncer/resources/ingress/controller.go
  incubator/virtualcluster/pkg/syncer/resources/namespace/controller.go
  incubator/virtualcluster/pkg/syncer/resources/node/controller.go
  incubator/virtualcluster/pkg/syncer/resources/persistentvolume/controller.go
  incubator/virtualcluster/pkg/syncer/resources/persistentvolumeclaim/controller.go
  incubator/virtualcluster/pkg/syncer/resources/pod/controller.go
  incubator/virtualcluster/pkg/syncer/resources/priorityclass/controller.go
  incubator/virtualcluster/pkg/syncer/resources/secret/controller.go
  incubator/virtualcluster/pkg/syncer/resources/service/controller.go
  incubator/virtualcluster/pkg/syncer/resources/serviceaccount/controller.go
  incubator/virtualcluster/pkg/syncer/resources/storageclass/controller.go
  incubator/virtualcluster/pkg/syncer/syncer.go
  incubator/virtualcluster/pkg/util/plugin/plugin.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1379 [VC] Add provision results in scheduler cluster state
  incubator/virtualcluster/experiment/pkg/scheduler/cache/cache.go
  incubator/virtualcluster/experiment/pkg/scheduler/cache/cluster.go
  incubator/virtualcluster/experiment/pkg/scheduler/cache/cluster_test.go
  incubator/virtualcluster/experiment/pkg/scheduler/cache/namespace.go
  incubator/virtualcluster/experiment/pkg/scheduler/util/helper.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1380 [VC] Add supercluster namespace reconciler
  incubator/virtualcluster/experiment/pkg/scheduler/cache/cache.go
  incubator/virtualcluster/experiment/pkg/scheduler/cache/cluster.go
  incubator/virtualcluster/experiment/pkg/scheduler/cache/interface.go
  incubator/virtualcluster/experiment/pkg/scheduler/constants/constants.go
  incubator/virtualcluster/experiment/pkg/scheduler/reconciler.go
  incubator/virtualcluster/experiment/pkg/scheduler/resource/supercluster/namespace/controller.go
  incubator/virtualcluster/experiment/pkg/scheduler/scheduler.go
  incubator/virtualcluster/experiment/pkg/scheduler/util/helper.go
  incubator/virtualcluster/pkg/util/cluster/cluster.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1376 Replace deprecated 'NewGomegaWithT' with 'NewWithT'
  incubator/hnc/internal/forest/namespacestructure_test.go
  incubator/hnc/internal/object/object_test.go
  incubator/hnc/internal/validators/anchor_test.go
  incubator/hnc/internal/validators/hierarchy_test.go
  incubator/hnc/internal/validators/hncconfig_test.go
  incubator/hnc/internal/validators/namespace_test.go
  incubator/hnc/internal/validators/object_test.go
  incubator/hnc/test/e2e/quickstart_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#1382 [VC] fix minor bug in cluster cache copy
  incubator/virtualcluster/experiment/pkg/scheduler/cache/cluster.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1381 [VC] Add cache dump functionality
  incubator/virtualcluster/experiment/pkg/scheduler/cache/cache.go
  incubator/virtualcluster/experiment/pkg/scheduler/cache/cluster.go
  incubator/virtualcluster/experiment/pkg/scheduler/cache/interface.go
  incubator/virtualcluster/experiment/pkg/scheduler/cache/namespace.go
  incubator/virtualcluster/experiment/pkg/scheduler/scheduler.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1384 [VC] Add health check and update super cluster capacity periodically
  incubator/virtualcluster/experiment/cmd/scheduler/app/server.go
  incubator/virtualcluster/experiment/pkg/scheduler/cache/cache.go
  incubator/virtualcluster/experiment/pkg/scheduler/cache/cluster.go
  incubator/virtualcluster/experiment/pkg/scheduler/cache/interface.go
  incubator/virtualcluster/experiment/pkg/scheduler/health.go
  incubator/virtualcluster/experiment/pkg/scheduler/metrics/metrics.go
  incubator/virtualcluster/experiment/pkg/scheduler/scheduler.go
  incubator/virtualcluster/experiment/pkg/scheduler/util/helper.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1387 Update README with more Prow info
  incubator/hnc/README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1385 [VC] Add virtualcluster resource reconciler and introduce SchedulerEngine
  incubator/virtualcluster/experiment/cmd/scheduler/virtualclusterresource.go
  incubator/virtualcluster/experiment/pkg/scheduler/cache/cache.go
  incubator/virtualcluster/experiment/pkg/scheduler/constants/constants.go
  incubator/virtualcluster/experiment/pkg/scheduler/engine/schedulerengine.go
  incubator/virtualcluster/experiment/pkg/scheduler/manager/manager.go
  incubator/virtualcluster/experiment/pkg/scheduler/resource/supercluster/namespace/controller.go
  incubator/virtualcluster/experiment/pkg/scheduler/resource/virtualcluster/namespace/controller.go
  incubator/virtualcluster/experiment/pkg/scheduler/resource/virtualcluster/register.go
  incubator/virtualcluster/experiment/pkg/scheduler/resource/virtualcluster/resourcequota/controller.go
  incubator/virtualcluster/experiment/pkg/scheduler/scheduler.go
  incubator/virtualcluster/experiment/pkg/scheduler/util/helper.go
  incubator/virtualcluster/experiment/pkg/scheduler/util/helper_test.go
  incubator/virtualcluster/pkg/util/mccontroller/mccontroller.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1393 [VC] Adding capi generated type
  incubator/virtualcluster/config/crds/cluster.x-k8s.io_clusters.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#1395 [VC] Adding super cluster networking feature
  incubator/virtualcluster/cmd/syncer/app/options/options.go
  incubator/virtualcluster/pkg/syncer/conversion/helper.go
  incubator/virtualcluster/pkg/syncer/conversion/helper_test.go
  incubator/virtualcluster/pkg/syncer/conversion/mutate.go
  incubator/virtualcluster/pkg/syncer/resources/pod/dws.go
  incubator/virtualcluster/pkg/syncer/util/featuregate/gate.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1390 [VC] Implement major workflows in SchedulerEngine
  incubator/virtualcluster/experiment/pkg/scheduler/algorithm/types.go
  incubator/virtualcluster/experiment/pkg/scheduler/cache/cache.go
  incubator/virtualcluster/experiment/pkg/scheduler/cache/cache_test.go
  incubator/virtualcluster/experiment/pkg/scheduler/cache/cluster_test.go
  incubator/virtualcluster/experiment/pkg/scheduler/cache/interface.go
  incubator/virtualcluster/experiment/pkg/scheduler/cache/namespace.go
  incubator/virtualcluster/experiment/pkg/scheduler/engine/schedulerengine.go
  incubator/virtualcluster/experiment/pkg/scheduler/engine/schedulerengine_test.go
  incubator/virtualcluster/experiment/pkg/scheduler/resource/virtualcluster/namespace/controller.go
  incubator/virtualcluster/experiment/pkg/scheduler/util/helper.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1396 Fix Docker-in-Docker and image name
  incubator/hnc/hack/prow-e2e/Dockerfile
  incubator/hnc/hack/prow-e2e/Makefile
  incubator/hnc/hack/prow-e2e/README.md
  incubator/hnc/hack/prow-e2e/run-e2e-tests.sh
Labels: approved, cncf-cla: yes, lgtm, size/M

#1389 VC: selective consistency ns checks
  incubator/virtualcluster/pkg/syncer/patrol/differ/handler.go
  incubator/virtualcluster/pkg/syncer/resources/configmap/checker.go
  incubator/virtualcluster/pkg/syncer/resources/namespace/checker.go
  incubator/virtualcluster/pkg/syncer/resources/namespace/checker_test.go
  incubator/virtualcluster/pkg/syncer/resources/namespace/dws_test.go
  incubator/virtualcluster/pkg/syncer/util/featuregate/gate.go
  incubator/virtualcluster/pkg/syncer/util/test/featuregate.go
  incubator/virtualcluster/pkg/syncer/util/test/runDWS.go
  incubator/virtualcluster/pkg/syncer/util/test/runUWS.go
  incubator/virtualcluster/pkg/util/mccontroller/mccontroller.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1400 [VC] cleanup: add cache test
  incubator/virtualcluster/experiment/pkg/scheduler/cache/cache.go
  incubator/virtualcluster/experiment/pkg/scheduler/cache/cluster.go
  incubator/virtualcluster/experiment/pkg/scheduler/cache/cluster_test.go
  incubator/virtualcluster/experiment/pkg/scheduler/cache/namespace.go
  incubator/virtualcluster/experiment/pkg/scheduler/cache/namespace_test.go
  incubator/virtualcluster/experiment/pkg/scheduler/engine/schedulerengine.go
  incubator/virtualcluster/experiment/pkg/scheduler/resource/virtualcluster/namespace/controller.go
  incubator/virtualcluster/experiment/pkg/scheduler/util/helper.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1399 [VC] Update SchedulerCache when vc or cluster CRs are added/removed
  incubator/virtualcluster/experiment/pkg/scheduler/cache/cache.go
  incubator/virtualcluster/experiment/pkg/scheduler/cache/cache_test.go
  incubator/virtualcluster/experiment/pkg/scheduler/cache/cluster.go
  incubator/virtualcluster/experiment/pkg/scheduler/cache/interface.go
  incubator/virtualcluster/experiment/pkg/scheduler/reconciler.go
  incubator/virtualcluster/experiment/pkg/scheduler/util/helper.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1401 [VC] Snapshot schedulercache for namespace scheduling
  incubator/virtualcluster/experiment/pkg/scheduler/cache/cache.go
  incubator/virtualcluster/experiment/pkg/scheduler/cache/interface.go
  incubator/virtualcluster/experiment/pkg/scheduler/cache/snapshot.go
  incubator/virtualcluster/experiment/pkg/scheduler/cache/snapshot_test.go
  incubator/virtualcluster/experiment/pkg/scheduler/engine/schedulerengine.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1402 [VC] Fix a broken UT
  incubator/virtualcluster/experiment/pkg/scheduler/cache/snapshot_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1403 [VC] refactor ep, pv, pvc checker by differ
  incubator/virtualcluster/pkg/syncer/resources/endpoints/checker.go
  incubator/virtualcluster/pkg/syncer/resources/persistentvolume/checker.go
  incubator/virtualcluster/pkg/syncer/resources/persistentvolumeclaim/checker.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1407 [VC] refactor pod, service, serviceaccount checker by differ
  incubator/virtualcluster/pkg/syncer/resources/persistentvolume/checker.go
  incubator/virtualcluster/pkg/syncer/resources/pod/checker.go
  incubator/virtualcluster/pkg/syncer/resources/pod/checker_test.go
  incubator/virtualcluster/pkg/syncer/resources/service/checker.go
  incubator/virtualcluster/pkg/syncer/resources/serviceaccount/checker.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#1406 [VC] Add simple first fit namespace scheduling algorithm
  incubator/virtualcluster/experiment/pkg/scheduler/algorithm/namespacesched.go
  incubator/virtualcluster/experiment/pkg/scheduler/cache/snapshot.go
  incubator/virtualcluster/experiment/pkg/scheduler/engine/schedulerengine.go
  incubator/virtualcluster/experiment/pkg/scheduler/resource/virtualcluster/namespace/controller.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1398 Attempt to fix HNC postsubmits
  incubator/hnc/hack/prow-e2e/Dockerfile
  incubator/hnc/hack/prow-e2e/Makefile
  incubator/hnc/hack/prow-e2e/run-e2e-tests.sh
Labels: approved, cncf-cla: yes, lgtm, size/S

#1408 [HNC] Add envvar printout for debugging
  incubator/hnc/hack/prow-e2e/Dockerfile
  incubator/hnc/hack/prow-e2e/run-e2e-tests.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1411 Get rid of now-mostly-wrong readme
  incubator/hnc/hack/prow-e2e/README.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#1412 Get rid of special-purpose Prow image
  incubator/hnc/hack/Makefile
  incubator/hnc/hack/README.md
  incubator/hnc/hack/prow-e2e/Dockerfile
  incubator/hnc/hack/prow-e2e/Makefile
  incubator/hnc/hack/prow-e2e/README.md
  incubator/hnc/hack/prow-e2e/run-e2e-tests.sh
  incubator/hnc/hack/prow-run-e2e.sh
Labels: approved, cncf-cla: yes, lgtm, size/L

#1409 [VC] Add README.md for the experiment feature
  incubator/virtualcluster/README.md
  incubator/virtualcluster/experiment/README.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#1414 [VC] Make UID in reconcile request optional
  incubator/virtualcluster/experiment/pkg/scheduler/resource/supercluster/namespace/controller.go
  incubator/virtualcluster/experiment/pkg/scheduler/resource/virtualcluster/namespace/controller.go
  incubator/virtualcluster/experiment/pkg/scheduler/resource/virtualcluster/resourcequota/controller.go
  incubator/virtualcluster/pkg/syncer/manager/manager.go
  incubator/virtualcluster/pkg/util/handler/enqueue_object.go
  incubator/virtualcluster/pkg/util/handler/enqueue_object_test.go
  incubator/virtualcluster/pkg/util/listener/adapter.go
  incubator/virtualcluster/pkg/util/mccontroller/mccontroller.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#1415 [VC] Clean up: Remove UID from Pod in scheduler cache
  incubator/virtualcluster/experiment/pkg/scheduler/cache/cluster_test.go
  incubator/virtualcluster/experiment/pkg/scheduler/cache/pod.go
  incubator/virtualcluster/experiment/pkg/scheduler/engine/schedulerengine.go
  incubator/virtualcluster/experiment/pkg/scheduler/resource/virtualcluster/pod/controller.go
  incubator/virtualcluster/experiment/pkg/scheduler/util/helper.go
Labels: approved, cncf-cla: yes, lgtm, size/S
