Repository kubernetes-sigs/multi-tenancy, pull requests merged in 2021-04, with the labels that each got.

#1456 [VC] Fix vNodeGC and Pod checker bugs when enabling SuperClusterPooling feature
  incubator/virtualcluster/pkg/syncer/constants/constants.go
  incubator/virtualcluster/pkg/syncer/resources/pod/checker.go
  incubator/virtualcluster/pkg/syncer/vnode/vnode.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#1457 Do not remove/update un-Labled resources in virtual cluster
  incubator/virtualcluster/pkg/syncer/resources/crd/checker.go
  incubator/virtualcluster/pkg/syncer/resources/priorityclass/checker.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1458 [VC] Add demo link to experimental scheduler README.md
  incubator/virtualcluster/experiment/README.md
  incubator/virtualcluster/experiment/doc/demo-arch.png
  incubator/virtualcluster/experiment/doc/demo.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1459 [vc] Remove more logs from CRD Syncer
  incubator/virtualcluster/pkg/syncer/resources/crd/controller.go
  incubator/virtualcluster/pkg/syncer/resources/crd/uws.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#1461 add non-public tenant priorityclass testcases
  incubator/virtualcluster/pkg/syncer/resources/priorityclass/checker_test.go
  incubator/virtualcluster/pkg/syncer/resources/priorityclass/uws_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1463 Add Readme to explain how to build custom resource syncer (2)
  incubator/virtualcluster/doc/customresource-syncer.md
  incubator/virtualcluster/doc/images/cr-syncer.png
Labels: approved, cncf-cla: yes, lgtm, size/L

#1464 [VC] Remove namespace placement result when quota is deleted
  incubator/virtualcluster/experiment/pkg/scheduler/resource/virtualcluster/namespace/controller.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1465 [VC] Add Namespace update synchronization for scheduling placement
  incubator/virtualcluster/experiment/doc/demo.md
  incubator/virtualcluster/pkg/syncer/conversion/equality.go
  incubator/virtualcluster/pkg/syncer/resources/namespace/checker.go
  incubator/virtualcluster/pkg/syncer/resources/namespace/dws.go
  incubator/virtualcluster/pkg/util/constants/constants.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1444 Make excluded namespace configurable
  incubator/hnc/api/v1alpha2/hierarchy_types.go
  incubator/hnc/cmd/manager/main.go
  incubator/hnc/config/manager/manager.yaml
  incubator/hnc/config/webhook/manifests.yaml
  incubator/hnc/config/webhook/webhook_patch.yaml
  incubator/hnc/docs/user-guide/concepts.md
  incubator/hnc/internal/config/default_config.go
  incubator/hnc/internal/reconcilers/anchor.go
  incubator/hnc/internal/reconcilers/anchor_test.go
  incubator/hnc/internal/reconcilers/hierarchy_config.go
  incubator/hnc/internal/reconcilers/hierarchy_config_test.go
  incubator/hnc/internal/reconcilers/object.go
  incubator/hnc/internal/validators/anchor.go
  incubator/hnc/internal/validators/anchor_test.go
  incubator/hnc/internal/validators/hierarchy.go
  incubator/hnc/internal/validators/hierarchy_test.go
  incubator/hnc/internal/validators/namespace.go
  incubator/hnc/internal/validators/namespace_test.go
  incubator/hnc/internal/validators/object.go
  incubator/hnc/test/e2e/issues_test.go
  incubator/hnc/test/e2e/rolebinding_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1468 [VC] Fix a small figure problem in the paper
  incubator/virtualcluster/doc/vc-icdcs.pdf
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1469 [VC] Get services of default namespace from tenant when enabling SuperClusterPooling
  incubator/virtualcluster/pkg/syncer/conversion/helper.go
  incubator/virtualcluster/pkg/syncer/conversion/mutate.go
  incubator/virtualcluster/pkg/syncer/resources/pod/dws.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1471 Remove the hack for unserved versions in envtest
  incubator/hnc/Makefile
  incubator/hnc/hack/crd_patches/ensure-all-served-for-envtest.sh
  incubator/hnc/internal/reconcilers/suite_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#1472 Document excluded namespace configuration only available after v0.8
  incubator/hnc/docs/user-guide/concepts.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1477 Ensure setting 'Missing' anchor state when ns cannot create
  incubator/hnc/internal/reconcilers/anchor.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1481 Ensure excluded-namespaces are properly configured before e2e tests
  incubator/hnc/Makefile
  incubator/hnc/README.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#1485 Exclude namespaces before deploying HNC
  incubator/hnc/Makefile
Labels: approved, cncf-cla: yes, lgtm, size/S

#1483 Handle bypassed webhook rules on excluded namespaces
  incubator/hnc/api/v1alpha2/hierarchy_types.go
  incubator/hnc/internal/kubectl/describe.go
  incubator/hnc/internal/kubectl/root.go
  incubator/hnc/internal/reconcilers/anchor.go
  incubator/hnc/internal/reconcilers/anchor_test.go
  incubator/hnc/internal/reconcilers/hierarchy_config.go
  incubator/hnc/internal/reconcilers/hierarchy_config_test.go
  incubator/hnc/internal/reconcilers/test_helpers_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1490 Allow builtin 'admin' role to manage HNC objects
  incubator/hnc/config/rbac/hnc_admin.yaml
  incubator/hnc/config/rbac/kustomization.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#1489 Support cluster-admin propagation and update docs
  incubator/hnc/Makefile
  incubator/hnc/config/rbac/role.yaml
  incubator/hnc/docs/user-guide/faq.md
  incubator/hnc/docs/user-guide/how-to.md
  incubator/hnc/internal/reconcilers/object.go
  incubator/hnc/test/e2e/issues_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1487 Update cert-rotator to 0.2.0; tweak test targets
  incubator/hnc/Makefile
  incubator/hnc/go.mod
  incubator/hnc/go.sum
  incubator/hnc/vendor/github.com/open-policy-agent/cert-controller/pkg/rotator/rotator.go
  incubator/hnc/vendor/modules.txt
Labels: approved, cncf-cla: yes, lgtm, size/L

#1493 Disable broken test
  incubator/hnc/test/e2e/issues_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1488 Sync object propagation on newly labeled namespaces
  incubator/hnc/internal/forest/namespace.go
  incubator/hnc/internal/reconcilers/hierarchy_config.go
  incubator/hnc/internal/reconcilers/object_test.go
  incubator/hnc/internal/reconcilers/test_helpers_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1496 Update docs for upcoming v0.8
  incubator/hnc/docs/user-guide/README.md
  incubator/hnc/docs/user-guide/concepts.md
  incubator/hnc/docs/user-guide/how-to.md
  incubator/hnc/docs/user-guide/quickstart.md
Labels: approved, cncf-cla: yes, lgtm, size/L

#1498 Increase HNC release timeout to 30m (HNC v0.8 branch)
  incubator/hnc/Makefile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1499 Increase HNC release timeout to 30m (master branch)
  incubator/hnc/Makefile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1501 Update all docs to point to HNC v0.8.0
  incubator/hnc/README.md
  incubator/hnc/docs/user-guide/how-to.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#1504 Update all docs to point to HNC v0.8.0 (master)
  incubator/hnc/README.md
  incubator/hnc/docs/user-guide/how-to.md
Labels: approved, cncf-cla: yes, lgtm, size/S
