Repository kubernetes-sigs/multi-tenancy, pull requests merged in 2021-01, with the labels that each got.

#1334 [VC] Add scheduler resource watcher framework
  incubator/virtualcluster/experiment/cmd/scheduler/app/config/config.go
  incubator/virtualcluster/experiment/cmd/scheduler/app/options/options.go
  incubator/virtualcluster/experiment/cmd/scheduler/app/server.go
  incubator/virtualcluster/experiment/pkg/scheduler/constants/constants.go
  incubator/virtualcluster/experiment/pkg/scheduler/manager/manager.go
  incubator/virtualcluster/experiment/pkg/scheduler/scheduler.go
  incubator/virtualcluster/experiment/pkg/scheduler/watcher/virtualcluster/register.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1335 [VC] Add virtualcluster reconciler
  incubator/virtualcluster/experiment/pkg/scheduler/manager/manager.go
  incubator/virtualcluster/experiment/pkg/scheduler/reconciler.go
  incubator/virtualcluster/experiment/pkg/scheduler/resource/virtualcluster/register.go
  incubator/virtualcluster/experiment/pkg/scheduler/scheduler.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1337 VC: introduce differ to optimize patroller algorithm
  incubator/virtualcluster/pkg/syncer/conversion/helper.go
  incubator/virtualcluster/pkg/syncer/patrol/differ/differ.go
  incubator/virtualcluster/pkg/syncer/patrol/differ/differ_test.go
  incubator/virtualcluster/pkg/syncer/patrol/differ/handler.go
  incubator/virtualcluster/pkg/syncer/resources/configmap/checker.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#1317 MTB: added custom deployment func
  benchmarks/kubectl-mtb/test/benchmarks/block_use_of_nodeport_services/block_use_of_nodeport_services.go
  benchmarks/kubectl-mtb/test/benchmarks/require_always_pull_image/README.md
  benchmarks/kubectl-mtb/test/utils/resources/deployment/deployment.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1338 [VC] Add Client support for cluster CRD
  incubator/virtualcluster/experiment/cmd/scheduler/app/config/config.go
  incubator/virtualcluster/experiment/cmd/scheduler/app/options/options.go
  incubator/virtualcluster/experiment/cmd/scheduler/app/server.go
  incubator/virtualcluster/experiment/pkg/apis/cluster/v1alpha4/cluster_phase_types.go
  incubator/virtualcluster/experiment/pkg/apis/cluster/v1alpha4/cluster_types.go
  incubator/virtualcluster/experiment/pkg/apis/cluster/v1alpha4/condition_types.go
  incubator/virtualcluster/experiment/pkg/apis/cluster/v1alpha4/doc.go
  incubator/virtualcluster/experiment/pkg/apis/cluster/v1alpha4/register.go
  incubator/virtualcluster/experiment/pkg/apis/cluster/v1alpha4/zz_generated.deepcopy.go
  incubator/virtualcluster/experiment/pkg/client/clientset/versioned/clientset.go
  incubator/virtualcluster/experiment/pkg/client/clientset/versioned/doc.go
  incubator/virtualcluster/experiment/pkg/client/clientset/versioned/fake/clientset_generated.go
  incubator/virtualcluster/experiment/pkg/client/clientset/versioned/fake/doc.go
  incubator/virtualcluster/experiment/pkg/client/clientset/versioned/fake/register.go
  incubator/virtualcluster/experiment/pkg/client/clientset/versioned/scheme/doc.go
  incubator/virtualcluster/experiment/pkg/client/clientset/versioned/scheme/register.go
  incubator/virtualcluster/experiment/pkg/client/clientset/versioned/typed/cluster/v1alpha4/cluster.go
  incubator/virtualcluster/experiment/pkg/client/clientset/versioned/typed/cluster/v1alpha4/cluster_client.go
  incubator/virtualcluster/experiment/pkg/client/clientset/versioned/typed/cluster/v1alpha4/doc.go
  incubator/virtualcluster/experiment/pkg/client/clientset/versioned/typed/cluster/v1alpha4/fake/doc.go
  incubator/virtualcluster/experiment/pkg/client/clientset/versioned/typed/cluster/v1alpha4/fake/fake_cluster.go
  incubator/virtualcluster/experiment/pkg/client/clientset/versioned/typed/cluster/v1alpha4/fake/fake_cluster_client.go
  incubator/virtualcluster/experiment/pkg/client/clientset/versioned/typed/cluster/v1alpha4/generated_expansion.go
  incubator/virtualcluster/experiment/pkg/client/informers/externalversions/cluster/interface.go
  incubator/virtualcluster/experiment/pkg/client/informers/externalversions/cluster/v1alpha4/cluster.go
  incubator/virtualcluster/experiment/pkg/client/informers/externalversions/cluster/v1alpha4/interface.go
  incubator/virtualcluster/experiment/pkg/client/informers/externalversions/factory.go
  incubator/virtualcluster/experiment/pkg/client/informers/externalversions/generic.go
  incubator/virtualcluster/experiment/pkg/client/informers/externalversions/internalinterfaces/factory_interfaces.go
  incubator/virtualcluster/experiment/pkg/client/listers/cluster/v1alpha4/cluster.go
  incubator/virtualcluster/experiment/pkg/client/listers/cluster/v1alpha4/expansion_generated.go
  incubator/virtualcluster/experiment/pkg/scheduler/scheduler.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#1340 [VC] Add supercluster reconciling loop
  incubator/virtualcluster/experiment/pkg/scheduler/constants/constants.go
  incubator/virtualcluster/experiment/pkg/scheduler/reconciler.go
  incubator/virtualcluster/experiment/pkg/scheduler/resource/supercluster/register.go
  incubator/virtualcluster/experiment/pkg/scheduler/scheduler.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1342 [VC] Make Cluster and MultiClusterController generic
  incubator/virtualcluster/cmd/syncer/app/options/options.go
  incubator/virtualcluster/cmd/syncer/app/server.go
  incubator/virtualcluster/experiment/pkg/scheduler/reconciler.go
  incubator/virtualcluster/pkg/syncer/cluster/cluster.go
  incubator/virtualcluster/pkg/syncer/cluster/fake_cluster.go
  incubator/virtualcluster/pkg/syncer/conversion/mutate.go
  incubator/virtualcluster/pkg/syncer/mccontroller/mccontroller.go
  incubator/virtualcluster/pkg/syncer/resources/configmap/checker.go
  incubator/virtualcluster/pkg/syncer/resources/configmap/dws.go
  incubator/virtualcluster/pkg/syncer/resources/endpoints/dws.go
  incubator/virtualcluster/pkg/syncer/resources/ingress/checker.go
  incubator/virtualcluster/pkg/syncer/resources/ingress/dws.go
  incubator/virtualcluster/pkg/syncer/resources/ingress/uws.go
  incubator/virtualcluster/pkg/syncer/resources/persistentvolumeclaim/checker.go
  incubator/virtualcluster/pkg/syncer/resources/persistentvolumeclaim/dws.go
  incubator/virtualcluster/pkg/syncer/resources/pod/checker.go
  incubator/virtualcluster/pkg/syncer/resources/pod/dws.go
  incubator/virtualcluster/pkg/syncer/resources/pod/uws.go
  incubator/virtualcluster/pkg/syncer/resources/secret/checker.go
  incubator/virtualcluster/pkg/syncer/resources/secret/dws.go
  incubator/virtualcluster/pkg/syncer/resources/service/checker.go
  incubator/virtualcluster/pkg/syncer/resources/service/dws.go
  incubator/virtualcluster/pkg/syncer/resources/service/uws.go
  incubator/virtualcluster/pkg/syncer/syncer.go
  incubator/virtualcluster/pkg/syncer/util/feature/feature.go
  incubator/virtualcluster/pkg/syncer/util/helper.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1345 VC: add vc ns to each object
  incubator/virtualcluster/pkg/syncer/conversion/helper.go
  incubator/virtualcluster/pkg/syncer/resources/configmap/dws.go
  incubator/virtualcluster/pkg/syncer/resources/endpoints/dws.go
  incubator/virtualcluster/pkg/syncer/resources/ingress/dws.go
  incubator/virtualcluster/pkg/syncer/resources/persistentvolume/uws.go
  incubator/virtualcluster/pkg/syncer/resources/persistentvolumeclaim/dws.go
  incubator/virtualcluster/pkg/syncer/resources/pod/dws.go
  incubator/virtualcluster/pkg/syncer/resources/secret/dws.go
  incubator/virtualcluster/pkg/syncer/resources/service/dws.go
  incubator/virtualcluster/pkg/syncer/resources/serviceaccount/dws.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1346 [VC] Fix a field name conflict in Cluster
  incubator/virtualcluster/pkg/util/cluster/cluster.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1349 [VC] Introduce basic structures (Pod, Namespace, Cluster) for scheduler cache
  incubator/virtualcluster/experiment/pkg/scheduler/cache/cluster.go
  incubator/virtualcluster/experiment/pkg/scheduler/cache/cluster_test.go
  incubator/virtualcluster/experiment/pkg/scheduler/cache/namespace.go
  incubator/virtualcluster/experiment/pkg/scheduler/cache/namespace_test.go
  incubator/virtualcluster/experiment/pkg/scheduler/cache/pod.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#1350 HNC produces double colons on error message
  incubator/hnc/internal/validators/hierarchy.go
  incubator/hnc/internal/validators/hncconfig.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#1352 [VC] Introduce SchedulerCache
  incubator/virtualcluster/experiment/pkg/scheduler/cache/cache.go
  incubator/virtualcluster/experiment/pkg/scheduler/cache/cache_test.go
  incubator/virtualcluster/experiment/pkg/scheduler/cache/cluster_test.go
  incubator/virtualcluster/experiment/pkg/scheduler/cache/interface.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1353 VC: syncer: sync scheduled object in SuperClusterPool mode
  incubator/virtualcluster/cmd/syncer/app/options/options.go
  incubator/virtualcluster/cmd/syncer/app/server.go
  incubator/virtualcluster/pkg/syncer/syncer.go
  incubator/virtualcluster/pkg/syncer/util/feature/feature.go
  incubator/virtualcluster/pkg/syncer/util/featuregate/gate.go
  incubator/virtualcluster/pkg/util/constants/constants.go
  incubator/virtualcluster/pkg/util/mccontroller/mccontroller.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1357 [VC] Fix UT breakage
  incubator/virtualcluster/pkg/syncer/resources/pod/dws_test.go
  incubator/virtualcluster/pkg/syncer/resources/secret/checker_test.go
  incubator/virtualcluster/pkg/syncer/resources/secret/dws_test.go
  incubator/virtualcluster/pkg/syncer/util/featuregate/gate.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1358 VC: mccontroller: add listener adapter
  incubator/virtualcluster/pkg/syncer/manager/manager.go
  incubator/virtualcluster/pkg/syncer/resources/configmap/controller.go
  incubator/virtualcluster/pkg/syncer/resources/endpoints/controller.go
  incubator/virtualcluster/pkg/syncer/resources/event/controller.go
  incubator/virtualcluster/pkg/syncer/resources/ingress/controller.go
  incubator/virtualcluster/pkg/syncer/resources/namespace/controller.go
  incubator/virtualcluster/pkg/syncer/resources/node/controller.go
  incubator/virtualcluster/pkg/syncer/resources/persistentvolume/controller.go
  incubator/virtualcluster/pkg/syncer/resources/persistentvolumeclaim/controller.go
  incubator/virtualcluster/pkg/syncer/resources/pod/controller.go
  incubator/virtualcluster/pkg/syncer/resources/priorityclass/controller.go
  incubator/virtualcluster/pkg/syncer/resources/secret/controller.go
  incubator/virtualcluster/pkg/syncer/resources/service/controller.go
  incubator/virtualcluster/pkg/syncer/resources/serviceaccount/controller.go
  incubator/virtualcluster/pkg/syncer/resources/storageclass/controller.go
  incubator/virtualcluster/pkg/syncer/util/test/runDWS.go
  incubator/virtualcluster/pkg/syncer/util/test/runPatrol.go
  incubator/virtualcluster/pkg/syncer/util/test/runUWS.go
  incubator/virtualcluster/pkg/util/listener/adapter.go
  incubator/virtualcluster/pkg/util/mccontroller/mccontroller.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1359 [VC] Finish reconciling super cluster CR in scheduler
  incubator/virtualcluster/experiment/cmd/scheduler/app/server.go
  incubator/virtualcluster/experiment/config/crd/cluster.x-k8s.io_clusters.yaml
  incubator/virtualcluster/experiment/config/setup/all_in_one.yaml
  incubator/virtualcluster/experiment/pkg/scheduler/reconciler.go
  incubator/virtualcluster/pkg/syncer/syncer.go
  incubator/virtualcluster/pkg/util/constants/constants.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1360 VC: syncer: start watch cluster event after cache sync
  incubator/virtualcluster/pkg/syncer/syncer.go
  incubator/virtualcluster/pkg/syncer/util/test/runDWS.go
  incubator/virtualcluster/pkg/syncer/util/test/runPatrol.go
  incubator/virtualcluster/pkg/syncer/util/test/runUWS.go
  incubator/virtualcluster/pkg/util/cluster/cluster.go
  incubator/virtualcluster/pkg/util/cluster/fake_cluster.go
  incubator/virtualcluster/pkg/util/listener/adapter.go
  incubator/virtualcluster/pkg/util/listener/listener.go
  incubator/virtualcluster/pkg/util/mccontroller/mccontroller.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1356 MTB: changed flag input format
  benchmarks/kubectl-mtb/go.sum
  benchmarks/kubectl-mtb/internal/kubectl-mtb/run.go
  benchmarks/kubectl-mtb/test/benchmarks/block_use_of_nodeport_services/block_use_of_nodeport_services.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1365 [VC] Use new listener interface in Scheduler
  incubator/virtualcluster/experiment/pkg/scheduler/manager/manager.go
  incubator/virtualcluster/experiment/pkg/scheduler/reconciler.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#1363 [VC] syncer: using generic scheme register instead of hand writing
  incubator/virtualcluster/pkg/syncer/manager/manager.go
  incubator/virtualcluster/pkg/syncer/patrol/options.go
  incubator/virtualcluster/pkg/syncer/patrol/patroller.go
  incubator/virtualcluster/pkg/syncer/resources/configmap/controller.go
  incubator/virtualcluster/pkg/syncer/resources/endpoints/controller.go
  incubator/virtualcluster/pkg/syncer/resources/event/controller.go
  incubator/virtualcluster/pkg/syncer/resources/ingress/checker_test.go
  incubator/virtualcluster/pkg/syncer/resources/ingress/controller.go
  incubator/virtualcluster/pkg/syncer/resources/ingress/dws_test.go
  incubator/virtualcluster/pkg/syncer/resources/ingress/uws_test.go
  incubator/virtualcluster/pkg/syncer/resources/namespace/controller.go
  incubator/virtualcluster/pkg/syncer/resources/node/controller.go
  incubator/virtualcluster/pkg/syncer/resources/persistentvolume/controller.go
  incubator/virtualcluster/pkg/syncer/resources/persistentvolumeclaim/controller.go
  incubator/virtualcluster/pkg/syncer/resources/pod/controller.go
  incubator/virtualcluster/pkg/syncer/resources/priorityclass/checker_test.go
  incubator/virtualcluster/pkg/syncer/resources/priorityclass/controller.go
  incubator/virtualcluster/pkg/syncer/resources/priorityclass/uws_test.go
  incubator/virtualcluster/pkg/syncer/resources/register.go
  incubator/virtualcluster/pkg/syncer/resources/secret/controller.go
  incubator/virtualcluster/pkg/syncer/resources/service/controller.go
  incubator/virtualcluster/pkg/syncer/resources/serviceaccount/controller.go
  incubator/virtualcluster/pkg/syncer/resources/storageclass/controller.go
  incubator/virtualcluster/pkg/syncer/util/scheme/scheme.go
  incubator/virtualcluster/pkg/syncer/util/scheme/scheme_test.go
  incubator/virtualcluster/pkg/syncer/util/test/runDWS.go
  incubator/virtualcluster/pkg/syncer/util/test/runPatrol.go
  incubator/virtualcluster/pkg/syncer/util/test/runUWS.go
  incubator/virtualcluster/pkg/syncer/uwcontroller/options.go
  incubator/virtualcluster/pkg/syncer/uwcontroller/uwcontroller.go
  incubator/virtualcluster/pkg/util/mccontroller/mccontroller.go
  incubator/virtualcluster/pkg/util/mccontroller/options.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#1361 add necessary helper functions and changes to support CRD sync
  incubator/virtualcluster/cmd/syncer/app/options/options.go
  incubator/virtualcluster/pkg/util/cluster/cluster.go
  incubator/virtualcluster/pkg/util/cluster/fake_cluster.go
  incubator/virtualcluster/pkg/util/mccontroller/mccontroller.go
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/M
